Repository openshift/insights-operator, pull requests merged in 2019-10, with the labels that each got.

#24 Add inecas to OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#31 Unit test options
  Makefile
  README.md
Labels: approved, lgtm, size/S

#35 gather: consider restarting pods as not healthy
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, lgtm, size/XS

#36 gather: include events in report
  manifests/03-clusterrole.yaml
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, lgtm, size/M
