Repository openshift/insights-operator, pull requests merged in 2019-11, with the labels that each got.

#26 Enabling metrics exchange with prometheus
  manifests/02-namespace.yaml
  manifests/03-prometheus_role.yaml
  manifests/03-prometheus_rolebinding.yaml
  manifests/05-service.yaml
  manifests/06-deployment.yaml
  manifests/07-cluster-operator.yaml
  manifests/07-servicemonitor.yaml
  pkg/insights/insightsclient/insightsclient.go
Labels: approved, lgtm, ok-to-test, size/M

#42 api to metrics service changed from prometheus to legacyregistry
  pkg/insights/insightsclient/insightsclient.go
Labels: approved, lgtm, ok-to-test, size/S

#40 gather: Collect some prometheus metrics for the cluster
  go.mod
  go.sum
  manifests/03-clusterrole.yaml
  pkg/cmd/start/start.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/record/interface.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/client_metrics.go
  vendor/github.com/openshift/library-go/pkg/controller/metrics/workqueue_metrics.go
  vendor/github.com/openshift/library-go/pkg/crypto/crypto.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#45 Add manifest annotations for hosted deployment exclusions
  manifests/05-service.yaml
  manifests/06-deployment.yaml
  manifests/07-cluster-operator.yaml
  manifests/07-servicemonitor.yaml
Labels: approved, lgtm, ok-to-test

#48 insightsclient: Report the amount of data written
  pkg/insights/insightsclient/insightsclient.go
Labels: approved, lgtm, size/XS

#49 bump(*): fix fileobserver logging
  go.mod
  go.sum
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/modules.txt
Labels: approved, lgtm, size/S

#38 Bug 1767719: gather: include network events for namespace that has degraded operator
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/M

#51 Added dummy e2e target
  Makefile
Labels: approved, lgtm, size/S

#53 Fixed unit test command
  Makefile
Labels: approved, lgtm, size/XS

#56 Bug 1767719: Fix the event reporting in insights operator
  manifests/03-clusterrole.yaml
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/L

#55 Added dummy e2e target for release 4.3
  Makefile
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/S
