Repository openshift/insights-operator, pull requests merged in 2019-08, with the labels that each got.

#1 rename: Rename support-operator to insights-operator
  Dockerfile
  Makefile
  README.md
  cmd/insights-operator/main.go
  config/pod.yaml
  glide.yaml
  manifests/05-deployment.yaml
  manifests/image-references
  pkg/authorizer/clusterauthorizer/clusterauthorizer.go
  pkg/cmd/start/start.go
  pkg/config/configobserver/configobserver.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/controller/status/status.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/interface.go
  pkg/insights/insightsclient/insightsclient.go
  pkg/insights/insightsuploader/insightsuploader.go
  pkg/record/diskrecorder/diskrecorder.go
Labels: approved, lgtm, size/M

#2 Bug 1738495: Invalid token is reported as error in cluster status
  pkg/authorizer/clusterauthorizer/clusterauthorizer.go
  pkg/config/configobserver/configobserver.go
  pkg/insights/insightsclient/insightsclient.go
Labels: approved, bugzilla/valid-bug, lgtm, size/S

#3 Add mfojtik to OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS

#7 Bug 1744297: pkg/controller/status/status: Never go degraded (hack)
  pkg/controller/status/status.go
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#6 Anonymize APIServerInteranlURL
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, lgtm, size/XS

#10 Provide initial proxy support for insights operator
  manifests/04-proxy-cert-configmap.yaml
  manifests/05-deployment.yaml
  pkg/controller/operator.go
  pkg/insights/insightsclient/insightsclient.go
Labels: approved, lgtm, size/M

#13 Synchronize gathering and flushing
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/record/diskrecorder/diskrecorder.go
  pkg/record/interface.go
Labels: approved, lgtm, size/M

#14 gather: Capture failing nodes during gather pass
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/record/interface.go
  pkg/record/interface_test.go
Labels: approved, lgtm, size/L
