Repository openshift/insights-operator, pull requests merged in 2020-02, with the labels that each got.

#65 Bug 1797563: added TestUnreachableHost
  Makefile
  test/integration/basic_test.go
  test/integration/bugs_test.go
  test/integration/main_test.go
Labels: approved, bugzilla/valid-bug, lgtm, size/L

#71 Add alexandrevicenzi as code owner
  OWNERS
Labels: approved, bugzilla/valid-bug, lgtm, size/XS

#76 Backport code owners to 4.3
  OWNERS
Labels: approved, lgtm, size/XS

#75 Backport code owners to 4.2
  OWNERS
Labels: size/XS

#64 Bug 1788116: override node selector (4.2)
  manifests/02-namespace.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#57 Bug 1798889: initial commit for tests for release 4.2
  test/integration/bugs_test.go
  test/integration/main_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test, size/L

#63 Bug 1788112: override node selector (4.3)
  manifests/02-namespace.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, size/XS

#77 Insightsclient metrics - small bugfix , added status code '0'.
  pkg/insights/insightsclient/insightsclient.go
Labels: approved, lgtm, ok-to-test, size/XS

#73 Add license
  LICENSE
Labels: approved, lgtm, size/L

#70 Collect certificates
  .gitignore
  Makefile
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/csr.go
  pkg/gather/clusterconfig/csr_test.go
  pkg/gather/clusterconfig/testdata/csr_appr.json
  pkg/gather/clusterconfig/testdata/csr_appr_anon.json
  pkg/gather/clusterconfig/testdata/csr_unappr.json
  pkg/gather/clusterconfig/testdata/csr_unappr_anon.json
  pkg/utils/strings.go
Labels: approved, lgtm, ok-to-test, size/XL

#72 Updated base image for insights-operator
  Dockerfile
Labels: approved, lgtm, size/XS

#78 manifests: Remove run-level, insights operator does not need it
  manifests/02-namespace.yaml
Labels: approved, lgtm, size/XS

#81 add new test TestClusterDefaultNodeSelector
  test/integration/bugs_test.go
  test/integration/main_test.go
Labels: approved, lgtm, size/M
