Repository openshift/insights-operator, pull requests merged in 2020-01, with the labels that each got.

#59 Bug 1782151 - override node selector
  manifests/02-namespace.yaml
Labels: approved, lgtm, size/XS

#61 added TestOptOutOptIn and moved some code to functions
  test/integration/basic_test.go
  test/integration/bugs_test.go
  test/integration/main_test.go
Labels: approved, lgtm, needs-ok-to-test, size/L

#62 Add Pavel Tisnovsky into list of repo owners
  OWNERS
Labels: approved, lgtm, size/XS

#58 Bug 1788118: initial commit for tests for release 4.3
  test/integration/bugs_test.go
  test/integration/main_test.go
Labels: approved, bugzilla/valid-bug, lgtm, ok-to-test, size/L

#66 insightsclient: include error message when we are unable to build request
  pkg/insights/insightsclient/insightsclient.go
Labels: approved, lgtm, size/XS

#69 gather: Only return pods that have been pending more than 2m
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, lgtm, size/S
