Repository openshift/insights-operator, pull requests merged in 2020-07, with the labels that each got.

#129 Updating sample data
  docs/gathered-data.md
  docs/insights-archive-sample/config/authentication.json
  docs/insights-archive-sample/config/featuregate.json
  docs/insights-archive-sample/config/imagepruner.json
  docs/insights-archive-sample/config/imageregistry.json
  docs/insights-archive-sample/config/infrastructure.json
  docs/insights-archive-sample/config/ingress.json
  docs/insights-archive-sample/config/metrics
  docs/insights-archive-sample/config/network
  docs/insights-archive-sample/config/network.json
  docs/insights-archive-sample/config/node/ci-ln-3z9y7mt-f76d1-69jcr-master-0.json
  docs/insights-archive-sample/config/node/ci-ln-3z9y7mt-f76d1-69jcr-master-1.json
  docs/insights-archive-sample/config/node/ci-ln-3z9y7mt-f76d1-69jcr-master-2.json
  docs/insights-archive-sample/config/node/ci-ln-3z9y7mt-f76d1-69jcr-worker-b-q6vs9.json
  docs/insights-archive-sample/config/node/ci-ln-3z9y7mt-f76d1-69jcr-worker-c-h8zcp.json
  docs/insights-archive-sample/config/node/ci-ln-3z9y7mt-f76d1-69jcr-worker-d-pbtms.json
  docs/insights-archive-sample/config/oauth.json
  docs/insights-archive-sample/config/proxy.json
  docs/insights-archive-sample/config/version.json
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, lgtm

#132 Check also Pod status before enabling Fast upload
  pkg/controller/operator.go
  pkg/controller/status/status.go
  pkg/insights/insightsuploader/insightsuploader.go
Labels: approved, lgtm

#116 Bug 1840012: [release-4.4] pkg: write files with extension
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/csr.go
  pkg/record/diskrecorder/diskrecorder.go
  pkg/record/interface.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#141 Info how to retrieve key and certificate and simple script to do so
  README.md
  tools/gen_cert_key.py
Labels: approved, lgtm

#134 Test pods logs collected - Automate BZ1838973
  go.sum
  test/integration/bugs_test.go
  test/integration/main_test.go
  vendor/github.com/docker/spdystream/CONTRIBUTING.md
  vendor/github.com/docker/spdystream/LICENSE
  vendor/github.com/docker/spdystream/LICENSE.docs
  vendor/github.com/docker/spdystream/MAINTAINERS
  vendor/github.com/docker/spdystream/README.md
  vendor/github.com/docker/spdystream/connection.go
  vendor/github.com/docker/spdystream/handlers.go
  vendor/github.com/docker/spdystream/priority.go
  vendor/github.com/docker/spdystream/spdy/dictionary.go
  vendor/github.com/docker/spdystream/spdy/read.go
  vendor/github.com/docker/spdystream/spdy/types.go
  vendor/github.com/docker/spdystream/spdy/write.go
  vendor/github.com/docker/spdystream/stream.go
  vendor/github.com/docker/spdystream/utils.go
  vendor/github.com/getsentry/raven-go/Dockerfile.test
  vendor/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  vendor/k8s.io/apimachinery/pkg/util/remotecommand/constants.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/addr.go
  vendor/k8s.io/client-go/tools/remotecommand/doc.go
  vendor/k8s.io/client-go/tools/remotecommand/errorstream.go
  vendor/k8s.io/client-go/tools/remotecommand/reader.go
  vendor/k8s.io/client-go/tools/remotecommand/remotecommand.go
  vendor/k8s.io/client-go/tools/remotecommand/resize.go
  vendor/k8s.io/client-go/tools/remotecommand/v1.go
  vendor/k8s.io/client-go/tools/remotecommand/v2.go
  vendor/k8s.io/client-go/tools/remotecommand/v3.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/client-go/transport/spdy/spdy.go
  vendor/k8s.io/client-go/util/exec/exec.go
  vendor/modules.txt
Labels: approved, lgtm, ok-to-test

#144 TestPodLogsCollected fix
  test/integration/bugs_test.go
Labels: approved, lgtm, ok-to-test

#135 Shorten e2e tests interval
  Makefile
Labels: approved, lgtm

#133 Bug 1860032: Running Red Hat images and crashlooping OpenShift pods should be gathered
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, ok-to-test
