Repository openshift/insights-operator, pull requests merged in 2020-12, with the labels that each got.

#274 Bug 1903639: Add hostsubnet to sample archive & fix bug in the hostsu…
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-0.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-1.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-2.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-worker-b-56nwr.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-worker-c-wkwh7.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-worker-d-mdwl8.json
  pkg/gather/clusterconfig/host_subnets.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#277 Annotate manifests for single-node-developer cluster profile
  manifests/02-namespace.yaml
  manifests/03-clusterrole.yaml
  manifests/03-prometheus_role.yaml
  manifests/03-prometheus_rolebinding.yaml
  manifests/04-proxy-cert-configmap.yaml
  manifests/04-service-ca-configmap.yaml
  manifests/04-serviceaccount.yaml
  manifests/05-service.yaml
  manifests/06-deployment.yaml
  manifests/07-cluster-operator.yaml
  manifests/07-servicemonitor.yaml
Labels: approved, lgtm

#267 Cleanup clusterOperatorInsights helper function
  test/integration/basic_test.go
  test/integration/bugs_test.go
  test/integration/main_test.go
Labels: approved, lgtm, ok-to-test

#281 Fix bug in statefulset gatherer & minor doc fix
  docs/gathered-data.md
  pkg/gather/clusterconfig/image_pruners.go
  pkg/gather/clusterconfig/stateful_sets.go
Labels: approved, lgtm

#270 First check IO container status and optionally delay first gathering
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
  pkg/insights/insightsuploader/insightsuploader.go
  test/integration/basic_test.go
Labels: approved, lgtm

#252 [release-4.5] Backport e2e tests
  Makefile
  go.sum
  test/integration/basic_test.go
  test/integration/bugs_test.go
  test/integration/log_checker.go
  test/integration/main_test.go
  test/integration/resource_samples/apply.sh
  test/integration/resource_samples/csr.yaml
  test/integration/resource_samples/machineset.yaml
  vendor/github.com/docker/spdystream/CONTRIBUTING.md
  vendor/github.com/docker/spdystream/LICENSE
  vendor/github.com/docker/spdystream/LICENSE.docs
  vendor/github.com/docker/spdystream/MAINTAINERS
  vendor/github.com/docker/spdystream/README.md
  vendor/github.com/docker/spdystream/connection.go
  vendor/github.com/docker/spdystream/handlers.go
  vendor/github.com/docker/spdystream/priority.go
  vendor/github.com/docker/spdystream/spdy/dictionary.go
  vendor/github.com/docker/spdystream/spdy/read.go
  vendor/github.com/docker/spdystream/spdy/types.go
  vendor/github.com/docker/spdystream/spdy/write.go
  vendor/github.com/docker/spdystream/stream.go
  vendor/github.com/docker/spdystream/utils.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/doc.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/httpstream.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/connection.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/roundtripper.go
  vendor/k8s.io/apimachinery/pkg/util/httpstream/spdy/upgrade.go
  vendor/k8s.io/apimachinery/pkg/util/remotecommand/constants.go
  vendor/k8s.io/apimachinery/third_party/forked/golang/netutil/addr.go
  vendor/k8s.io/client-go/tools/remotecommand/doc.go
  vendor/k8s.io/client-go/tools/remotecommand/errorstream.go
  vendor/k8s.io/client-go/tools/remotecommand/reader.go
  vendor/k8s.io/client-go/tools/remotecommand/remotecommand.go
  vendor/k8s.io/client-go/tools/remotecommand/resize.go
  vendor/k8s.io/client-go/tools/remotecommand/v1.go
  vendor/k8s.io/client-go/tools/remotecommand/v2.go
  vendor/k8s.io/client-go/tools/remotecommand/v3.go
  vendor/k8s.io/client-go/tools/remotecommand/v4.go
  vendor/k8s.io/client-go/transport/spdy/spdy.go
  vendor/k8s.io/client-go/util/exec/exec.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#275 Adding a metrics report to IO gatherers
  pkg/record/interface.go
Labels: approved, lgtm

#226 [release 4.6] Bug 1888602: Fixes policyClient and the corresponding config.
  manifests/03-clusterrole.yaml
  pkg/controller/operator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#289 Check context status when checking container is running OK
  pkg/controller/operator.go
Labels: approved, lgtm

#292 Update initial waiting times and give TestIsIOHealthy more time
  Makefile
  pkg/controller/operator.go
Labels: approved, lgtm

#255 Diskrecorder simplify the Summary function
  pkg/record/diskrecorder/diskrecorder.go
Labels: approved, lgtm

#282 Adds github pull request template.
  .github/pull_request_template.md
Labels: approved, lgtm

#295 Skip TestArchiveUploadedAndResultReceived
  test/integration/basic_test.go
Labels: approved, lgtm

#276 [release-4.6] Bug 1904014: Add hostsubnet to sample archive & fix bug…
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-0.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-1.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-2.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-worker-b-56nwr.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-worker-c-wkwh7.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-worker-d-mdwl8.json
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#221 [release 4.6] Bug 1888165: Add the namespace to the gatherers reports to avoid conflicts
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#296 Bug 1907293: e2e tests - increase timeouts little bit
  Makefile
  test/integration/bugs_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#297 Bug 1907378: Gather netnamespaces network info
  docs/gathered-data.md
  docs/insights-archive-sample/config/netnamespaces.json
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/netnamespaces.go
  pkg/gather/clusterconfig/netnamespaces_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#279 Bug 1907876: Refactoring record and gatherer
  config/local.yaml
  config/pod.yaml
  docs/arch.md
  docs/gathered-data.md
  pkg/config/config.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/gather/clusterconfig/0_gahterer_test.go
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/authentications.go
  pkg/gather/clusterconfig/certificate_signing_requests.go
  pkg/gather/clusterconfig/config_maps.go
  pkg/gather/clusterconfig/container_images.go
  pkg/gather/clusterconfig/container_runtime_configs.go
  pkg/gather/clusterconfig/custom_resource_definitions.go
  pkg/gather/clusterconfig/feature_gates.go
  pkg/gather/clusterconfig/host_subnets.go
  pkg/gather/clusterconfig/image_pruners.go
  pkg/gather/clusterconfig/image_registries.go
  pkg/gather/clusterconfig/infrastructures.go
  pkg/gather/clusterconfig/ingresses.go
  pkg/gather/clusterconfig/install_plans.go
  pkg/gather/clusterconfig/machine_config_pools.go
  pkg/gather/clusterconfig/machine_sets.go
  pkg/gather/clusterconfig/netnamespaces.go
  pkg/gather/clusterconfig/networks.go
  pkg/gather/clusterconfig/nodes.go
  pkg/gather/clusterconfig/oauths.go
  pkg/gather/clusterconfig/operators.go
  pkg/gather/clusterconfig/pod_disruption_budgets.go
  pkg/gather/clusterconfig/proxies.go
  pkg/gather/clusterconfig/recent_metrics.go
  pkg/gather/clusterconfig/service_accounts.go
  pkg/gather/clusterconfig/stateful_sets.go
  pkg/gather/clusterconfig/version.go
  pkg/gather/interface.go
  pkg/insights/insightsclient/insightsclient.go
  pkg/record/interface.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#298 Bug 1908400:tests-e2e, increase timeouts, re-add TestArchiveUploadedAndResultsReceived
  Makefile
  test/integration/basic_test.go
  test/integration/log_checker.go
  test/integration/main_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#261 [release-4.6] Bug 1894244: Fixes records index on diskrecorder
  pkg/record/diskrecorder/diskrecorder.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
