Repository openshift/insights-operator, pull requests merged in 2020-03, with the labels that each got.

#82 add coverage for BZ1753755
  test/integration/bugs_test.go
Labels: approved, lgtm, size/S

#85 Add test to observe config changes
  pkg/config/configobserver/configobserver.go
  pkg/config/configobserver/configobserver_test.go
Labels: approved, lgtm, size/L

#88 Report logs when checkPods is going to fail
  test/integration/basic_test.go
  test/integration/bugs_test.go
  test/integration/main_test.go
Labels: approved, lgtm
