Repository openshift/insights-operator, pull requests merged in 2020-09, with the labels that each got.

#170 [release-4.3] Bug 1874427: Add @natiiix to OWNERS
  OWNERS
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#137 [release-4.3] Bug 1843923: Don't delay first
  pkg/controller/operator.go
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
  pkg/insights/insightsuploader/insightsuploader.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/doc.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_apiserver.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_authentication.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_build.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusteroperator.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_clusterversion.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_config_client.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_console.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_dns.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_featuregate.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_image.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_infrastructure.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_ingress.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_network.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_oauth.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_project.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_proxy.go
  vendor/github.com/openshift/client-go/config/clientset/versioned/typed/config/v1/fake/fake_scheduler.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#176 Bug 1876858: manifests: rename operator container to be more descriptive
  manifests/06-deployment.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#171 Bug 1879070: Add metrics back to archive sample
  docs/insights-archive-sample/config/metrics
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#177 Bug 1879068: Collect hostsubnet information
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  vendor/github.com/openshift/api/network/v1/constants.go
  vendor/github.com/openshift/api/network/v1/doc.go
  vendor/github.com/openshift/api/network/v1/generated.pb.go
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/network/v1/legacy.go
  vendor/github.com/openshift/api/network/v1/register.go
  vendor/github.com/openshift/api/network/v1/types.go
  vendor/github.com/openshift/api/network/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/network/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/clusternetwork.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/doc.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/egressnetworkpolicy.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/doc.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/fake_clusternetwork.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/fake_egressnetworkpolicy.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/fake_hostsubnet.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/fake_netnamespace.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/fake_network_client.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/hostsubnet.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/netnamespace.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/network_client.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#188 Bug 1881848: Do not return CRD not found error, just log it
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#187 Bug 1881364: Add new team members to OWNERS
  OWNERS
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#183 Bug 1881816: Gather MachineSet info
  docs/gathered-data.md
  docs/insights-archive-sample/machinesets/d50d0126-c90b-4428-a75f-dc08cd02960a-worker-test
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/yaml/yaml.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/k8s.io/client-go/dynamic/interface.go
  vendor/k8s.io/client-go/dynamic/scheme.go
  vendor/k8s.io/client-go/dynamic/simple.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#193 Bug 1882699: Make gen-doc work outside of GOPATH
  cmd/gendoc/main.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#169 [release-4.3] Bug 1874018: Limit collection of ALERTS metric to 1000 lines (~500KiB) to avoid unbearably large archives
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#178 Bug 1882714: Updates readme
  README.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#182 Bug 1882858: Automate TestArchiveContains::HostsSubnet & 2 more
  test/integration/bugs_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#165 Bug 1882685: Log checker
  test/integration/basic_test.go
  test/integration/bugs_test.go
  test/integration/log_checker.go
  test/integration/main_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#175 Bug 1881907: Adds cluster version into the User-Agent header
  Makefile
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/insights/insightsclient/insightsclient.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#184 Bug 1881044: Limit the maximum number of CSR
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, ok-to-test

#185 Bug 1881905: Adds gatherer for PodDistributionBudget
  docs/gathered-data.md
  docs/insights-archive-sample/config/pdbs/etcd-quorum-guard.json
  docs/insights-archive-sample/config/pdbs/router-default.json
  manifests/03-clusterrole.yaml
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#111 [release-4.3] Bug 1836815: Gather image registry config
  Makefile
  pkg/config/configobserver/configobserver_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
