Repository openshift/insights-operator, pull requests merged in 2020-08, with the labels that each got.

#149 TestCollectingAfterDegradingOperator
  test/integration/bugs_test.go
  test/integration/main_test.go
Labels: approved, lgtm, ok-to-test

#150 Test if files in insights archive have extension set
  test/integration/bugs_test.go
  test/integration/main_test.go
Labels: approved, lgtm, ok-to-test

#148 Bug 1862444: Limit collection of ALERTS metric to 1000 lines (~500KiB) to avoid unbearably large archives
  README.md
  docs/gathered-data.md
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, ok-to-test

#128 Bug 1851492: [release-4.5] clusterconfig.go: limit the size of collected logs
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/record/diskrecorder/diskrecorder.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#152 Tests e2e: Automate 2 BZ tests & generalize TestArchiveContainsFiles
  test/integration/bugs_test.go
  test/integration/main_test.go
Labels: approved, lgtm, ok-to-test

#154 Add @natiiix to OWNERS
  OWNERS
Labels: approved, lgtm, ok-to-test

#155 TestCSRCollected
  Makefile
  test/integration/bugs_test.go
Labels: approved, lgtm

#158 Decrease insights secret interval minimal duration
  pkg/config/configobserver/configobserver.go
  pkg/config/configobserver/configobserver_test.go
Labels: approved, lgtm

#153 [release-4.5] Bug 1866776: Limit collection of ALERTS metric to 1000 lines (~500KiB) to avoid unbearably large archives
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm, ok-to-test

#157 TestUploadNotDelayedAfterStart
  Makefile
  test/integration/basic_test.go
  test/integration/bugs_test.go
  test/integration/main_test.go
Labels: approved, lgtm

#159 Fix TestArchiveContains/File: Check if insights operator records an event
  test/integration/bugs_test.go
Labels: approved, lgtm

#164 [release-4.4] Bug 1870512: Add @natiiix to OWNERS
  OWNERS
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#136 [release-4.4] Bug 1842489: Don't delay first upload
  pkg/controller/operator.go
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
  pkg/insights/insightsuploader/insightsuploader.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#162 [release-4.4] Bug 1869197: Limit collection of ALERTS metric to 1000 lines (~500KiB) to avoid unbearably large archives
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#168 Bug 1872557: handle 201 response from upload
  pkg/insights/insightsclient/insightsclient.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm, ok-to-test
