Repository openshift/insights-operator, pull requests merged in 2020-05, with the labels that each got.

#102 Bug 1813894: Stop using service ca from service account token
  manifests/04-service-ca-configmap.yaml
  manifests/06-deployment.yaml
  pkg/cmd/start/start.go
  pkg/controller/operator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#113 Bug 1837967: Gathering Image Pruner configuration
  docs/gathered-data.md
  manifests/03-clusterrole.yaml
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#96 Bug 1825757: Collecting config maps
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  pkg/gather/clusterconfig/csr.go
  pkg/gather/clusterconfig/testdata/configmaps.json
  pkg/utils/testlog.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#99 Bug 1838969: pkg/record/diskrecorder/diskrecorder: add json extension
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/csr.go
  pkg/record/diskrecorder/diskrecorder.go
  pkg/record/interface.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm
