Repository openshift/insights-operator, pull requests merged in 2020-11, with the labels that each got.

#223 Gather clusteroperator resources
  manifests/03-clusterrole.yaml
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_examples.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, lgtm

#246 Bug 1893766: IO archive contains more records of than is the limit
  pkg/record/diskrecorder/diskrecorder.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#196 Add pattern/patterns to TestArchiveContains
  Makefile
  test/integration/bugs_test.go
  test/integration/resource_samples/apply.sh
  test/integration/resource_samples/csr.yaml
  vendor/modules.txt
Labels: approved, lgtm

#236 Refactor isOperatorDegraded and isOperatorDisabled to operatorConditionCheck
  test/integration/basic_test.go
  test/integration/bugs_test.go
  test/integration/main_test.go
Labels: approved, lgtm, ok-to-test

#249 Update owners list
  OWNERS
Labels: approved, lgtm

#248 [release-4.6] Backport e2e tests
  Makefile
  test/integration/basic_test.go
  test/integration/bugs_test.go
  test/integration/log_checker.go
  test/integration/main_test.go
  test/integration/resource_samples/apply.sh
  test/integration/resource_samples/csr.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#256 [release-4.6] temporarily remove e2e-tests (delayed upload)
  test/integration/basic_test.go
  test/integration/bugs_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#260 Fix TestProxy in clusterauthorizer_test.go
  pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
Labels: approved, lgtm

#259 Add IBM Cloud managed annotations to CVO manifests
  manifests/02-namespace.yaml
  manifests/03-clusterrole.yaml
  manifests/03-prometheus_role.yaml
  manifests/03-prometheus_rolebinding.yaml
  manifests/04-proxy-cert-configmap.yaml
  manifests/04-service-ca-configmap.yaml
  manifests/04-serviceaccount.yaml
Labels: approved, lgtm

#257 Separating the gather logic into separate files
  pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
  pkg/controller/operator.go
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/0_utils.go
  pkg/gather/clusterconfig/1_examples.go
  pkg/gather/clusterconfig/1_examples_test.go
  pkg/gather/clusterconfig/authentications.go
  pkg/gather/clusterconfig/certificate_signing_requests.go
  pkg/gather/clusterconfig/certificate_signing_requests_test.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  pkg/gather/clusterconfig/config_maps.go
  pkg/gather/clusterconfig/config_maps_test.go
  pkg/gather/clusterconfig/container_images.go
  pkg/gather/clusterconfig/container_images_test.go
  pkg/gather/clusterconfig/container_runtime_configs.go
  pkg/gather/clusterconfig/container_runtime_configs_test.go
  pkg/gather/clusterconfig/custom_resource_definitions.go
  pkg/gather/clusterconfig/custom_resource_definitions_test.go
  pkg/gather/clusterconfig/feature_gates.go
  pkg/gather/clusterconfig/host_subnets.go
  pkg/gather/clusterconfig/host_subnets_test.go
  pkg/gather/clusterconfig/image_pruners.go
  pkg/gather/clusterconfig/image_pruners_test.go
  pkg/gather/clusterconfig/image_registries.go
  pkg/gather/clusterconfig/image_registries_test.go
  pkg/gather/clusterconfig/infrastructures.go
  pkg/gather/clusterconfig/ingresses.go
  pkg/gather/clusterconfig/install_plans.go
  pkg/gather/clusterconfig/install_plans_test.go
  pkg/gather/clusterconfig/machine_config_pools.go
  pkg/gather/clusterconfig/machine_config_pools_test.go
  pkg/gather/clusterconfig/machine_sets.go
  pkg/gather/clusterconfig/machine_sets_test.go
  pkg/gather/clusterconfig/networks.go
  pkg/gather/clusterconfig/nodes.go
  pkg/gather/clusterconfig/oauths.go
  pkg/gather/clusterconfig/operators.go
  pkg/gather/clusterconfig/operators_test.go
  pkg/gather/clusterconfig/pod_disruption_budgets.go
  pkg/gather/clusterconfig/pod_disruption_budgets_test.go
  pkg/gather/clusterconfig/proxies.go
  pkg/gather/clusterconfig/recent_metrics.go
  pkg/gather/clusterconfig/service_accounts.go
  pkg/gather/clusterconfig/service_accounts_test.go
  pkg/gather/clusterconfig/stateful_sets.go
  pkg/gather/clusterconfig/stateful_sets_test.go
  pkg/gather/clusterconfig/version.go
  vendor/golang.org/x/net/http2/server.go
Labels: approved, lgtm

#265 Skip TestArchiveUploadedAndResultReceived
  test/integration/basic_test.go
Labels: approved, lgtm

#230 Add IO Architecture doc and metrics sample
  README.md
  docs/arch.md
  docs/metrics.txt
Labels: approved, lgtm

#174 Improve container image collection
  pkg/gather/clusterconfig/container_images.go
  pkg/gather/clusterconfig/container_images_test.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/digest.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/digester.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/doc.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/doc.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/reference.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/regexp.go
  vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
  vendor/modules.txt
Labels: approved, lgtm

#268 fix typos in docs and unused variable
  docs/arch.md
  pkg/record/interface_test.go
Labels: approved, lgtm

#271 Init health status metrics to distinguish no report state vs 0 problems
  pkg/insights/insightsreport/insightsreport.go
Labels: approved, lgtm

#272 Fix clusteroperators serialization
  pkg/gather/clusterconfig/operators.go
Labels: approved, lgtm

#264 Reuse archives & refactor archive checks + some fixes
  test/integration/bugs_test.go
  test/integration/main_test.go
Labels: approved, lgtm
