Repository openshift/insights-operator, pull requests merged in 2020-10, with the labels that each got.

#197 Bug 1884160: Adds info about sample archive in README.md
  README.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#180 Bug 1880352: collect hostsubnet information
  docs/gathered-data.md
  docs/insights-archive-sample/config/hostsubnet/master-0.cluster.lab.upshift.rdu2.redhat.com
  docs/insights-archive-sample/config/hostsubnet/worker-0.cluster.lab.upshift.rdu2.redhat.com
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  vendor/github.com/openshift/api/network/v1/constants.go
  vendor/github.com/openshift/api/network/v1/doc.go
  vendor/github.com/openshift/api/network/v1/generated.pb.go
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/network/v1/legacy.go
  vendor/github.com/openshift/api/network/v1/register.go
  vendor/github.com/openshift/api/network/v1/types.go
  vendor/github.com/openshift/api/network/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/network/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/clusternetwork.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/doc.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/egressnetworkpolicy.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/doc.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/fake_clusternetwork.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/fake_egressnetworkpolicy.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/fake_hostsubnet.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/fake_netnamespace.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/fake_network_client.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/hostsubnet.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/netnamespace.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/network_client.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#194 Bug 1883160: Add new team members to OWNERS
  OWNERS
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#195 Bug 1883175: Gather MachineSet info
  docs/gathered-data.md
  docs/insights-archive-sample/machinesets/d50d0126-c90b-4428-a75f-dc08cd02960a-worker-test
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/yaml/yaml.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/k8s.io/client-go/dynamic/interface.go
  vendor/k8s.io/client-go/dynamic/scheme.go
  vendor/k8s.io/client-go/dynamic/simple.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#200 Gather ServiceAccounts stats from cluster namespaces
  config/local.yaml
  docs/gathered-data.md
  docs/insights-archive-sample/config/serviceaccounts.json
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, lgtm

#142 Report the returned response body to log the error detail from cloud.redhat.com
  pkg/insights/insightsclient/insightsclient.go
Labels: approved, lgtm

#202 [release-4.4] Bug 1885191: Gather MachineSet info
  docs/gathered-data.md
  docs/insights-archive-sample/machinesets/d50d0126-c90b-4428-a75f-dc08cd02960a-worker-test
  manifests/03-clusterrole.yaml
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  vendor/k8s.io/apimachinery/pkg/runtime/serializer/yaml/yaml.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/k8s.io/client-go/dynamic/interface.go
  vendor/k8s.io/client-go/dynamic/scheme.go
  vendor/k8s.io/client-go/dynamic/simple.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#181 [release-4.4] Bug 1880384: - collect hostsubnet information
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  vendor/github.com/openshift/api/network/v1/constants.go
  vendor/github.com/openshift/api/network/v1/doc.go
  vendor/github.com/openshift/api/network/v1/generated.pb.go
  vendor/github.com/openshift/api/network/v1/generated.proto
  vendor/github.com/openshift/api/network/v1/legacy.go
  vendor/github.com/openshift/api/network/v1/register.go
  vendor/github.com/openshift/api/network/v1/types.go
  vendor/github.com/openshift/api/network/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/network/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/clusternetwork.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/doc.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/egressnetworkpolicy.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/doc.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/fake_clusternetwork.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/fake_egressnetworkpolicy.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/fake_hostsubnet.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/fake_netnamespace.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/fake/fake_network_client.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/generated_expansion.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/hostsubnet.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/netnamespace.go
  vendor/github.com/openshift/client-go/network/clientset/versioned/typed/network/v1/network_client.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#209 Bug 1886462: Add the namespace to the gatherers reports to avoid conflicts
  .gitignore
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#199 [release-4.5] Bug 1884551: Adds PodDisruptionBudgets gather.
  docs/gathered-data.md
  manifests/03-clusterrole.yaml
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#210 Bug 1886751: Gather MachineConfigPools
  docs/gathered-data.md
  docs/insights-archive-sample/config/machineconfigpools/master.json
  docs/insights-archive-sample/config/machineconfigpools/worker.json
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#207 Updating ose-insights-operator builder & base images to be consistent with ART
  Dockerfile
Labels: approved, lgtm

#163 Bug 1882361: Get report from smart-proxy and expose overview as a metric
  config/pod.yaml
  pkg/cmd/start/start.go
  pkg/config/config.go
  pkg/config/configobserver/configobserver.go
  pkg/controller/operator.go
  pkg/controllerstatus/controllerstatus.go
  pkg/insights/insightsclient/insightsclient.go
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/insightsreport/types.go
  pkg/insights/insightsuploader/insightsuploader.go
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#211 Take default support instead of rely on existence of config
  pkg/config/config.go
  pkg/controller/operator.go
Labels: approved, lgtm

#212 Fix error in default Smart proxy report endpoint
  pkg/cmd/start/start.go
Labels: approved, lgtm

#216 Bug 1887778: Adds ContainerRuntimeConfig gatherer
  docs/gathered-data.md
  docs/insights-archive-sample/config/containerruntimeconfigs/set-log-and-pid.json
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#201 [release-4.4] Bug 1885177: Adds PodDisruptionBudgets gather.
  docs/gathered-data.md
  manifests/03-clusterrole.yaml
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#192 Bug 1883425: Gather installplans
  config/local.yaml
  docs/gathered-data.md
  docs/insights-archive-sample/config/instalplans.json
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  pkg/gather/clusterconfig/testdata/installplan.yaml
  pkg/gather/clusterconfig/testdata/installplan2.yaml
  pkg/gather/clusterconfig/testdata/installplan_openshift.yaml
  pkg/gather/clusterconfig/testdata/installplan_psql.yaml
  pkg/record/interface.go
  test/integration/bugs_test.go
  test/integration/main_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#123 Bug 1844419: [release-4.4] GatherClusterOperators: store pod logs
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/record/diskrecorder/diskrecorder.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#173 Fix test: Increase allowed delay in TestUploadNotDelayedAfterStart
  test/integration/bugs_test.go
Labels: approved, lgtm

#225 Bug 1888601: Fixes policyClient and the corresponding config.
  manifests/03-clusterrole.yaml
  pkg/controller/operator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#220 Bug 1888172: Updates the sample archive.
  docs/insights-archive-sample/config/machineconfigpools/master.json
  docs/insights-archive-sample/config/machineconfigpools/worker.json
  docs/insights-archive-sample/config/pdbs/etcd-quorum-guard.json
  docs/insights-archive-sample/config/pdbs/openshift-machine-config-operator/etcd-quorum-guard.json
  docs/insights-archive-sample/config/pdbs/router-default.json
  docs/insights-archive-sample/config/serviceaccounts.json
  docs/insights-archive-sample/machinesets/d50d0126-c90b-4428-a75f-dc08cd02960a-worker-test
  docs/insights-archive-sample/machinesets/openshift-machine-api/ci-ln-fyvthbt-f76d1-nl2fh-worker-b.json
  docs/insights-archive-sample/machinesets/openshift-machine-api/ci-ln-fyvthbt-f76d1-nl2fh-worker-c.json
  docs/insights-archive-sample/machinesets/openshift-machine-api/ci-ln-fyvthbt-f76d1-nl2fh-worker-d.json
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#218 Gather StatefulSet configs from default & openshift namespaces
  docs/insights-archive-sample/config/statefulsets/openshift-monitoring/prometheus-k8s.json
  pkg/controller/operator.go
  pkg/controllerstatus/controllerstatus.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  test/integration/basic_test.go
  test/integration/bugs_test.go
  test/integration/log_checker.go
Labels: approved, lgtm

#203 Bug 1885261: Add new team members to OWNERS
  OWNERS
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#204 [release 4.5] Bug 1885515: Fixes 'make build'
  Makefile
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#237 Add more verbosity to the tests
  Makefile
Labels: approved, lgtm

#234 Simplify/generalize host subnet pattern
  test/integration/bugs_test.go
Labels: approved, lgtm

#241 Added TestArchiveUploadedAndResultReceived
  Makefile
  test/integration/basic_test.go
  test/integration/log_checker.go
  test/integration/main_test.go
Labels: approved, lgtm

#235 add current profile annotations to CVO manifests
  manifests/02-namespace.yaml
  manifests/03-clusterrole.yaml
  manifests/03-prometheus_role.yaml
  manifests/03-prometheus_rolebinding.yaml
  manifests/04-proxy-cert-configmap.yaml
  manifests/04-service-ca-configmap.yaml
  manifests/04-serviceaccount.yaml
  manifests/05-service.yaml
  manifests/06-deployment.yaml
  manifests/07-cluster-operator.yaml
  manifests/07-servicemonitor.yaml
Labels: approved, lgtm
