Repository openshift/insights-operator, pull requests merged in 2021-02, with the labels that each got.

#325 Bug 1923888: Fixes error metadata gathering
  pkg/gather/clusterconfig/0_gatherer.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#327 Bug 1922267: collect invalid resource name error from logs
  docs/gathered-data.md
  docs/insights-archive-sample/config/pod/openshift-authentication/logs/oauth-openshift-6c98668d5b-ftt5n/errors.log
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/openshift_authentication_logs.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#323 Bug 1923892: Updates arch.md
  docs/arch.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#214 [release 4.5] Bug 1887763: Adds MachineConfigPool gatherer
  docs/gathered-data.md
  docs/insights-archive-sample/config/machineconfigpools/master.json
  docs/insights-archive-sample/config/machineconfigpools/worker.json
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#262 [release-4.5] Bug 1894243: Fixes records index on diskrecorder
  pkg/record/diskrecorder/diskrecorder.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#308 [release-4.5] Bug 1914255: Red Hat image and crashlooping OpenShift pod collection
  docs/gathered-data.md
  docs/insights-archive-sample/config/running_containers.json
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/digest.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/digester.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/doc.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/doc.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/reference.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/regexp.go
  vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#329 Bug 1925408: Remove StatefulSet gatherer & replace it with gathering "cluster-mon…
  docs/gathered-data.md
  docs/insights-archive-sample/config/configmaps/openshift-config/admin-kubeconfig-client-ca/ca-bundle.crt
  docs/insights-archive-sample/config/configmaps/openshift-config/cloud-provider-config/config
  docs/insights-archive-sample/config/configmaps/openshift-config/etcd-ca-bundle/ca-bundle.crt
  docs/insights-archive-sample/config/configmaps/openshift-config/etcd-metric-serving-ca/ca-bundle.crt
  docs/insights-archive-sample/config/configmaps/openshift-config/etcd-serving-ca/ca-bundle.crt
  docs/insights-archive-sample/config/configmaps/openshift-config/initial-etcd-ca/ca-bundle.crt
  docs/insights-archive-sample/config/configmaps/openshift-config/initial-kube-apiserver-server-ca/ca-bundle.crt
  docs/insights-archive-sample/config/configmaps/openshift-config/openshift-install-manifests/invoker
  docs/insights-archive-sample/config/configmaps/openshift-config/openshift-install-manifests/version
  docs/insights-archive-sample/config/configmaps/openshift-config/openshift-install/invoker
  docs/insights-archive-sample/config/configmaps/openshift-config/openshift-install/version
  docs/insights-archive-sample/config/configmaps/openshift-monitoring/cluster-monitoring-config/config.json
  docs/insights-archive-sample/config/pod/openshift-sdn/logs/sdn-f2694/errors.log
  docs/insights-archive-sample/config/statefulsets/openshift-monitoring/prometheus-k8s.json
  go.mod
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/config_maps.go
  pkg/gather/clusterconfig/stateful_sets.go
  pkg/gather/clusterconfig/stateful_sets_test.go
  test/integration/bugs_test.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#244 [release-4.5] Bug 1889679: Collect installplans
  config/local.yaml
  docs/gathered-data.md
  docs/insights-archive-sample/config/instalplans.json
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  pkg/gather/clusterconfig/testdata/installplan.yaml
  pkg/gather/clusterconfig/testdata/installplan2.yaml
  pkg/gather/clusterconfig/testdata/installplan_openshift.yaml
  pkg/gather/clusterconfig/testdata/installplan_psql.yaml
  pkg/record/interface.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#332 Bug 1926082: Relax the recent log gatherers to avoid degrading during…
  pkg/gather/clusterconfig/0_gatherer.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#334 Do not create the metrics file in case of any error
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/recent_metrics.go
Labels: approved, lgtm

#336 Disable instead of Degrade in case of gather fails
  pkg/controller/status/status.go
Labels: approved, lgtm

#318 Bug 1923895: Auto changelog
  CHANGELOG.md
  README.md
  cmd/changelog/main.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#238 [release 4.6] Bug 1891544: Adds ContainerRuntimeConfig gatherer
  docs/gathered-data.md
  docs/insights-archive-sample/config/containerruntimeconfigs/set-log-and-pid.json
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#305 Some charms to Makefile
  Makefile
Labels: approved, lgtm

#306 Introduce parallelism to unit tests
  pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
  pkg/config/configobserver/configobserver_test.go
  pkg/controller/status/status_test.go
  pkg/gather/clusterconfig/0_gahterer_test.go
  pkg/gather/clusterconfig/certificate_signing_requests_test.go
  pkg/gather/clusterconfig/config_maps_test.go
  pkg/gather/clusterconfig/image_pruners_test.go
  pkg/gather/clusterconfig/image_registries_test.go
  pkg/gather/clusterconfig/install_plans_test.go
  pkg/gather/clusterconfig/service_accounts_test.go
Labels: approved, lgtm

#303 Improve code removing some codesmells
  cmd/gendoc/main.go
  cmd/insights-operator/main.go
  pkg/config/config.go
  pkg/controller/status/status.go
  pkg/gather/clusterconfig/0_utils.go
  pkg/gather/clusterconfig/certificate_signing_requests.go
  pkg/gather/clusterconfig/container_images.go
  pkg/gather/clusterconfig/operators.go
  pkg/gather/clusterconfig/service_accounts.go
  pkg/gather/interface.go
  pkg/insights/insightsclient/insightsclient.go
  pkg/insights/insightsuploader/insightsuploader.go
  pkg/record/diskrecorder/diskrecorder.go
  test/integration/log_checker.go
Labels: approved, lgtm

#341 Fixes changelog script code styling
  cmd/changelog/main.go
Labels: approved, lgtm

#337 Recorder refactoring that improves maintainability
  Makefile
  go.mod
  go.sum
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/0_gatherer_test.go
  pkg/gather/clusterconfig/operators.go
  pkg/gather/interface.go
  pkg/record/diskrecorder/diskrecorder.go
  pkg/record/memory.go
  pkg/record/record.go
  pkg/recorder/diskrecorder/diskrecorder.go
  pkg/recorder/diskrecorder/diskrecorder_test.go
  pkg/recorder/interface.go
  pkg/recorder/recorder.go
  pkg/recorder/recorder_test.go
  tests/integration/basic_test.go
  tests/integration/bugs_test.go
  tests/integration/log_checker.go
  tests/integration/main_test.go
  tests/integration/resource_samples/apply.sh
  tests/integration/resource_samples/csr.yaml
  tests/reports.go
  tests/testing.go
  vendor/github.com/stretchr/objx/.codeclimate.yml
  vendor/github.com/stretchr/objx/.gitignore
  vendor/github.com/stretchr/objx/.travis.yml
  vendor/github.com/stretchr/objx/LICENSE
  vendor/github.com/stretchr/objx/README.md
  vendor/github.com/stretchr/objx/Taskfile.yml
  vendor/github.com/stretchr/objx/accessors.go
  vendor/github.com/stretchr/objx/conversions.go
  vendor/github.com/stretchr/objx/doc.go
  vendor/github.com/stretchr/objx/go.mod
  vendor/github.com/stretchr/objx/go.sum
  vendor/github.com/stretchr/objx/map.go
  vendor/github.com/stretchr/objx/mutations.go
  vendor/github.com/stretchr/objx/security.go
  vendor/github.com/stretchr/objx/tests.go
  vendor/github.com/stretchr/objx/type_specific.go
  vendor/github.com/stretchr/objx/type_specific_codegen.go
  vendor/github.com/stretchr/objx/value.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/mock/doc.go
  vendor/github.com/stretchr/testify/mock/mock.go
  vendor/modules.txt
Labels: approved, lgtm

#239 [release 4.5] Bug 1891545: Adds ContainerRuntimeConfig gatherer
  docs/gathered-data.md
  docs/insights-archive-sample/config/containerruntimeconfigs/set-log-and-pid.json
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#321 [release-4.6] Bug 1921554: Gather OpenShift SDN error messages from logs
  docs/gathered-data.md
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#345 Small clean up and utils reorg
  .gitignore
  Makefile
  pkg/gather/clusterconfig/0_gatherer_test.go
  pkg/gather/clusterconfig/0_utils.go
  pkg/gather/clusterconfig/1_examples.go
  pkg/gather/clusterconfig/1_examples_test.go
  pkg/gather/clusterconfig/authentications.go
  pkg/gather/clusterconfig/certificate_signing_requests.go
  pkg/gather/clusterconfig/const.go
  pkg/gather/clusterconfig/container_images.go
  pkg/gather/clusterconfig/feature_gates.go
  pkg/gather/clusterconfig/gather_logs.go
  pkg/gather/clusterconfig/gather_logs_test.go
  pkg/gather/clusterconfig/host_subnets.go
  pkg/gather/clusterconfig/host_subnets_test.go
  pkg/gather/clusterconfig/image_pruners.go
  pkg/gather/clusterconfig/image_pruners_test.go
  pkg/gather/clusterconfig/image_registries.go
  pkg/gather/clusterconfig/image_registries_test.go
  pkg/gather/clusterconfig/infrastructures.go
  pkg/gather/clusterconfig/ingresses.go
  pkg/gather/clusterconfig/install_plans.go
  pkg/gather/clusterconfig/install_plans_test.go
  pkg/gather/clusterconfig/netnamespaces.go
  pkg/gather/clusterconfig/networks.go
  pkg/gather/clusterconfig/nodes.go
  pkg/gather/clusterconfig/oauths.go
  pkg/gather/clusterconfig/olm_operators.go
  pkg/gather/clusterconfig/olm_operators_test.go
  pkg/gather/clusterconfig/openshift_authentication_logs.go
  pkg/gather/clusterconfig/openshift_sdn_controller_logs.go
  pkg/gather/clusterconfig/operators.go
  pkg/gather/clusterconfig/operators_test.go
  pkg/gather/clusterconfig/pod_disruption_budgets.go
  pkg/gather/clusterconfig/pod_disruption_budgets_test.go
  pkg/gather/clusterconfig/proxies.go
  pkg/gather/clusterconfig/recent_metrics.go
  pkg/gather/clusterconfig/service_accounts.go
  pkg/gather/clusterconfig/version.go
  pkg/utils/anonymize/string.go
  pkg/utils/anonymize/url.go
  pkg/utils/check/has_container_in_crashloop.go
  pkg/utils/check/is_healthy_pod.go
  pkg/utils/const.go
  pkg/utils/count_lines.go
  pkg/utils/get_all_namespaces.go
  pkg/utils/line_limit_reader.go
  pkg/utils/marshal/raw.go
  pkg/utils/marshal/raw_byte.go
  pkg/utils/parse_json_query.go
Labels: approved, lgtm

#349 Sample archive - update metrics file to contain all the metrics we ga…
  docs/insights-archive-sample/config/metrics
Labels: approved, lgtm

#348 Do not run gathering when IO is disabled
  pkg/controller/periodic/periodic.go
Labels: approved, lgtm

#350 Remove code duplication that disable the gather
  pkg/controller/periodic/periodic.go
Labels: approved, lgtm

#342 sap license management logs gatherer
  docs/gathered-data.md
  docs/insights-archive-sample/config/pod/sdi/logs/license-manager-da1d2e8fadfb8dd7022f08-4hjh7-6887768c5b-qzxb6/errors.log
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/const.go
  pkg/gather/clusterconfig/gather_logs.go
  pkg/gather/clusterconfig/gather_logs_test.go
  pkg/gather/clusterconfig/openshift_apiserver_operator_logs.go
  pkg/gather/clusterconfig/openshift_authentication_logs.go
  pkg/gather/clusterconfig/openshift_sdn_controller_logs.go
  pkg/gather/clusterconfig/openshift_sdn_logs.go
  pkg/gather/clusterconfig/sap_config.go
  pkg/gather/clusterconfig/sap_config_test.go
  pkg/gather/clusterconfig/sap_vsystem_iptables_logs.go
Labels: approved, lgtm

#347 Bug 1930393: Gather info about unhealthy SAP pods
  docs/gathered-data.md
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/sap_pods.go
  pkg/gather/clusterconfig/sap_pods_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#351 Reduce Gatherer's code complexity
  pkg/gather/clusterconfig/0_gatherer.go
Labels: approved, lgtm

#331 [release-4.7] Bug 1925659: Relax the recent log gatherers to avoid degrading during…
  pkg/controller/status/status.go
  pkg/gather/clusterconfig/0_gatherer.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#339 [release-4.6] Bug 1928108: Gather PersistentVolume definition (if any…
  docs/gathered-data.md
  docs/insights-archive-sample/config/persistentvolumes/task-pv-volume.json
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#330 [release-4.6] Bug 1885941: Gather ServiceAccounts stats from cluster namespaces
  docs/gathered-data.md
  docs/insights-archive-sample/config/serviceaccounts.json
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#352 Do not use context in the recorder
  pkg/controller/periodic/periodic.go
  pkg/recorder/diskrecorder/diskrecorder.go
  pkg/recorder/diskrecorder/diskrecorder_test.go
  pkg/recorder/interface.go
  pkg/recorder/recorder.go
  pkg/recorder/recorder_test.go
Labels: approved, lgtm

#242 [release-4.5] Bug 1885936: Gather ServiceAccounts
  cmd/gendoc/main.go
  docs/gathered-data.md
  docs/insights-archive-sample/config/serviceaccounts.json
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  vendor/bitbucket.org/ww/goautoneg/Makefile
  vendor/bitbucket.org/ww/goautoneg/README.txt
  vendor/bitbucket.org/ww/goautoneg/autoneg.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
