Repository openshift/insights-operator, pull requests merged in 2021-10, with the labels that each got.

#513 Reverts "Respect user defined proxy's CA cert"
  pkg/insights/insightsclient/insightsclient.go
Labels: approved, lgtm

#515 Bug 2011822: obfuscation ovn clusters bug
  pkg/anonymization/anonymizer.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#498 Bug 2012069: Refactoring Status controller
  pkg/controller/operator.go
  pkg/controller/status/conditions.go
  pkg/controller/status/conditions_test.go
  pkg/controller/status/controller.go
  pkg/controller/status/controller_test.go
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#503 [release-4.9] Bug 2004816: Fix the error logic in the OCM controller & degrade only…
  pkg/insights/insightsclient/insightsclient.go
  pkg/ocm/ocm.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed
