Repository openshift/insights-operator, pull requests merged in 2021-08, with the labels that each got.

#375 Bug 1988351: OCM controller - periodically pull the data and update corresponding
  config/pod.yaml
  manifests/03-clusterrole.yaml
  pkg/authorizer/clusterauthorizer/clusterauthorizer.go
  pkg/cmd/start/start.go
  pkg/config/config.go
  pkg/config/configobserver/configobserver.go
  pkg/controller/operator.go
  pkg/insights/insightsclient/insightsclient.go
  pkg/ocm/ocm.go
  pkg/ocm/ocm_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#473 Bug 1988349: Insightsreport set corresponding clusteroperator condition correctly
  pkg/controller/operator.go
  pkg/controller/status/status.go
  pkg/insights/insightsreport/insightsreport.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#462 [release-4.8] Bug 1974877: Add egress ips to anonymizer to 4.8
  pkg/anonymization/anonymizer.go
  pkg/anonymization/anonymizer_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#459 [release-4.8] Bug 1977754: Gather all MachineConfig definitions (#449)
  docs/gathered-data.md
  docs/insights-archive-sample/config/machineconfigs/00-master.json
  docs/insights-archive-sample/config/machineconfigs/00-worker.json
  docs/insights-archive-sample/config/machineconfigs/01-master-container-runtime.json
  docs/insights-archive-sample/config/machineconfigs/01-master-kubelet.json
  docs/insights-archive-sample/config/machineconfigs/01-worker-container-runtime.json
  docs/insights-archive-sample/config/machineconfigs/01-worker-kubelet.json
  docs/insights-archive-sample/config/machineconfigs/75-worker-sap-data-intelligence.json
  docs/insights-archive-sample/config/machineconfigs/99-master-generated-registries.json
  docs/insights-archive-sample/config/machineconfigs/99-master-ssh.json
  docs/insights-archive-sample/config/machineconfigs/99-sdi-generated-containerruntime.json
  docs/insights-archive-sample/config/machineconfigs/99-worker-generated-registries.json
  docs/insights-archive-sample/config/machineconfigs/99-worker-ssh.json
  docs/insights-archive-sample/config/machineconfigs/rendered-master-e87e5e9a903559fdc31ebab60a8a33a6.json
  docs/insights-archive-sample/config/machineconfigs/rendered-worker-ce8ef65e999c2c7a5b42944c37ca8a54.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/machine_configs.go
  pkg/gatherers/clusterconfig/machine_configs_test.go
  pkg/gatherers/clusterconfig/sap_machine_configs.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#467 [release-4.8] Bug 1977342: Fix obfuscation translation table secret 4.8
  .editorconfig
  manifests/03-clusterrole.yaml
  manifests/image-references
  pkg/anonymization/anonymizer.go
  pkg/anonymization/anonymizer_test.go
  pkg/controller/gather_job.go
  pkg/controller/operator.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium

#485 Bug 1991860: Don't try to record an empty Record if gatherClusterConfigV1 fails
  pkg/gatherers/clusterconfig/cluster_config_v1_config_map.go
  pkg/gatherers/clusterconfig/config_maps.go
  pkg/recorder/recorder.go
  pkg/recorder/recorder_test.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#486 Bug 1995913: Degraded status in the OCM controller
  pkg/controller/operator.go
  pkg/controller/status/status.go
  pkg/controllerstatus/controllerstatus.go
  pkg/insights/insightsclient/insightsclient.go
  pkg/insights/insightsreport/insightsreport.go
  pkg/ocm/ocm.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium
