Repository openshift/insights-operator, pull requests merged in 2021-09, with the labels that each got.

#487 Bug 2000492: Conditional data gathering validation & refactoring
  cmd/insights-operator/main.go
  config/pod.yaml
  docs/gathered-data.md
  go.mod
  go.sum
  pkg/gather/gather.go
  pkg/gather/gather_test.go
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/gatherers/conditional/conditions.go
  pkg/gatherers/conditional/gather_image_stream_definitions_of_namespace.go
  pkg/gatherers/conditional/gather_logs_of_namespace.go
  pkg/gatherers/conditional/gathering_functions.go
  pkg/gatherers/conditional/gathering_rule.schema.json
  pkg/gatherers/conditional/gathering_rules.schema.json
  pkg/gatherers/conditional/types.go
  pkg/gatherers/conditional/validation.go
  pkg/gatherers/conditional/validation_test.go
  pkg/utils/errors.go
  pkg/utils/errors_test.go
  pkg/utils/structs.go
  vendor/github.com/xeipuuv/gojsonpointer/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonpointer/README.md
  vendor/github.com/xeipuuv/gojsonpointer/pointer.go
  vendor/github.com/xeipuuv/gojsonreference/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonreference/README.md
  vendor/github.com/xeipuuv/gojsonreference/reference.go
  vendor/github.com/xeipuuv/gojsonschema/.gitignore
  vendor/github.com/xeipuuv/gojsonschema/.travis.yml
  vendor/github.com/xeipuuv/gojsonschema/LICENSE-APACHE-2.0.txt
  vendor/github.com/xeipuuv/gojsonschema/README.md
  vendor/github.com/xeipuuv/gojsonschema/draft.go
  vendor/github.com/xeipuuv/gojsonschema/errors.go
  vendor/github.com/xeipuuv/gojsonschema/format_checkers.go
  vendor/github.com/xeipuuv/gojsonschema/glide.yaml
  vendor/github.com/xeipuuv/gojsonschema/go.mod
  vendor/github.com/xeipuuv/gojsonschema/go.sum
  vendor/github.com/xeipuuv/gojsonschema/internalLog.go
  vendor/github.com/xeipuuv/gojsonschema/jsonContext.go
  vendor/github.com/xeipuuv/gojsonschema/jsonLoader.go
  vendor/github.com/xeipuuv/gojsonschema/locales.go
  vendor/github.com/xeipuuv/gojsonschema/result.go
  vendor/github.com/xeipuuv/gojsonschema/schema.go
  vendor/github.com/xeipuuv/gojsonschema/schemaLoader.go
  vendor/github.com/xeipuuv/gojsonschema/schemaPool.go
  vendor/github.com/xeipuuv/gojsonschema/schemaReferencePool.go
  vendor/github.com/xeipuuv/gojsonschema/schemaType.go
  vendor/github.com/xeipuuv/gojsonschema/subSchema.go
  vendor/github.com/xeipuuv/gojsonschema/types.go
  vendor/github.com/xeipuuv/gojsonschema/utils.go
  vendor/github.com/xeipuuv/gojsonschema/validation.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#489 Bug 2000820: Gather installed PSP names
  docs/gathered-data.md
  docs/insights-archive-sample/config/psp_names.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/pod_security_policies.go
  pkg/gatherers/clusterconfig/pod_security_policies_test.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#481 Add a script for updating files in the sample archive
  README.md
  scripts/update_sample_archive.sh
Labels: approved, lgtm

#490 [release-4.8] Bug 2001457: Gather installed PSP names (#489)
  docs/gathered-data.md
  docs/insights-archive-sample/config/psp_names.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/pod_security_policies.go
  pkg/gatherers/clusterconfig/pod_security_policies_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium

#492 ApiRequestCount conditional gathering
  docs/gathered-data.md
  docs/insights-archive-sample/conditional/api_request_counts.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/gatherers/conditional/gather_api_request_count.go
  pkg/gatherers/conditional/gather_api_request_count_test.go
  pkg/gatherers/conditional/gathering_functions.go
  pkg/gatherers/conditional/gathering_rule.schema.json
  pkg/gatherers/conditional/types.go
  pkg/utils/unstructerd_wrappers.go
Labels: approved, lgtm

#494 Bug 2001823: Fix the error logic in the OCM controller & degrade only…
  pkg/insights/insightsclient/insightsclient.go
  pkg/ocm/ocm.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#497 insightsclient - close response body
  pkg/insights/insightsclient/insightsclient.go
  pkg/insights/insightsreport/insightsreport.go
Labels: approved, lgtm

#499 Fix the sample archive path for the last conditional gatherer
  docs/insights-archive-sample/conditional/alerts/APIRemovedInNextEUSReleaseInUse/api_request_counts.json
Labels: approved, lgtm

#500 Bug 2004814: OCM controller - change type of the secret
  pkg/ocm/ocm.go
  pkg/ocm/ocm_test.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#501 Update changelog
  CHANGELOG.md
Labels: approved, lgtm

#504 Reduce stacktrace size in logs
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/operators_pods_and_events.go
  pkg/gatherers/clusterconfig/operators_pods_and_events_test.go
  pkg/utils/math.go
Labels: approved, lgtm

#495 Bug 2003657: Respect user defined proxy's CA cert
  pkg/insights/insightsclient/insightsclient.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#505 Gather jaegers.jaegertracing.io CRs
  docs/gathered-data.md
  docs/insights-archive-sample/config/jaegertracing.io/jaeger1.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/jaeger_cr.go
  pkg/gatherers/clusterconfig/jaeger_cr_test.go
Labels: approved, lgtm

#493 [release-4.7] Bug 2002539: Gather installed PSP names (#489)
  docs/gathered-data.md
  docs/insights-archive-sample/config/psp_names.json
  pkg/gather/clusterconfig/pod_security_policies.go
  pkg/gather/clusterconfig/pod_security_policies_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium

#510 Regenerate changelog & update some gatherers OCP versions
  CHANGELOG.md
  cmd/changelog/main.go
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/machine_configs.go
  pkg/gatherers/clusterconfig/pod_security_policies.go
Labels: approved, lgtm

#512 [release-4.7] Bug 2002539: Fix wrong rebase of PSP gatherer
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/pod_security_policies.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium

#507 Bug 2005771: Anonymize the ImageRegistry storage information also in
  pkg/gatherers/clusterconfig/image_registries.go
  pkg/gatherers/clusterconfig/image_registries_test.go
Labels: approved, lgtm

#511 Removing one unnecessary case statement from workload_info
  pkg/gatherers/workloads/workloads_info.go
Labels: approved, lgtm

#508 gather webhook configurations
  docs/gathered-data.md
  docs/insights-archive-sample/config/mutatingwebhookconfigurations/machine-api.json
  docs/insights-archive-sample/config/mutatingwebhookconfigurations/pod-identity-webhook.json
  docs/insights-archive-sample/config/validatingwebhookconfigurations/autoscaling.openshift.io.json
  docs/insights-archive-sample/config/validatingwebhookconfigurations/machine-api.json
  docs/insights-archive-sample/config/validatingwebhookconfigurations/multus.openshift.io.json
  docs/insights-archive-sample/config/validatingwebhookconfigurations/prometheusrules.openshift.io.json
  docs/insights-archive-sample/config/validatingwebhookconfigurations/snapshot.storage.k8s.io.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/mutatingwebhookconfigurations.go
  pkg/gatherers/clusterconfig/validatingwebhookconfigurations.go
  pkg/gatherers/clusterconfig/webhookconfigurations_test.go
Labels: approved, lgtm
