Repository openshift/insights-operator, pull requests merged in 2021-07, with the labels that each got.

#471 cover tasks_processing.go better
  .openshiftci/check-coverage.sh
  Makefile
  pkg/gather/tasks_processing_test.go
Labels: approved, lgtm

#469 Remove ParseJSONQuery function and replace it with unstructured
  pkg/gatherers/clusterconfig/install_plans.go
  pkg/gatherers/clusterconfig/install_plans_test.go
  pkg/gatherers/clusterconfig/olm_operators.go
  pkg/gatherers/clusterconfig/olm_operators_test.go
  pkg/gatherers/clusterconfig/operators.go
  pkg/utils/parse_json_query.go
  pkg/utils/unstructerd_wrappers.go
Labels: approved, lgtm

#468 Update the gather functions to collect data from the system namespaces only
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/container_images.go
  pkg/gatherers/clusterconfig/install_plans.go
  pkg/gatherers/clusterconfig/service_accounts.go
Labels: approved, lgtm

#466 fix obfuscation translation table secret manifest
  .editorconfig
  manifests/03-clusterrole.yaml
  manifests/image-references
Labels: approved, lgtm

#456 Better pod log gathering with offset for stacktrace messages
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/operators_pods_and_events.go
Labels: approved, lgtm

#450 Make obfuscation work with a provided archive
  CONTRIBUTING.md
  README.md
  cmd/obfuscate-archive/main.go
  docs/arch.md
  docs/insights-archive-sample/config/configmaps/kube-system/cluster-config-v1.json
  go.mod
  go.sum
  pkg/anonymization/anonymizer.go
  pkg/anonymization/anonymizer_test.go
  pkg/controller/gather_job.go
  pkg/gatherers/clusterconfig/cluster_config_v1_config_map.go
  pkg/gatherers/clusterconfig/config_maps.go
  pkg/recorder/diskrecorder/diskrecorder.go
  vendor/github.com/openshift/installer/LICENSE
  vendor/github.com/openshift/installer/NOTICE
  vendor/github.com/openshift/installer/pkg/ipnet/ipnet.go
  vendor/github.com/openshift/installer/pkg/types/aws/OWNERS
  vendor/github.com/openshift/installer/pkg/types/aws/doc.go
  vendor/github.com/openshift/installer/pkg/types/aws/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/aws/metadata.go
  vendor/github.com/openshift/installer/pkg/types/aws/platform.go
  vendor/github.com/openshift/installer/pkg/types/azure/OWNERS
  vendor/github.com/openshift/installer/pkg/types/azure/doc.go
  vendor/github.com/openshift/installer/pkg/types/azure/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/azure/metadata.go
  vendor/github.com/openshift/installer/pkg/types/azure/platform.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/OWNERS
  vendor/github.com/openshift/installer/pkg/types/baremetal/doc.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/metadata.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/platform.go
  vendor/github.com/openshift/installer/pkg/types/clustermetadata.go
  vendor/github.com/openshift/installer/pkg/types/doc.go
  vendor/github.com/openshift/installer/pkg/types/gcp/OWNERS
  vendor/github.com/openshift/installer/pkg/types/gcp/clouduid.go
  vendor/github.com/openshift/installer/pkg/types/gcp/doc.go
  vendor/github.com/openshift/installer/pkg/types/gcp/machinepools.go
  vendor/github.com/openshift/installer/pkg/types/gcp/metadata.go
  vendor/github.com/openshift/installer/pkg/types/gcp/platform.go
  vendor/github.com/openshift/installer/pkg/types/installconfig.go
  vendor/github.com/openshift/installer/pkg/types/installconfig_libvirt.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/OWNERS
  vendor/github.com/openshift/installer/pkg/types/libvirt/doc.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/metadata.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/network.go
  vendor/github.com/openshift/installer/pkg/types/libvirt/platform.go
  vendor/github.com/openshift/installer/pkg/types/machinepools.go
  vendor/github.com/openshift/installer/pkg/types/none/doc.go
  vendor/github.com/openshift/installer/pkg/types/none/platform.go
  vendor/github.com/openshift/installer/pkg/types/openstack/OWNERS
  vendor/github.com/openshift/installer/pkg/types/openstack/doc.go
  vendor/github.com/openshift/installer/pkg/types/openstack/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/openstack/metadata.go
  vendor/github.com/openshift/installer/pkg/types/openstack/platform.go
  vendor/github.com/openshift/installer/pkg/types/vsphere/OWNERS
  vendor/github.com/openshift/installer/pkg/types/vsphere/doc.go
  vendor/github.com/openshift/installer/pkg/types/vsphere/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/vsphere/platform.go
  vendor/modules.txt
Labels: approved, lgtm

#472 Bug 1982170: Set also the summary operation when updating status
  pkg/controllerstatus/controllerstatus.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#474 Bye bye Pavel
  OWNERS
Labels: approved, lgtm

#477 Bug 1984047: Do not use klog.Fatal
  pkg/cmd/start/start.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#476 Bug 1986833: Gather Openshift Logging Stack Data
  docs/gathered-data.md
  docs/insights-archive-sample/config/logging/openshift-logging/instance.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/openshift_logging.go
  pkg/gatherers/clusterconfig/openshift_logging_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#479 Bug 1975542: remove the redundant role & rolebinding definition
  manifests/03-clusterrole.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#478 Bug 1987192: Set the disabled state only when the token is removed from the
  pkg/controller/status/status.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#453 [release-4.8] Bug 1967949: MemoryRecord name can be obfuscated & fix case of duplicate records (…
  pkg/recorder/recorder.go
  pkg/recorder/recorder_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
