Repository openshift/insights-operator, pull requests merged in 2021-12, with the labels that each got.

#528 changes for collecting tsdb status
  docs/gathered-data.md
  docs/insights-archive-sample/config/tsdb.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/tsdb_status.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#554 [release-4.8] Bug 2026646: Gather all the container logs from related…
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/operators_pods_and_events.go
  pkg/gatherers/clusterconfig/operators_pods_and_events_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed

#555 [release-4.7] Bug 2026659: Gather all the container logs from related…
  docs/gathered-data.md
  pkg/gather/clusterconfig/operators_pods_and_events.go
  pkg/gather/clusterconfig/operators_pods_and_events_test.go
  pkg/utils/check/is_healthy_pod.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed

#559 [release-4.9] Bug 2027637: gather webhook configurations
  docs/gathered-data.md
  docs/insights-archive-sample/config/mutatingwebhookconfigurations/machine-api.json
  docs/insights-archive-sample/config/mutatingwebhookconfigurations/pod-identity-webhook.json
  docs/insights-archive-sample/config/validatingwebhookconfigurations/autoscaling.openshift.io.json
  docs/insights-archive-sample/config/validatingwebhookconfigurations/machine-api.json
  docs/insights-archive-sample/config/validatingwebhookconfigurations/multus.openshift.io.json
  docs/insights-archive-sample/config/validatingwebhookconfigurations/prometheusrules.openshift.io.json
  docs/insights-archive-sample/config/validatingwebhookconfigurations/snapshot.storage.k8s.io.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/mutatingwebhookconfigurations.go
  pkg/gatherers/clusterconfig/validatingwebhookconfigurations.go
  pkg/gatherers/clusterconfig/webhookconfigurations_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed

#524 Cluster version condition
  docs/insights-archive-sample/insights-operator/conditional-gatherer-rules.json
  go.mod
  go.sum
  pkg/gather/gather.go
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/gatherers/conditional/conditions.go
  pkg/gatherers/conditional/gathering_functions.go
  pkg/gatherers/conditional/gathering_rule.schema.json
  vendor/github.com/blang/semver/v4/LICENSE
  vendor/github.com/blang/semver/v4/go.mod
  vendor/github.com/blang/semver/v4/json.go
  vendor/github.com/blang/semver/v4/range.go
  vendor/github.com/blang/semver/v4/semver.go
  vendor/github.com/blang/semver/v4/sort.go
  vendor/github.com/blang/semver/v4/sql.go
  vendor/modules.txt
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#560 [release-4.8] Bug 2027720: gather webhook configurations
  docs/gathered-data.md
  docs/insights-archive-sample/config/mutatingwebhookconfigurations/machine-api.json
  docs/insights-archive-sample/config/mutatingwebhookconfigurations/pod-identity-webhook.json
  docs/insights-archive-sample/config/validatingwebhookconfigurations/autoscaling.openshift.io.json
  docs/insights-archive-sample/config/validatingwebhookconfigurations/machine-api.json
  docs/insights-archive-sample/config/validatingwebhookconfigurations/multus.openshift.io.json
  docs/insights-archive-sample/config/validatingwebhookconfigurations/prometheusrules.openshift.io.json
  docs/insights-archive-sample/config/validatingwebhookconfigurations/snapshot.storage.k8s.io.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/mutatingwebhookconfigurations.go
  pkg/gatherers/clusterconfig/validatingwebhookconfigurations.go
  pkg/gatherers/clusterconfig/webhookconfigurations_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed

#562 new cluster operator condition providing info about unavailable SCA certs
  config/pod.yaml
  pkg/cmd/start/start.go
  pkg/config/config.go
  pkg/config/configobserver/configobserver.go
  pkg/controller/status/conditions.go
  pkg/controller/status/controller.go
  pkg/controller/status/status.go
  pkg/controllerstatus/controllerstatus.go
  pkg/ocm/ocm.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#551 adding gatherer for collecting silenced alerts
  docs/gathered-data.md
  docs/insights-archive-sample/config/silenced_alerts.json
  manifests/03-clusterrole.yaml
  pkg/controller/const.go
  pkg/controller/gather_job.go
  pkg/controller/operator.go
  pkg/gather/gather.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer_test.go
  pkg/gatherers/clusterconfig/silenced_alerts.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#558 Collect Info about Openshift scheduler
  docs/gathered-data.md
  docs/insights-archive-sample/config/pod/openshift-kube-scheduler/logs/openshift-kube-scheduler-ip-10-0-141-107.us-east-2.compute.internal/messages.log
  docs/insights-archive-sample/config/pod/openshift-kube-scheduler/logs/openshift-kube-scheduler-ip-10-0-177-226.us-east-2.compute.internal/messages.log
  docs/insights-archive-sample/config/pod/openshift-kube-scheduler/logs/openshift-kube-scheduler-ip-10-0-211-255.us-east-2.compute.internal/messages.log
  docs/insights-archive-sample/config/schedulers/cluster.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/openshift_apiserver_operator_logs.go
  pkg/gatherers/clusterconfig/openshift_authentication_logs.go
  pkg/gatherers/clusterconfig/openshift_sdn_controller_logs.go
  pkg/gatherers/clusterconfig/openshift_sdn_logs.go
  pkg/gatherers/clusterconfig/sap_vsystem_iptables_logs.go
  pkg/gatherers/clusterconfig/scheduler.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#543 Update OWNERS
  OWNERS
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed

#556 alert about disconnected cluster
  manifests/08-prometheus_rule.yaml
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#557 feat: limit number of containers per namespace
  pkg/gatherers/common/gather_logs.go
  pkg/gatherers/conditional/gather_logs_of_namespace.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#534 Bug 2005816: make projectid and region anonymization consistent
  docs/insights-archive-sample/config/configmaps/kube-system/cluster-config-v1.json
  docs/insights-archive-sample/machinesets/openshift-machine-api/ci-ln-fyvthbt-f76d1-nl2fh-worker-b.json
  docs/insights-archive-sample/machinesets/openshift-machine-api/ci-ln-fyvthbt-f76d1-nl2fh-worker-c.json
  docs/insights-archive-sample/machinesets/openshift-machine-api/ci-ln-fyvthbt-f76d1-nl2fh-worker-d.json
  pkg/gatherers/clusterconfig/cluster_config_v1_config_map.go
  pkg/gatherers/clusterconfig/cluster_config_v1_config_map_test.go
  pkg/gatherers/clusterconfig/image_registries.go
  pkg/gatherers/clusterconfig/infrastructures.go
  pkg/gatherers/clusterconfig/machine_sets.go
  pkg/gatherers/clusterconfig/nodes.go
  pkg/utils/anonymize/unstructured.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium, qe-approved

#564 refactor: recucing configobserver.go cognitive complexity
  pkg/config/config.go
  pkg/config/configobserver/config.go
  pkg/config/configobserver/config_test.go
  pkg/config/configobserver/configobserver.go
  pkg/config/configobserver/configobserver_test.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#566 Update versions for backports in our gathered data docs
  docs/gathered-data.md
  docs/insights-archive-sample/config/dvo_metrics
  pkg/gatherers/clusterconfig/mutatingwebhookconfigurations.go
  pkg/gatherers/clusterconfig/validatingwebhookconfigurations.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved
