Repository openshift/insights-operator, pull requests merged in 2021-01, with the labels that each got.

#300 [release 4.7] Bug 1913343: Added changelog file
  .github/pull_request_template.md
  CHANGELOG.md
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#273 [release 4.7] Bug 1913356: Implemented gathering specific logs from openshift apiserver operator
  docs/gathered-data.md
  docs/insights-archive-sample/config/pod/openshift-apiserver-operator/logs/openshift-apiserver-operator-6ddb679b87-4kn55/errors.log
  go.mod
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/openshift_apiserver_operator_logs.go
  pkg/gather/clusterconfig/openshift_apiserver_operator_logs_test.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/gopkg.in/yaml.v3/.travis.yml
  vendor/gopkg.in/yaml.v3/LICENSE
  vendor/gopkg.in/yaml.v3/NOTICE
  vendor/gopkg.in/yaml.v3/README.md
  vendor/gopkg.in/yaml.v3/apic.go
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/emitterc.go
  vendor/gopkg.in/yaml.v3/encode.go
  vendor/gopkg.in/yaml.v3/go.mod
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/gopkg.in/yaml.v3/readerc.go
  vendor/gopkg.in/yaml.v3/resolve.go
  vendor/gopkg.in/yaml.v3/scannerc.go
  vendor/gopkg.in/yaml.v3/sorter.go
  vendor/gopkg.in/yaml.v3/writerc.go
  vendor/gopkg.in/yaml.v3/yaml.go
  vendor/gopkg.in/yaml.v3/yamlh.go
  vendor/gopkg.in/yaml.v3/yamlprivateh.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-unspecified, bugzilla/valid-bug, lgtm

#219 [release 4.5] Bug 1887886: Add the namespace to the gatherers reports to avoid conflicts
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#278 [release-4.5] Bug 1904079: Add hostsubnet to sample archive & fix bug…
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-0.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-1.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-2.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-worker-b-56nwr.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-worker-c-wkwh7.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-worker-d-mdwl8.json
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#227 [release 4.5] Bug 1888607: Fixes policyClient and the corresponding config.
  manifests/03-clusterrole.yaml
  pkg/controller/operator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#313 Bug 1917371: Adds docs for using the profiler
  README.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#302 Bug 1917367: Refactor periodic.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/gather/clusterconfig/0_gahterer_test.go
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/authentications.go
  pkg/gather/clusterconfig/certificate_signing_requests.go
  pkg/gather/clusterconfig/config_maps.go
  pkg/gather/clusterconfig/container_images.go
  pkg/gather/clusterconfig/container_runtime_configs.go
  pkg/gather/clusterconfig/custom_resource_definitions.go
  pkg/gather/clusterconfig/feature_gates.go
  pkg/gather/clusterconfig/host_subnets.go
  pkg/gather/clusterconfig/image_pruners.go
  pkg/gather/clusterconfig/image_registries.go
  pkg/gather/clusterconfig/infrastructures.go
  pkg/gather/clusterconfig/ingresses.go
  pkg/gather/clusterconfig/install_plans.go
  pkg/gather/clusterconfig/machine_config_pools.go
  pkg/gather/clusterconfig/machine_sets.go
  pkg/gather/clusterconfig/netnamespaces.go
  pkg/gather/clusterconfig/networks.go
  pkg/gather/clusterconfig/nodes.go
  pkg/gather/clusterconfig/oauths.go
  pkg/gather/clusterconfig/openshift_apiserver_operator_logs.go
  pkg/gather/clusterconfig/openshift_sdn_logs.go
  pkg/gather/clusterconfig/operators.go
  pkg/gather/clusterconfig/pod_disruption_budgets.go
  pkg/gather/clusterconfig/proxies.go
  pkg/gather/clusterconfig/recent_metrics.go
  pkg/gather/clusterconfig/service_accounts.go
  pkg/gather/clusterconfig/stateful_sets.go
  pkg/gather/clusterconfig/version.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#317 Bug 1918129: Update the sample archive and remove IP anonymization in clusteropera…
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/authentication/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/cloudcredential/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/config/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/console/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/csisnapshotcontroller/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/dns/default.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/etcd/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubeapiserver/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubecontrollermanager/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubescheduler/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubestorageversionmigrator/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/network/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/openshiftapiserver/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/openshiftcontrollermanager/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/serviceca/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/storage/cluster.json
  docs/insights-archive-sample/config/clusteroperator/samples.operator.openshift.io/config/cluster.json
  pkg/gather/clusterconfig/operators.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#283 Bug 1904413: Fix hostsubnet gathering and add to sample archive
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-0.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-1.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-master-2.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-worker-b-56nwr.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-worker-c-wkwh7.json
  docs/insights-archive-sample/config/hostsubnet/ci-ln-iffptmb-f76d1-nhwgd-worker-d-mdwl8.json
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#314 Bug 1916843: collect logs from openshift-sdn-controller pod
  docs/gathered-data.md
  docs/insights-archive-sample/config/pod/openshift-sdn/logs/sdn-controller-l8gq9/errors.log
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/gather_logs.go
  pkg/gather/clusterconfig/gather_logs_test.go
  pkg/gather/clusterconfig/openshift_apiserver_operator_logs.go
  pkg/gather/clusterconfig/openshift_sdn_controller_logs.go
  pkg/gather/clusterconfig/openshift_sdn_logs.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#319 Bug 1921013: Gather PersistentVolume definition (if any) used in Image registry st…
  CHANGELOG.md
  docs/gathered-data.md
  pkg/gather/clusterconfig/image_registries.go
  pkg/gather/clusterconfig/image_registries_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#316 Bug 1917799: Gather list of OLM operator names and versions & minor clean up
  CHANGELOG.md
  docs/gathered-data.md
  docs/insights-archive-sample/config/olm_operators.json
  manifests/03-clusterrole.yaml
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/0_utils.go
  pkg/gather/clusterconfig/authentications.go
  pkg/gather/clusterconfig/certificate_signing_requests.go
  pkg/gather/clusterconfig/certificate_signing_requests_test.go
  pkg/gather/clusterconfig/config_maps.go
  pkg/gather/clusterconfig/container_images.go
  pkg/gather/clusterconfig/container_runtime_configs.go
  pkg/gather/clusterconfig/custom_resource_definitions.go
  pkg/gather/clusterconfig/custom_resource_definitions_test.go
  pkg/gather/clusterconfig/feature_gates.go
  pkg/gather/clusterconfig/host_subnets.go
  pkg/gather/clusterconfig/image_pruners.go
  pkg/gather/clusterconfig/image_registries.go
  pkg/gather/clusterconfig/infrastructures.go
  pkg/gather/clusterconfig/ingresses.go
  pkg/gather/clusterconfig/install_plans.go
  pkg/gather/clusterconfig/machine_config_pools.go
  pkg/gather/clusterconfig/machine_sets.go
  pkg/gather/clusterconfig/netnamespaces.go
  pkg/gather/clusterconfig/networks.go
  pkg/gather/clusterconfig/nodes.go
  pkg/gather/clusterconfig/oauths.go
  pkg/gather/clusterconfig/olm_operators.go
  pkg/gather/clusterconfig/olm_operators_test.go
  pkg/gather/clusterconfig/operators.go
  pkg/gather/clusterconfig/pod_disruption_budgets.go
  pkg/gather/clusterconfig/proxies.go
  pkg/gather/clusterconfig/service_accounts.go
  pkg/gather/clusterconfig/stateful_sets.go
  pkg/gather/clusterconfig/testdata/olm_operator_1.yaml
  pkg/gather/clusterconfig/version.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#286 [release 4.6] Bug 1905031: Collect spec config for clusteroperator resources
  docs/gathered-data.md
  docs/insights-archive-sample/config/clusteroperator/imageregistry.operator.openshift.io/config/cluster.json
  docs/insights-archive-sample/config/clusteroperator/imageregistry.operator.openshift.io/imagepruner/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/authentication/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/cloudcredential/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/config/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/console/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/csisnapshotcontroller/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/dns/default.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/etcd/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubeapiserver/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubecontrollermanager/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubescheduler/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubestorageversionmigrator/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/openshiftapiserver/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/openshiftcontrollermanager/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/serviceca/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/storage/cluster.json
  docs/insights-archive-sample/config/clusteroperator/samples.operator.openshift.io/config/cluster.json
  docs/insights-archive-sample/config/imagepruner.json
  docs/insights-archive-sample/config/imageregistry.json
  manifests/03-clusterrole.yaml
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_examples.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  test/integration/bugs_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#213 [release 4.6] Bug 1887759: Adds MachineConfigPool gatherer
  docs/gathered-data.md
  docs/insights-archive-sample/config/machineconfigpools/master.json
  docs/insights-archive-sample/config/machineconfigpools/worker.json
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#243 [release 4.6] Bug 1889676: Gather installplans
  config/local.yaml
  docs/gathered-data.md
  docs/insights-archive-sample/config/instalplans.json
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  pkg/gather/clusterconfig/testdata/installplan.yaml
  pkg/gather/clusterconfig/testdata/installplan2.yaml
  pkg/gather/clusterconfig/testdata/installplan_openshift.yaml
  pkg/gather/clusterconfig/testdata/installplan_psql.yaml
  pkg/record/interface.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#304 [release-4.6] Bug 1913645: Improved Red Hat image and crashlooping OpenShift pod collection
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/digest.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/digester.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/doc.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/doc.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/reference.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/regexp.go
  vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#287 [release-4.5] Bug 1905106: Collect spec config for clusteroperator resources
  docs/gathered-data.md
  docs/insights-archive-sample/config/clusteroperator/imageregistry.operator.openshift.io/config/cluster.json
  docs/insights-archive-sample/config/clusteroperator/imageregistry.operator.openshift.io/imagepruner/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/authentication/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/cloudcredential/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/config/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/console/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/csisnapshotcontroller/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/dns/default.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/etcd/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubeapiserver/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubecontrollermanager/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubescheduler/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubestorageversionmigrator/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/openshiftapiserver/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/openshiftcontrollermanager/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/serviceca/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/storage/cluster.json
  docs/insights-archive-sample/config/clusteroperator/samples.operator.openshift.io/config/cluster.json
  manifests/03-clusterrole.yaml
  pkg/controller/operator.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_examples.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  test/integration/bugs_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm
