Repository openshift/insights-operator, pull requests merged in 2021-04, with the labels that each got.

#381 Bug 1942271: Gather openshift-cluster-version pods and events
  docs/gathered-data.md
  docs/insights-archive-sample/insights-operator/gathers.json
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/operators.go
  pkg/gather/clusterconfig/version.go
  pkg/insights/insightsclient/insightsclient.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#388 Adding CI Liting and improving Makefile
  .editorconfig
  .gitignore
  .golangci.yml
  .openshiftci/install-golangci-lint.sh
  Dockerfile.debug
  Makefile
  README.md
Labels: approved, lgtm

#354 Obfuscate IPv4 addresses and hide cluster base domain
  config/local.yaml
  docs/insights-archive-sample/insights-operator/gathers.json
  pkg/anonymization/anonymizer.go
  pkg/anonymization/anonymizer_test.go
  pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
  pkg/config/config.go
  pkg/config/configobserver/configobserver.go
  pkg/controller/gather_job.go
  pkg/controller/operator.go
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/0_gatherer_test.go
  pkg/gather/clusterconfig/sap_datahubs_test.go
  pkg/recorder/recorder.go
  pkg/recorder/recorder_test.go
  pkg/utils/dns.go
  pkg/utils/slices.go
  pkg/utils/slices_test.go
  pkg/utils/strings.go
  pkg/utils/strings_test.go
Labels: approved, lgtm

#390 Adding githooks, contributing and styleguide
  .githooks/pre-commit
  CONTRIBUTING.md
  Makefile
  README.md
  STYLEGUIDE.md
Labels: approved, lgtm

#392 Disable emptyStringTest check
  .golangci.yml
  STYLEGUIDE.md
Labels: approved, lgtm

#373 [release-4.6] Bug 1939059: sap license management logs gatherer
  docs/gathered-data.md
  docs/insights-archive-sample/config/pod/sdi/logs/license-manager-da1d2e8fadfb8dd7022f08-4hjh7-6887768c5b-qzxb6/errors.log
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/const.go
  pkg/gather/clusterconfig/gather_logs.go
  pkg/gather/clusterconfig/openshift_sdn_controller_logs.go
  pkg/gather/clusterconfig/openshift_sdn_logs.go
  pkg/gather/clusterconfig/sap_config.go
  pkg/gather/clusterconfig/sap_config_test.go
  pkg/gather/clusterconfig/sap_pods.go
  pkg/gather/clusterconfig/sap_pods_test.go
  pkg/gather/clusterconfig/sap_vsystem_iptables_logs.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#382 [release 4.6] Bug 1942457: Adds metadata to the IO archive
  docs/insights-archive-sample/insights-operator/gathers.json
  pkg/record/interface.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#389 Bug 1948966: One-off gather
  docs/gather-job.yaml
  pkg/cmd/start/start.go
  pkg/controller/const.go
  pkg/controller/gather_job.go
  pkg/controller/operator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#384 [release-4.6] Bug 1942907: Gather datahubs.installers.datahub.sap.com resources from SAP clusters
  docs/gathered-data.md
  docs/insights-archive-sample/customresources/installers.datahub.sap.com/datahubs/sdi/default.json
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/sap_datahubs.go
  pkg/gather/clusterconfig/sap_datahubs_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#396 Bug 1948943: Workloads - Add limit for the number of pods gathered
  docs/gathered-data.md
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/sap_datahubs.go
  pkg/gather/clusterconfig/sap_pods.go
  pkg/gather/clusterconfig/sap_vsystem_iptables_logs.go
  pkg/gather/clusterconfig/workloads.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#391 Add management workload annotations
  manifests/02-namespace.yaml
  manifests/06-deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#363 [release-4.6] Bug 1935574: Extend the OLM operator data with related …
  docs/gathered-data.md
  docs/insights-archive-sample/config/olm_operators.json
  manifests/03-clusterrole.yaml
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/image_registries.go
  pkg/gather/clusterconfig/machine_sets.go
  pkg/gather/clusterconfig/olm_operators.go
  pkg/gather/clusterconfig/olm_operators_test.go
  pkg/gather/clusterconfig/testdata/csv_1.yaml
  pkg/gather/clusterconfig/testdata/olm_operator_1.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#401 Bug 1951412: Update configmap gatherer to not fail in case of invalid yaml
  pkg/gather/clusterconfig/config_maps.go
  pkg/gather/clusterconfig/config_maps_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#397 Bug 1951034: Split up the GatherClusterOperators into smaller parts
  Makefile
  docs/gathered-data.md
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/operators.go
  pkg/gather/clusterconfig/operators_pods_and_events.go
  pkg/gather/clusterconfig/operators_pods_and_events_test.go
  pkg/gather/clusterconfig/operators_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#398 Bug 1951456: Docs and lint fixes
  .golangci.precommit.yml
  .golangci.yml
  pkg/anonymization/anonymizer.go
  pkg/authorizer/clusterauthorizer/clusterauthorizer.go
  pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
  pkg/cmd/start/receiver.go
  pkg/cmd/start/start.go
  pkg/config/config.go
  pkg/config/configobserver/configobserver.go
  pkg/config/configobserver/configobserver_test.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
  pkg/controllerstatus/controllerstatus.go
  pkg/record/memory.go
  pkg/record/record.go
  pkg/recorder/diskrecorder/diskrecorder_test.go
  pkg/recorder/recorder.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#404 Bug 1948943: Make the pods limit in the workload gatherer more accurate
  pkg/gather/clusterconfig/workloads.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#374 Bug 1949907: Gather summary of PodNetworkConnectivityChecks
  docs/gathered-data.md
  docs/insights-archive-sample/config/podnetworkconnectivitychecks.json
  manifests/03-clusterrole.yaml
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/const.go
  pkg/gather/clusterconfig/pod_network_connectivity_checks.go
  pkg/gather/clusterconfig/pod_network_connectivity_checks_test.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/0000_10-pod-network-connectivity-check.crd.yaml
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/doc.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/register.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/types_conditioncheck.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operatorcontrolplane/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#408 Bug 1953543: Add missing sample archive data
  docs/gathered-data.md
  docs/insights-archive-sample/config/persistentvolumes/task-pv-volume.json
  pkg/gather/clusterconfig/image_registries.go
  pkg/gather/clusterconfig/operators_pods_and_events.go
  pkg/gather/clusterconfig/sap_config.go
  pkg/gather/clusterconfig/sap_pods.go
  pkg/gather/clusterconfig/sap_vsystem_iptables_logs.go
  pkg/gather/clusterconfig/workloads.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#405 Rename workload annotations
  manifests/06-deployment.yaml
Labels: approved, bugzilla/valid-bug, lgtm

#414 Bug 1955102: Add vsphere_node_hw_version_total metric to the collected metrics
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/gather/clusterconfig/recent_metrics.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#412 Bug 1954931: Remove URL anonymization from ClusterOperator resources
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/authentication/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/kubeapiserver/cluster.json
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/openshiftapiserver/cluster.json
  pkg/gather/clusterconfig/infrastructures.go
  pkg/gather/clusterconfig/operators.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#416 [release 4.7] Bug 1955476: Add vsphere_node_hw_version_total metric
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/gather/clusterconfig/recent_metrics.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm
