Repository openshift/insights-operator, pull requests merged in 2021-03, with the labels that each got.

#353 Update relatedObjects
  pkg/controller/status/status.go
Labels: approved, lgtm

#324 [release-4.6] Bug 1921743: collect logs from openshift-sdn-controller…
  docs/gathered-data.md
  docs/insights-archive-sample/config/pod/openshift-sdn/logs/sdn-controller-l8gq9/errors.log
  pkg/gather/clusterconfig/clusterconfig.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#357 Makes changelog script compatible with squash
  CHANGELOG.md
  cmd/changelog/main.go
Labels: approved, lgtm

#359 Update documentation
  docs/gathered-data.md
Labels: approved, lgtm

#358 Bug 1934397: Extend the OLM operator data with related ClusterServiceVersion conditions
  docs/gathered-data.md
  docs/insights-archive-sample/config/olm_operators.json
  pkg/gather/clusterconfig/olm_operators.go
  pkg/gather/clusterconfig/olm_operators_test.go
  pkg/gather/clusterconfig/testdata/csv_1.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#356 Bug 1934112: Adds memory usage to the metadata
  docs/insights-archive-sample/insights-operator/gathers.json
  pkg/gather/clusterconfig/0_gatherer.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#335 [release-4.6] Bug 1932775: Refactor
  pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
  pkg/controller/operator.go
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/0_utils.go
  pkg/gather/clusterconfig/authentications.go
  pkg/gather/clusterconfig/certificate_signing_requests.go
  pkg/gather/clusterconfig/certificate_signing_requests_test.go
  pkg/gather/clusterconfig/clusterconfig.go
  pkg/gather/clusterconfig/clusterconfig_examples.go
  pkg/gather/clusterconfig/clusterconfig_test.go
  pkg/gather/clusterconfig/config_maps.go
  pkg/gather/clusterconfig/config_maps_test.go
  pkg/gather/clusterconfig/container_images.go
  pkg/gather/clusterconfig/container_images_test.go
  pkg/gather/clusterconfig/container_runtime_configs.go
  pkg/gather/clusterconfig/container_runtime_configs_test.go
  pkg/gather/clusterconfig/custom_resource_definitions.go
  pkg/gather/clusterconfig/custom_resource_definitions_test.go
  pkg/gather/clusterconfig/feature_gates.go
  pkg/gather/clusterconfig/gather_logs.go
  pkg/gather/clusterconfig/host_subnets.go
  pkg/gather/clusterconfig/host_subnets_test.go
  pkg/gather/clusterconfig/image_pruners.go
  pkg/gather/clusterconfig/image_pruners_test.go
  pkg/gather/clusterconfig/image_registries.go
  pkg/gather/clusterconfig/image_registries_test.go
  pkg/gather/clusterconfig/infrastructures.go
  pkg/gather/clusterconfig/ingresses.go
  pkg/gather/clusterconfig/install_plans.go
  pkg/gather/clusterconfig/install_plans_test.go
  pkg/gather/clusterconfig/machine_config_pools.go
  pkg/gather/clusterconfig/machine_config_pools_test.go
  pkg/gather/clusterconfig/machine_sets.go
  pkg/gather/clusterconfig/machine_sets_test.go
  pkg/gather/clusterconfig/netnamespaces.go
  pkg/gather/clusterconfig/netnamespaces_test.go
  pkg/gather/clusterconfig/networks.go
  pkg/gather/clusterconfig/nodes.go
  pkg/gather/clusterconfig/oauths.go
  pkg/gather/clusterconfig/openshift_sdn_controller_logs.go
  pkg/gather/clusterconfig/openshift_sdn_logs.go
  pkg/gather/clusterconfig/operators.go
  pkg/gather/clusterconfig/operators_test.go
  pkg/gather/clusterconfig/pod_disruption_budgets.go
  pkg/gather/clusterconfig/pod_disruption_budgets_test.go
  pkg/gather/clusterconfig/proxies.go
  pkg/gather/clusterconfig/recent_metrics.go
  pkg/gather/clusterconfig/sap_config.go
  pkg/gather/clusterconfig/sap_config_test.go
  pkg/gather/clusterconfig/service_accounts.go
  pkg/gather/clusterconfig/service_accounts_test.go
  pkg/gather/clusterconfig/version.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#365 Do not scan all the pod logs in the "GatherOpenshiftAuthenticationLogs"
  pkg/gather/clusterconfig/openshift_authentication_logs.go
Labels: approved, lgtm

#368 Bug 1936785: Include namespace name in binarydata configmap path & test
  docs/gathered-data.md
  pkg/gather/clusterconfig/config_maps.go
  pkg/gather/clusterconfig/config_maps_test.go
  pkg/gather/clusterconfig/olm_operators_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#366 Bug 1936782: Gather "cluster-monitoring-config" configmap
  docs/gathered-data.md
  docs/insights-archive-sample/config/configmaps/openshift-config/admin-kubeconfig-client-ca/ca-bundle.crt
  docs/insights-archive-sample/config/configmaps/openshift-config/cloud-provider-config/config
  docs/insights-archive-sample/config/configmaps/openshift-config/etcd-ca-bundle/ca-bundle.crt
  docs/insights-archive-sample/config/configmaps/openshift-config/etcd-metric-serving-ca/ca-bundle.crt
  docs/insights-archive-sample/config/configmaps/openshift-config/etcd-serving-ca/ca-bundle.crt
  docs/insights-archive-sample/config/configmaps/openshift-config/initial-etcd-ca/ca-bundle.crt
  docs/insights-archive-sample/config/configmaps/openshift-config/initial-kube-apiserver-server-ca/ca-bundle.crt
  docs/insights-archive-sample/config/configmaps/openshift-config/openshift-install-manifests/invoker
  docs/insights-archive-sample/config/configmaps/openshift-config/openshift-install-manifests/version
  docs/insights-archive-sample/config/configmaps/openshift-config/openshift-install/invoker
  docs/insights-archive-sample/config/configmaps/openshift-config/openshift-install/version
  docs/insights-archive-sample/config/configmaps/openshift-monitoring/cluster-monitoring-config/config.json
  go.mod
  pkg/gather/clusterconfig/config_maps.go
  test/integration/bugs_test.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#371 Introduce quick gather command
  cmd/insights-operator/main.go
  pkg/cmd/start/start.go
  pkg/config/config.go
  pkg/controller/gather_job.go
  pkg/controller/operator.go
Labels: approved, lgtm

#370 [release-4.7] Bug 1936861: Include namespace name in binarydata confi…
  docs/gathered-data.md
  pkg/gather/clusterconfig/config_maps.go
  pkg/gather/clusterconfig/config_maps_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#377 Fixing code style
  .golangci.yml
  Makefile
  pkg/config/configobserver/configobserver_test.go
  pkg/controller/status/status_test.go
  pkg/gather/clusterconfig/0_gatherer_test.go
  pkg/gather/clusterconfig/certificate_signing_requests_test.go
  pkg/gather/clusterconfig/config_maps_test.go
  pkg/gather/clusterconfig/container_images_test.go
  pkg/gather/clusterconfig/container_runtime_configs_test.go
  pkg/gather/clusterconfig/custom_resource_definitions_test.go
  pkg/gather/clusterconfig/gather_logs_test.go
  pkg/gather/clusterconfig/host_subnets_test.go
  pkg/gather/clusterconfig/image_pruners_test.go
  pkg/gather/clusterconfig/image_registries_test.go
  pkg/gather/clusterconfig/install_plans_test.go
  pkg/gather/clusterconfig/machine_config_pools_test.go
  pkg/gather/clusterconfig/machine_sets_test.go
  pkg/gather/clusterconfig/netnamespaces_test.go
  pkg/gather/clusterconfig/olm_operators_test.go
  pkg/gather/clusterconfig/operators_test.go
  pkg/gather/clusterconfig/pod_disruption_budgets.go
  pkg/gather/clusterconfig/pod_disruption_budgets_test.go
  pkg/gather/clusterconfig/sap_config_test.go
  pkg/gather/clusterconfig/sap_pods.go
  pkg/gather/clusterconfig/sap_pods_test.go
  pkg/gather/clusterconfig/service_accounts_test.go
  pkg/recorder/diskrecorder/diskrecorder_test.go
  pkg/recorder/recorder_test.go
Labels: approved, lgtm

#369 [release-4.7] Bug 1936802: Authentication log gatherer - do not scan …
  pkg/gather/clusterconfig/openshift_authentication_logs.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#360 [release-4.7] Bug 1934442: Gather info about unhealthy SAP pods
  docs/gathered-data.md
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/sap_pods.go
  pkg/gather/clusterconfig/sap_pods_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#362 [release-4.7] Bug 1935070: Extend the OLM operator data with related …
  docs/gathered-data.md
  docs/insights-archive-sample/config/olm_operators.json
  pkg/gather/clusterconfig/olm_operators.go
  pkg/gather/clusterconfig/olm_operators_test.go
  pkg/gather/clusterconfig/testdata/csv_1.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#364 [release 4.7] Bug 1935605: Adds memory usage to the metadata
  docs/insights-archive-sample/insights-operator/gathers.json
  pkg/gather/clusterconfig/0_gatherer.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, cherry-pick-approved, lgtm

#378 [release-4.6] Bug 1939640: Do not degrade in case of gathering failure
  pkg/controller/periodic/periodic.go
  pkg/controller/status/status.go
  pkg/controllerstatus/controllerstatus.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, cherry-pick-approved, lgtm

#376 Bug 1940432: Gahter datahubs.installers.datahub.sap.com resources from SAP clusters
  docs/gathered-data.md
  docs/insights-archive-sample/customresources/installers.datahub.sap.com/datahubs/sdi/default.json
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/sap_datahubs.go
  pkg/gather/clusterconfig/sap_datahubs_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#372 [release-4.7] Bug 1939061: Sap license management logs gatherer 4.7
  docs/gathered-data.md
  docs/insights-archive-sample/config/pod/sdi/logs/license-manager-da1d2e8fadfb8dd7022f08-4hjh7-6887768c5b-qzxb6/errors.log
  pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
  pkg/config/config.go
  pkg/controller/periodic/periodic.go
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/const.go
  pkg/gather/clusterconfig/custom_resource_definitions.go
  pkg/gather/clusterconfig/gather_logs.go
  pkg/gather/clusterconfig/gather_logs_test.go
  pkg/gather/clusterconfig/image_pruners.go
  pkg/gather/clusterconfig/ingresses.go
  pkg/gather/clusterconfig/openshift_apiserver_operator_logs.go
  pkg/gather/clusterconfig/openshift_authentication_logs.go
  pkg/gather/clusterconfig/openshift_sdn_controller_logs.go
  pkg/gather/clusterconfig/openshift_sdn_logs.go
  pkg/gather/clusterconfig/sap_config.go
  pkg/gather/clusterconfig/sap_config_test.go
  pkg/gather/clusterconfig/sap_vsystem_iptables_logs.go
  pkg/gather/interface.go
  pkg/insights/insightsclient/insightsclient.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#383 [release-4.7] Bug 1942068: Gahter datahubs.installers.datahub.sap.com resources from SAP clusters
  docs/gathered-data.md
  docs/insights-archive-sample/customresources/installers.datahub.sap.com/datahubs/sdi/default.json
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/sap_datahubs.go
  pkg/gather/clusterconfig/sap_datahubs_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#367 [release-4.6] Bug 1935775: Gather info about unhealthy SAP pods
  docs/gathered-data.md
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/sap_pods.go
  pkg/gather/clusterconfig/sap_pods_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#386 Remove some unnecessary obfuscation
  docs/insights-archive-sample/config/infrastructure.json
  docs/insights-archive-sample/config/ingress.json
  docs/insights-archive-sample/config/node/ci-ln-d53y532-f76d1-2btqq-master-0.json
  docs/insights-archive-sample/config/node/ci-ln-d53y532-f76d1-2btqq-master-1.json
  docs/insights-archive-sample/config/node/ci-ln-d53y532-f76d1-2btqq-master-2.json
  docs/insights-archive-sample/config/node/ci-ln-d53y532-f76d1-2btqq-worker-b-7x8mw.json
  docs/insights-archive-sample/config/node/ci-ln-d53y532-f76d1-2btqq-worker-c-nmnbz.json
  docs/insights-archive-sample/config/node/ci-ln-d53y532-f76d1-2btqq-worker-d-bpnbd.json
  docs/insights-archive-sample/config/node/ci-ln-ywdpkbt-f76d1-vw6lz-master-0.json
  docs/insights-archive-sample/config/node/ci-ln-ywdpkbt-f76d1-vw6lz-master-1.json
  docs/insights-archive-sample/config/node/ci-ln-ywdpkbt-f76d1-vw6lz-master-2.json
  docs/insights-archive-sample/config/node/ci-ln-ywdpkbt-f76d1-vw6lz-worker-b-tdhq6.json
  docs/insights-archive-sample/config/node/ci-ln-ywdpkbt-f76d1-vw6lz-worker-c-k5w6k.json
  docs/insights-archive-sample/config/node/ci-ln-ywdpkbt-f76d1-vw6lz-worker-d-rmh8w.json
  pkg/gather/clusterconfig/infrastructures.go
  pkg/gather/clusterconfig/ingresses.go
  pkg/gather/clusterconfig/nodes.go
Labels: approved, lgtm

#385 Add OCP versions to particular gatherers
  docs/gathered-data.md
  pkg/gather/clusterconfig/authentications.go
  pkg/gather/clusterconfig/certificate_signing_requests.go
  pkg/gather/clusterconfig/config_maps.go
  pkg/gather/clusterconfig/container_images.go
  pkg/gather/clusterconfig/container_runtime_configs.go
  pkg/gather/clusterconfig/custom_resource_definitions.go
  pkg/gather/clusterconfig/feature_gates.go
  pkg/gather/clusterconfig/host_subnets.go
  pkg/gather/clusterconfig/image_pruners.go
  pkg/gather/clusterconfig/image_registries.go
  pkg/gather/clusterconfig/infrastructures.go
  pkg/gather/clusterconfig/ingresses.go
  pkg/gather/clusterconfig/install_plans.go
  pkg/gather/clusterconfig/machine_config_pools.go
  pkg/gather/clusterconfig/machine_sets.go
  pkg/gather/clusterconfig/netnamespaces.go
  pkg/gather/clusterconfig/networks.go
  pkg/gather/clusterconfig/nodes.go
  pkg/gather/clusterconfig/oauths.go
  pkg/gather/clusterconfig/olm_operators.go
  pkg/gather/clusterconfig/openshift_apiserver_operator_logs.go
  pkg/gather/clusterconfig/openshift_authentication_logs.go
  pkg/gather/clusterconfig/openshift_sdn_controller_logs.go
  pkg/gather/clusterconfig/openshift_sdn_logs.go
  pkg/gather/clusterconfig/operators.go
  pkg/gather/clusterconfig/pod_disruption_budgets.go
  pkg/gather/clusterconfig/proxies.go
  pkg/gather/clusterconfig/recent_metrics.go
  pkg/gather/clusterconfig/sap_config.go
  pkg/gather/clusterconfig/sap_datahubs.go
  pkg/gather/clusterconfig/sap_pods.go
  pkg/gather/clusterconfig/sap_vsystem_iptables_logs.go
  pkg/gather/clusterconfig/service_accounts.go
  pkg/gather/clusterconfig/version.go
Labels: approved, lgtm

#355 Bug 1924663: Gather related pod logs when a cluster operator is degraded
  docs/gathered-data.md
  pkg/gather/clusterconfig/operators.go
  pkg/gather/clusterconfig/operators_test.go
  pkg/utils/check/is_healthy_pod.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#344 dockerfile for remote debugging
  Makefile
  debug.Dockerfile
Labels: approved, lgtm

#387 Integration tests moved to internal Python repo
  Makefile
  README.md
  pkg/recorder/diskrecorder/diskrecorder_test.go
  pkg/recorder/recorder_test.go
  tests/integration/basic_test.go
  tests/integration/bugs_test.go
  tests/integration/log_checker.go
  tests/integration/main_test.go
  tests/integration/resource_samples/apply.sh
  tests/integration/resource_samples/csr.yaml
  tests/reports.go
  tests/testing.go
Labels: approved, lgtm
