Repository openshift/insights-operator, pull requests merged in 2021-06, with the labels that each got.

#425 Bug 1966416: Do not exceed archive size limit
  docs/gathered-data.md
  pkg/controller/gather_job.go
  pkg/controller/periodic/periodic.go
  pkg/controller/periodic/periodic_test.go
  pkg/gather/gather.go
  pkg/gather/gather_test.go
  pkg/gather/mock_gatherers.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/machine_healthcheck.go
  pkg/gatherers/clusterconfig/operators_pods_and_events.go
  pkg/recorder/recorder.go
  pkg/recorder/recorder_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#442 Bug 1966717: include full timestamps in the logs
  pkg/gatherers/clusterconfig/gather_logs.go
  pkg/gatherers/clusterconfig/operators_pods_and_events.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#440 Bug 1967403: Workloads gatherer - increase the pods limit
  pkg/gatherers/workloads/workloads_info.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#435 [release 4.6] Bug 1965219: Adds virt_platform metric to the collected metrics
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/gather/clusterconfig/recent_metrics.go
  test/integration/bugs_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm

#443 Bug 1967595: Fixes the remaining lint issues
  .golangci.precommit.yml
  .golangci.yml
  cmd/changelog/main.go
  cmd/gendoc/main.go
  cmd/insights-operator/main.go
  pkg/config/mock_configurator.go
  pkg/controller/periodic/periodic.go
  pkg/controller/periodic/periodic_test.go
  pkg/gather/gather.go
  pkg/gather/gather_test.go
  pkg/gather/tasks_processing_test.go
  pkg/gatherers/clusterconfig/certificate_signing_requests.go
  pkg/gatherers/clusterconfig/image_registries.go
  pkg/gatherers/clusterconfig/infrastructures.go
  pkg/gatherers/clusterconfig/machine_healthcheck.go
  pkg/gatherers/clusterconfig/nodes.go
  pkg/gatherers/clusterconfig/openshift_apiserver_operator_logs.go
  pkg/gatherers/clusterconfig/operators_pods_and_events.go
  pkg/gatherers/clusterconfig/pod_network_connectivity_checks.go
  pkg/gatherers/clusterconfig/pod_network_connectivity_checks_test.go
  pkg/gatherers/clusterconfig/proxies.go
  pkg/gatherers/clusterconfig/sap_machine_configs_test.go
  pkg/gatherers/clusterconfig/version.go
  pkg/gatherers/workloads/workloads_info_test.go
  pkg/recorder/recorder.go
  pkg/recorder/recorder_test.go
  pkg/utils/anonymize/string.go
  pkg/utils/anonymize/url.go
  pkg/utils/check/has_container_in_crashloop.go
  pkg/utils/check/is_healthy_pod.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#445 Bug 1967843: Fixes one small bug
  pkg/gatherers/clusterconfig/gather_logs.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#419 Bug 1958790: Store translation table in a secret
  manifests/03-clusterrole.yaml
  pkg/anonymization/anonymizer.go
  pkg/anonymization/anonymizer_test.go
  pkg/gather/gather_test.go
  pkg/recorder/recorder.go
  pkg/recorder/recorder_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#448 Bug 1969525: Replace golint with revive
  .golangci.yml
  .openshiftci/install-golangci-lint.sh
  cmd/changelog/main.go
  pkg/anonymization/anonymizer.go
  pkg/authorizer/clusterauthorizer/clusterauthorizer.go
  pkg/cmd/start/start.go
  pkg/config/config.go
  pkg/config/configobserver/configobserver.go
  pkg/config/mock_configurator.go
  pkg/controller/gather_job.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/controller/status/status.go
  pkg/controllerstatus/controllerstatus.go
  pkg/gather/gather.go
  pkg/gatherers/clusterconfig/container_images_test.go
  pkg/gatherers/interface.go
  pkg/record/memory.go
  pkg/record/record.go
  pkg/recorder/recorder.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#436 Bug 1967832: Adds more tests for periodic.go
  pkg/config/mock_configurator.go
  pkg/controller/periodic/periodic_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#441 Bug 1961701: Use configured interval as the event time limit & check series if
  pkg/controller/gather_job.go
  pkg/controller/operator.go
  pkg/gather/gather.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer_test.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/operators_pods_and_events.go
  pkg/gatherers/clusterconfig/operators_pods_and_events_test.go
  pkg/gatherers/clusterconfig/version.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#439 Bug 1967833: Adds tasks pool to tasks_processing
  pkg/gather/tasks_processing.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#438 Bug 1966523: Gather MachineAutoscalers definitions
  docs/gathered-data.md
  docs/insights-archive-sample/config/machineautoscalers/openshift-machine-api/worker-us-east-1a.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/machine_autoscaler.go
  pkg/gatherers/clusterconfig/machine_autoscaler_test.go
  pkg/gatherers/clusterconfig/machine_healthcheck.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#413 [release 4.6] Bug 1953582: GatherClusterOperators and GatherClusterOperatorsPodAndEvents
  docs/gathered-data.md
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/0_utils.go
  pkg/gather/clusterconfig/operators.go
  pkg/gather/clusterconfig/operators_pods_and_events.go
  pkg/gather/clusterconfig/operators_pods_and_events_test.go
  pkg/gather/clusterconfig/operators_test.go
  pkg/utils/check/is_healthy_pod.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#446 add egress ips support to anonymizer
  pkg/anonymization/anonymizer.go
  pkg/anonymization/anonymizer_test.go
Labels: approved, lgtm

#452 Update versions in the metrics gather documentation
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/recent_metrics.go
Labels: approved, lgtm

#444 MemoryRecord name can be obfuscated & fix case of duplicate records
  pkg/recorder/recorder.go
  pkg/recorder/recorder_test.go
Labels: approved, lgtm

#454 Update changelog
  CHANGELOG.md
Labels: approved, lgtm

#449 Gather all MachineConfig definitions
  docs/gathered-data.md
  docs/insights-archive-sample/config/machineconfigs/00-master.json
  docs/insights-archive-sample/config/machineconfigs/00-worker.json
  docs/insights-archive-sample/config/machineconfigs/01-master-container-runtime.json
  docs/insights-archive-sample/config/machineconfigs/01-master-kubelet.json
  docs/insights-archive-sample/config/machineconfigs/01-worker-container-runtime.json
  docs/insights-archive-sample/config/machineconfigs/01-worker-kubelet.json
  docs/insights-archive-sample/config/machineconfigs/75-worker-sap-data-intelligence.json
  docs/insights-archive-sample/config/machineconfigs/99-master-generated-registries.json
  docs/insights-archive-sample/config/machineconfigs/99-master-ssh.json
  docs/insights-archive-sample/config/machineconfigs/99-sdi-generated-containerruntime.json
  docs/insights-archive-sample/config/machineconfigs/99-worker-generated-registries.json
  docs/insights-archive-sample/config/machineconfigs/99-worker-ssh.json
  docs/insights-archive-sample/config/machineconfigs/rendered-master-e87e5e9a903559fdc31ebab60a8a33a6.json
  docs/insights-archive-sample/config/machineconfigs/rendered-worker-ce8ef65e999c2c7a5b42944c37ca8a54.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/machine_configs.go
  pkg/gatherers/clusterconfig/machine_configs_test.go
  pkg/gatherers/clusterconfig/sap_machine_configs.go
Labels: approved, lgtm

#447 fix logs format in sample archive
  docs/insights-archive-sample/config/pod/openshift-apiserver-operator/logs/openshift-apiserver-operator-6ddb679b87-4kn55/errors.log
  docs/insights-archive-sample/config/pod/openshift-authentication/logs/oauth-openshift-6c98668d5b-ftt5n/errors.log
  docs/insights-archive-sample/config/pod/openshift-sdn/logs/sdn-controller-l8gq9/errors.log
  docs/insights-archive-sample/config/pod/openshift-sdn/logs/sdn-f2694/errors.log
Labels: approved, lgtm

#463 Enables godox on precommit
  .golangci.precommit.yml
Labels: approved, lgtm

#461 fix obfuscation translation table secret
  manifests/03-clusterrole.yaml
  pkg/anonymization/anonymizer.go
  pkg/anonymization/anonymizer_test.go
  pkg/controller/gather_job.go
  pkg/controller/operator.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
Labels: approved, lgtm

#433 Conditional gathering
  cmd/gendoc/main.go
  docs/gathered-data.md
  docs/insights-archive-sample/conditional/namespaces/openshift-cluster-samples-operator/imagestreams/example.json
  docs/insights-archive-sample/conditional/namespaces/openshift-cluster-samples-operator/pods/cluster-samples-operator-8ffb9b45f-49mjr/containers/cluster-samples-operator-watch/logs/last-100-lines.log
  docs/insights-archive-sample/conditional/namespaces/openshift-cluster-samples-operator/pods/cluster-samples-operator-8ffb9b45f-49mjr/containers/cluster-samples-operator/logs/last-100-lines.log
  docs/insights-archive-sample/insights-operator/conditional-gatherer-rules.json
  docs/insights-archive-sample/insights-operator/gathers.json
  pkg/gather/gather.go
  pkg/gather/mock_gatherers.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer_test.go
  pkg/gatherers/clusterconfig/openshift_apiserver_operator_logs.go
  pkg/gatherers/clusterconfig/openshift_authentication_logs.go
  pkg/gatherers/clusterconfig/openshift_sdn_controller_logs.go
  pkg/gatherers/clusterconfig/openshift_sdn_logs.go
  pkg/gatherers/clusterconfig/sap_vsystem_iptables_logs.go
  pkg/gatherers/common/constants.go
  pkg/gatherers/common/gather_logs.go
  pkg/gatherers/common/gather_logs_test.go
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/gatherers/conditional/gather_image_stream_definitions_of_namespace.go
  pkg/gatherers/conditional/gather_logs_of_namespace.go
  pkg/gatherers/conditional/types.go
  pkg/gatherers/interface.go
  pkg/gatherers/workloads/workloads_gatherer.go
  pkg/gatherers/workloads/workloads_gatherer_test.go
  pkg/gatherers/workloads/workloads_info.go
  pkg/utils/gatherers.go
Labels: approved, lgtm

#455 Updating the owners list
  OWNERS
Labels: approved, lgtm

#458 Gathered data doc update - add some known previous locations
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/config_maps.go
  pkg/gatherers/clusterconfig/image_pruners.go
  pkg/gatherers/clusterconfig/image_registries.go
  pkg/gatherers/clusterconfig/operators.go
Labels: approved, lgtm

#464 Bugzilla 1975542: Add delete annotation to stale resources
  manifests/03-clusterrole.yaml
Labels: approved, lgtm

#465 Fix installplans sample archive filename
  docs/insights-archive-sample/config/installplans.json
Labels: approved, lgtm
