Repository openshift/insights-operator, pull requests merged in 2021-11, with the labels that each got.

#525 Gather all CostManagementMericsConfig definitions.
  docs/gathered-data.md
  docs/insights-archive-sample/config/cost_management_metrics_configs/00-basic.json
  docs/insights-archive-sample/config/cost_management_metrics_configs/00-token.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/cost_management_metrics_configs.go
  pkg/gatherers/clusterconfig/cost_management_metrics_configs_test.go
Labels: approved, ok-to-test, lgtm, px-approved, docs-approved, qe-approved

#509 Conditional gatherer of logs of unhealthy pods
  docs/gathered-data.md
  docs/insights-archive-sample/insights-operator/conditional-gatherer-rules.json
  pkg/gatherers/common/gather_logs.go
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/gatherers/conditional/gather_logs_of_unhealthy_pods.go
  pkg/gatherers/conditional/gather_logs_of_unhealthy_pods_test.go
  pkg/gatherers/conditional/gathering_functions.go
  pkg/gatherers/conditional/gathering_rule.schema.json
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#506 [release-4.9] Bug 2005338: OCM controller - change type of the secret (#500)
  pkg/ocm/ocm.go
  pkg/ocm/ocm_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed

#532 Bug 2020250: Replacing deprecated ioutil
  cmd/changelog/main.go
  cmd/gendoc/main.go
  cmd/obfuscate-archive/main.go
  pkg/cmd/start/start.go
  pkg/gatherers/clusterconfig/certificate_signing_requests_test.go
  pkg/gatherers/clusterconfig/config_maps_test.go
  pkg/gatherers/clusterconfig/install_plans_test.go
  pkg/gatherers/clusterconfig/olm_operators_test.go
  pkg/gatherers/clusterconfig/recent_metrics.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/gatherers/workloads/workloads_info_test.go
  pkg/insights/insightsclient/insightsclient.go
  pkg/recorder/diskrecorder/diskrecorder.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#526 [release-4.9] Bug 2017759: Anonymize the ImageRegistry storage inform…
  pkg/gatherers/clusterconfig/image_registries.go
  pkg/gatherers/clusterconfig/image_registries_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-high, backport-risk-assessed

#531 Enhance gathered-data.md
  cmd/gendoc/main.go
  docs/gathered-data.md
Labels: approved, ok-to-test, lgtm, px-approved, docs-approved, qe-approved

#537 Fix cost management metric resource name
  manifests/03-clusterrole.yaml
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#517 Collecting node logs
  .golangci.precommit.yml
  .golangci.yml
  docs/gathered-data.md
  docs/insights-archive-sample/config/node/logs/ip-10-0-135-228.us-east-2.compute.internal.log
  pkg/controller/status/conditions_test.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/node_logs.go
  pkg/gatherers/clusterconfig/node_logs_test.go
  pkg/gatherers/common/gather_logs.go
  pkg/gatherers/common/gather_logs_test.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#527 [release-4.9] Bug 2017773: Anonymize identity provider attributes in …
  pkg/gatherers/clusterconfig/operators.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed

#538 Bug 2022251: Shorter delay in case of HTTP 403 during upload
  pkg/insights/insightsuploader/insightsuploader.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#536 [release-4.8] Bug 2020601: Anonymize the ImageRegistry storage information also in status
  cmd/changelog/main.go
  cmd/gendoc/main.go
  pkg/cmd/start/start.go
  pkg/gatherers/clusterconfig/certificate_signing_requests_test.go
  pkg/gatherers/clusterconfig/config_maps_test.go
  pkg/gatherers/clusterconfig/image_registries.go
  pkg/gatherers/clusterconfig/image_registries_test.go
  pkg/gatherers/clusterconfig/install_plans_test.go
  pkg/gatherers/clusterconfig/olm_operators_test.go
  pkg/gatherers/clusterconfig/recent_metrics.go
  pkg/gatherers/workloads/workloads_info_test.go
  pkg/insights/insightsclient/insightsclient.go
  pkg/recorder/diskrecorder/diskrecorder.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-high, backport-risk-assessed

#519 unified conditional gatherer api with targeted update edge blocking api
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/gatherers/conditional/conditions.go
  pkg/gatherers/conditional/gathering_rule.schema.json
  pkg/gatherers/conditional/validation_test.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#542 Update docs/arch.md documentation to mention the new gatherers
  docs/arch.md
  pkg/controller/periodic/periodic.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#547 Update documentation for PSP gatherer
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/pod_security_policies.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#546 [release-4.7] Bug 2022637: Anonymize the ImageRegistry storage inform…
  pkg/gather/clusterconfig/image_registries.go
  pkg/gather/clusterconfig/image_registries_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-high, backport-risk-assessed

#541 [release-4.8] Bug 2021572: Anonymize identity provider attributes in …
  pkg/gatherers/clusterconfig/operators.go
  pkg/utils/unstructured_wrappers.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed

#549 [release-4.7] Bug 2024614: Anonymize identity provider attributes in …
  pkg/gather/clusterconfig/operators.go
  pkg/utils/anonymize/string.go
  pkg/utils/unstructured_wrappers.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed

#550 workloads info - increase the pods limit a bit
  pkg/gatherers/workloads/workloads_info.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#552 [release-4.7] Bug 2026410: Fix PDB gatherer
  pkg/gather/clusterconfig/pod_disruption_budgets.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed

#544 Bug 2026699: fixed a bug with missing metadata
  pkg/controller/gather_job.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#553 [release-4.9] Bug 2026644: Gather all the container logs from relate namespaces of degraded clusteroperator
  cmd/changelog/main.go
  cmd/gendoc/main.go
  cmd/obfuscate-archive/main.go
  docs/gathered-data.md
  pkg/cmd/start/start.go
  pkg/gatherers/clusterconfig/certificate_signing_requests_test.go
  pkg/gatherers/clusterconfig/config_maps_test.go
  pkg/gatherers/clusterconfig/install_plans_test.go
  pkg/gatherers/clusterconfig/olm_operators_test.go
  pkg/gatherers/clusterconfig/operators_pods_and_events.go
  pkg/gatherers/clusterconfig/operators_pods_and_events_test.go
  pkg/gatherers/clusterconfig/recent_metrics.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/gatherers/workloads/workloads_info_test.go
  pkg/insights/insightsclient/insightsclient.go
  pkg/recorder/diskrecorder/diskrecorder.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed

#529 Gather DVO metrics
  docs/gathered-data.md
  docs/insights-archive-sample/config/dvo_metrics
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/dvo_metrics.go
  pkg/gatherers/clusterconfig/recent_metrics.go
  pkg/utils/const.go
  pkg/utils/count_lines.go
  pkg/utils/line_limit_reader.go
  pkg/utils/read_lines_with_prefix.go
  pkg/utils/read_lines_with_prefix_test.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved
