Repository openshift/insights-operator, pull requests merged in 2021-05, with the labels that each got.

#420 Bug 1957889: Improves documentation of GatherClusterOperatorPodsAndEvents
  pkg/gather/clusterconfig/operators_pods_and_events.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#410 [release 4.7] Bug 1953579: GatherClusterOperators and GatherClusterOperatorsPodAndEvents
  docs/gathered-data.md
  pkg/gather/clusterconfig/0_gatherer.go
  pkg/gather/clusterconfig/0_utils.go
  pkg/gather/clusterconfig/1_examples.go
  pkg/gather/clusterconfig/1_examples_test.go
  pkg/gather/clusterconfig/operators.go
  pkg/gather/clusterconfig/operators_pods_and_events.go
  pkg/gather/clusterconfig/operators_pods_and_events_test.go
  pkg/gather/clusterconfig/operators_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, cherry-pick-approved, lgtm

#409 Bug 1952906: Add a few tests to configobserver_test.go
  pkg/config/configobserver/configobserver_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#418 Bug 1958759: #417 insights report - add basic retry logic in case of 404
  go.sum
  pkg/gather/clusterconfig/pod_disruption_budgets.go
  pkg/gather/clusterconfig/pod_disruption_budgets_test.go
  pkg/insights/insightsclient/insightsclient.go
  pkg/insights/insightsreport/insightsreport.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#424 Bug 1960255: fixed obfuscation permissions
  Dockerfile.debug
  Makefile
  pkg/anonymization/anonymizer.go
  pkg/controller/gather_job.go
  pkg/controller/operator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#427 Bug 1960546: Adds virt_platform metric to the collected metrics
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/gatherers/clusterconfig/recent_metrics.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#415 Bug 1958114: Fix pre-commit script for staged vendor files
  .githooks/pre-commit
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#426 Bug 1960257: breaking changes in pr template
  .github/pull_request_template.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#429 Bug 1961091: Adding GatherMachineHealthCheck
  docs/gathered-data.md
  docs/insights-archive-sample/config/machinehealthchecks/openshift-machine-api/machine-api-termination-handler.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/machine_healthcheck.go
  pkg/gatherers/clusterconfig/machine_healthcheck_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#422 Bug 1959650: Gather SDI-related MachineConfigs
  docs/gathered-data.md
  docs/insights-archive-sample/config/machineconfigs/75-worker-sap-data-intelligence.json
  docs/insights-archive-sample/config/machineconfigs/99-sdi-generated-containerruntime.json
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/sap_machine_configs.go
  pkg/gatherers/clusterconfig/sap_machine_configs_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#430 Bug 1961545: Fixes gendoc
  cmd/gendoc/main.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#421 Bug 1961067: Collect full pod log for stack traces
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/operators_pods_and_events.go
  pkg/gatherers/clusterconfig/operators_pods_and_events_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#431 Bug 1961701: Change event gathering interval
  pkg/gatherers/clusterconfig/operators_pods_and_events.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#432 Bug 1962095: Replace gather-job image without FQDN
  docs/gather-job.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#428 [release 4.7] Bug 1960645: Adds virt_platform metric to the collected metrics
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/gather/clusterconfig/recent_metrics.go
  test/integration/bugs_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, cherry-pick-approved, lgtm
