Repository openshift/insights-operator, pull requests merged in 2022-09, with the labels that each got.

#672 OCPBUGS-959: manifests/02-namespace: Explicitly clear run-level label
  manifests/02-namespace.yaml
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/severity-moderate

#669 Implement insights report updating in the insightsoperators.operator.openshift.io resource
  config/pod.yaml
  pkg/controller/operator.go
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/insightsreport/insightsreport_test.go
  pkg/insights/types/types.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#674 OCPBUGS-1068: fix alert namespace label
  manifests/10-prometheus_rule.yaml
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug

#677 [release-4.11] OCPBUGS-1355: update the DVO metrics gatherer (#664)
  pkg/cmd/start/receiver.go
  pkg/gatherers/clusterconfig/dvo_metrics.go
  pkg/recorder/diskrecorder/diskrecorder.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#670 updated conditional gathering rules checking
  docs/conditional-gatherer/README.md
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/validation.go
  pkg/gatherers/conditional/validation_test.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#678 OCPBUGS-1351: do not include disabled rules in the total metric
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/insightsreport/insightsreport_test.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug

#679 OCPBUGS-1502: Update PNCC gatherer
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/pod_network_connectivity_checks.go
  pkg/gatherers/clusterconfig/pod_network_connectivity_checks_test.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/applyconfigurations/internal/internal.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/applyconfigurations/operatorcontrolplane/v1alpha1/logentry.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/applyconfigurations/operatorcontrolplane/v1alpha1/outageentry.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/applyconfigurations/operatorcontrolplane/v1alpha1/podnetworkconnectivitycheck.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/applyconfigurations/operatorcontrolplane/v1alpha1/podnetworkconnectivitycheckcondition.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/applyconfigurations/operatorcontrolplane/v1alpha1/podnetworkconnectivitycheckspec.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/applyconfigurations/operatorcontrolplane/v1alpha1/podnetworkconnectivitycheckstatus.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/clientset.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/doc.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/fake/clientset_generated.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/fake/doc.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/fake/register.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/scheme/doc.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/scheme/register.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/typed/operatorcontrolplane/v1alpha1/doc.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/typed/operatorcontrolplane/v1alpha1/fake/doc.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/typed/operatorcontrolplane/v1alpha1/fake/fake_operatorcontrolplane_client.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/typed/operatorcontrolplane/v1alpha1/fake/fake_podnetworkconnectivitycheck.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/typed/operatorcontrolplane/v1alpha1/generated_expansion.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/typed/operatorcontrolplane/v1alpha1/operatorcontrolplane_client.go
  vendor/github.com/openshift/client-go/operatorcontrolplane/clientset/versioned/typed/operatorcontrolplane/v1alpha1/podnetworkconnectivitycheck.go
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/severity-moderate
