Repository openshift/insights-operator, pull requests merged in 2022-08, with the labels that each got.

#654 Gather status of the cephclusters.ceph.rook.io resources
  docs/gathered-data.md
  docs/insights-archive-sample/config/storage/openshift-storage/ocs-storagecluster-cephcluster.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/ceph_cluster.go
  pkg/gatherers/clusterconfig/ceph_cluster_test.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#655 [release-4.11] Bug 2115685: Gather status of the cephclusters.ceph.rook.io resourc…
  docs/gathered-data.md
  docs/insights-archive-sample/config/storage/openshift-storage/ocs-storagecluster-cephcluster.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/ceph_cluster.go
  pkg/gatherers/clusterconfig/ceph_cluster_test.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed

#660 Remove Bugzilla references
  .github/pull_request_template.md
  README.md
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#657 helm upgrade and uninstall metric gathering
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/gatherers/clusterconfig/recent_metrics.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#659 [release-4.10] OCPBUGS-251: Gather status of the cephclusters.ceph.roo…
  docs/gathered-data.md
  docs/insights-archive-sample/config/storage/openshift-storage/ocs-storagecluster-cephcluster.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/ceph_cluster.go
  pkg/gatherers/clusterconfig/ceph_cluster_test.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#646 chore(manifests): adding insights capability annotations
  manifests/02-namespace.yaml
  manifests/03-clusterrole.yaml
  manifests/03-prometheus_role.yaml
  manifests/03-prometheus_rolebinding.yaml
  manifests/04-proxy-cert-configmap.yaml
  manifests/04-service-ca-configmap.yaml
  manifests/04-serviceaccount.yaml
  manifests/05-service.yaml
  manifests/06-deployment-ibm-cloud-managed.yaml
  manifests/06-deployment.yaml
  manifests/07-cluster-operator.yaml
  manifests/07-servicemonitor.yaml
  manifests/08-prometheus_rule.yaml
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#667 OCPBUGS-499: fix: order conditions by type to limit un-needed updates
  pkg/controller/status/conditions.go
  pkg/controller/status/conditions_test.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/severity-moderate

#662 [release-4.11] OCPBUGS-429: backport helm upgrade and uninstall metric to 4.11
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/gatherers/clusterconfig/recent_metrics.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#665 [release-4.9] OCPBUGS-443: Gather status of the cephclusters.ceph.rook…
  docs/gathered-data.md
  docs/insights-archive-sample/config/storage/openshift-storage/ocs-storagecluster-cephcluster.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/ceph_cluster.go
  pkg/gatherers/clusterconfig/ceph_cluster_test.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#664 OCPBUGS-439: update the DVO metrics gatherer
  docs/conditional-gatherer/README.md
  pkg/cmd/start/receiver.go
  pkg/gatherers/clusterconfig/dvo_metrics.go
  pkg/recorder/diskrecorder/diskrecorder.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/severity-moderate

#663 [release-4.10] OCPBUGS-430: Helm upgrades and uninstalls backport 4.10
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/gatherers/clusterconfig/recent_metrics.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#668 [release-4.8] OCPBUGS-580: Gather status of the cephclusters.ceph.rook.io reso…
  docs/gathered-data.md
  docs/insights-archive-sample/config/storage/openshift-storage/ocs-storagecluster-cephcluster.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/ceph_cluster.go
  pkg/gatherers/clusterconfig/ceph_cluster_test.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#658 openshift-machine-api warning events gatherer
  docs/gathered-data.md
  docs/insights-archive-sample/events/openshift-machine-api.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/events_filtering.go
  pkg/gatherers/clusterconfig/events_filtering_test.go
  pkg/gatherers/clusterconfig/openshift_machine_api_events.go
  pkg/gatherers/clusterconfig/openshift_machine_api_events_test.go
  pkg/gatherers/clusterconfig/operators_pods_and_events.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved
