Repository openshift/insights-operator, pull requests merged in 2022-05, with the labels that each got.

#615 [release-4.10] Bug 2079318: Remove PSP gatherer (#608)
  docs/gathered-data.md
  docs/insights-archive-sample/config/psp_names.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/pod_security_policies.go
  pkg/gatherers/clusterconfig/pod_security_policies_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-low, backport-risk-assessed

#603 Implement fingerprint for records
  docs/insights-archive-sample/insights-operator/gathers.json
  pkg/config/mock_configurator.go
  pkg/controller/gather_job.go
  pkg/controller/periodic/periodic.go
  pkg/controller/periodic/periodic_test.go
  pkg/gather/gather.go
  pkg/gather/gather_test.go
  pkg/gather/mock_gatherers.go
  pkg/gatherers/clusterconfig/certificate_signing_requests.go
  pkg/gatherers/clusterconfig/cluster_config_v1_config_map_test.go
  pkg/gatherers/clusterconfig/config_maps.go
  pkg/gatherers/clusterconfig/config_maps_test.go
  pkg/gatherers/clusterconfig/host_subnets_test.go
  pkg/gatherers/clusterconfig/image_pruners_test.go
  pkg/gatherers/clusterconfig/image_registries_test.go
  pkg/gatherers/clusterconfig/install_plans.go
  pkg/gatherers/clusterconfig/install_plans_test.go
  pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids.go
  pkg/gatherers/clusterconfig/netnamespaces_test.go
  pkg/gatherers/clusterconfig/operators_test.go
  pkg/gatherers/clusterconfig/service_accounts.go
  pkg/gatherers/clusterconfig/service_accounts_test.go
  pkg/gatherers/clusterconfig/webhookconfigurations_test.go
  pkg/record/memory.go
  pkg/record/record.go
  pkg/record/resource_marshaller.go
  pkg/record/resource_marshaller_test.go
  pkg/recorder/interface.go
  pkg/recorder/mock_recorder.go
  pkg/recorder/recorder.go
  pkg/recorder/recorder_test.go
  pkg/types/types.go
  pkg/utils/marshal/raw.go
  pkg/utils/marshal/raw_byte.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#571 Cluster transfer OCM controller
  config/pod.yaml
  go.mod
  manifests/03-clusterrole.yaml
  pkg/cmd/start/start.go
  pkg/config/config.go
  pkg/config/configobserver/config.go
  pkg/controller/operator.go
  pkg/controller/status/conditions.go
  pkg/controller/status/controller.go
  pkg/controller/status/status.go
  pkg/controllerstatus/controllerstatus.go
  pkg/insights/insightsclient/requests.go
  pkg/ocm/clustertransfer/cluster_transfer.go
  pkg/ocm/clustertransfer/cluster_transfer_test.go
  pkg/ocm/clustertransfer/test-data/accepted-cluster-transfer.json
  pkg/ocm/clustertransfer/test-data/more-cluster-transfers.json
  pkg/ocm/clustertransfer/test-data/test-pull-secret.json
  pkg/ocm/clustertransfer/test-data/updated-pull-secret.json
  pkg/ocm/clustertransfer/types.go
  vendor/modules.txt
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#617 Update new gatherer OCP versions
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#618 Bug 2081997: Fix the clusteroperator conditions values when IO is
  pkg/controller/status/controller.go
  pkg/controller/status/status.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#616 AUTH-133: manifests/deployment: comply to restricted pod security level
  manifests/06-deployment-ibm-cloud-managed.yaml
  manifests/06-deployment.yaml
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#619 [release-4.10] Bug 2081844: Fix the clusteroperator conditions values…
  pkg/controller/status/controller.go
  pkg/controller/status/status.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed

#623 [release-4.9] Bug 2083467: Fix the clusteroperator conditions values …
  pkg/controller/status/status.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed

#622 Bug 2083451: Update to console.redhat.com services
  config/pod.yaml
  docs/arch.md
  pkg/cmd/start/start.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#627 Console helm metrics
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/recent_metrics.go
Labels: approved, ok-to-test, lgtm, px-approved, docs-approved, qe-approved

#631 Update links to machine-api types
  Makefile
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/machine_healthcheck.go
  pkg/gatherers/clusterconfig/machine_sets.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#625 gather io configuration
  docs/gathered-data.md
  docs/insights-archive-sample/config/secrets/openshift-config/support/data.json
  pkg/config/configobserver/configobserver.go
  pkg/gather/gather.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer_test.go
  pkg/gatherers/clusterconfig/support_secret.go
  pkg/gatherers/clusterconfig/support_secret_test.go
  pkg/utils/anonymize/string.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#620 save conditional gatherer endpoint and firing alerts in the metadata
  docs/conditional-gatherer/README.md
  docs/insights-archive-sample/insights-operator/conditional-gatherer-rules.json
  pkg/controller/kubeconfigs.go
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved
