Repository openshift/insights-operator, pull requests merged in 2022-03, with the labels that each got.

#584 Bug 2059586: Set default messages & reconcile clusteroperator status conditions
  pkg/controller/status/conditions.go
  pkg/controller/status/controller.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#582 Send gathering time as metadata field with upload request
  pkg/insights/insightsclient/insightsclient.go
  pkg/insights/insightsuploader/insightsuploader.go
  pkg/recorder/diskrecorder/diskrecorder.go
  pkg/recorder/diskrecorder/diskrecorder_test.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#585 HyperShift - Add required annotation to remaining manifests
  manifests/05-service.yaml
  manifests/06-deployment.yaml
  manifests/07-cluster-operator.yaml
  manifests/07-servicemonitor.yaml
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#586 Revert "Set default messages & reconcile clusteroperator status conditions (#584)
  pkg/controller/status/conditions.go
  pkg/controller/status/controller.go
Labels: approved, lgtm

#589 Bug 2061304: Don't serialize empty `images` attribute in the workload info gatherer
  pkg/gatherers/workloads/types.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low, docs-approved

#588 Bug 2059586: Set default messages & reconcile clusteroperator status conditions
  pkg/controller/status/conditions.go
  pkg/controller/status/controller.go
  pkg/controllerstatus/controllerstatus.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#590 fix some docs
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/feature_gates.go
  pkg/gatherers/clusterconfig/ingresses.go
  pkg/gatherers/clusterconfig/proxies.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#592 Bug 2063164: Revert "Set default messages & reconcile clusteroperator status conditions"
  pkg/controller/status/conditions.go
  pkg/controller/status/controller.go
  pkg/controllerstatus/controllerstatus.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-urgent

#596 Bug 2065547: Gather some error messages from the kube-controller-manager containers
  docs/gathered-data.md
  docs/insights-archive-sample/config/pod/openshift-kube-controller-manager/logs/kube-controller-manager-ip-10-0-168-11.us-east-2.compute.internal/errors.log
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/kube_controller_manager_logs.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#595 Bug 2059586: Set default messages & reconcile clusteroperator status conditions
  pkg/controller/status/conditions.go
  pkg/controller/status/controller.go
  pkg/controllerstatus/controllerstatus.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#583 implemented fetching rules from a remote server for conditional gathering
  Makefile
  README.md
  config/local.yaml
  config/pod.yaml
  debug.Dockerfile
  docs/conditional-gatherer/README.md
  pkg/authorizer/clusterauthorizer/clusterauthorizer.go
  pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
  pkg/cmd/start/start.go
  pkg/config/config.go
  pkg/config/configobserver/config.go
  pkg/controller/const.go
  pkg/controller/gather_job.go
  pkg/controller/kubeconfigs.go
  pkg/controller/operator.go
  pkg/controller/status/controller.go
  pkg/gather/gather.go
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/gatherers/conditional/conditions.go
  pkg/gatherers/conditional/gathering_functions.go
  pkg/gatherers/conditional/gathering_rules.schema.json
  pkg/gatherers/conditional/parsing.go
  pkg/gatherers/conditional/parsing_test.go
  pkg/gatherers/conditional/types.go
  pkg/insights/insightsclient/insightsclient.go
  pkg/insights/insightsclient/reader.go
  pkg/insights/insightsclient/requests.go
  pkg/insights/insightsclient/requests_test.go
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/insightsuploader/insightsuploader.go
  pkg/ocm/sca/sca.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#593 Create an alternate IO deployment manifest excluding the NodeSelector
  .gitignore
  .golangci.precommit.yml
  .golangci.yml
  Makefile
  go.mod
  go.sum
  manifests/06-deployment-ibm-cloud-managed.yaml
  manifests/06-deployment.yaml
  pkg/dependencymagnet/docs.go
  profile-patches/ibm-cloud-managed/06-deployment.yaml-patch
  vendor/github.com/openshift/build-machinery-go/LICENSE
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk
  vendor/github.com/openshift/build-machinery-go/make/default.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/default.mk
  vendor/github.com/openshift/build-machinery-go/make/doc.go
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk
  vendor/github.com/openshift/build-machinery-go/make/golang.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/doc.go
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/tmp.mk
  vendor/github.com/openshift/build-machinery-go/make/lib/version.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/operator.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/build.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/test-unit.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/verify-update.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/golang/version.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/help.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/bindata.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/codegen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-glide.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps-gomod.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/deps.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/imagebuilder.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/images.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/kustomize.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/doc.go
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/release.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/rpm.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
  vendor/github.com/openshift/build-machinery-go/scripts/doc.go
  vendor/github.com/openshift/build-machinery-go/scripts/run-telepresence.sh
  vendor/github.com/openshift/build-machinery-go/scripts/update-deps.sh
  vendor/modules.txt
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#597 Add list of anonymized data points to documentation
  README.md
  docs/anonymized-data.md
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#599 [release-4.9] Bug 2066825: Gather some error messages from the kube-c…
  docs/gathered-data.md
  docs/insights-archive-sample/config/pod/openshift-kube-controller-manager/logs/kube-controller-manager-ip-10-0-168-11.us-east-2.compute.internal/errors.log
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/kube_controller_manager_logs.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed
