Repository openshift/insights-operator, pull requests merged in 2022-04, with the labels that each got.

#601 save version of gathering rules in metadata
  docs/insights-archive-sample/insights-operator/conditional-gatherer-rules.json
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/parsing.go
  pkg/gatherers/conditional/parsing_test.go
  pkg/gatherers/conditional/types.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#604 Bug 2072842: Gather namespace names with overlapping UIDs
  docs/gathered-data.md
  docs/insights-archive-sample/config/namespaces_with_overlapping_uids.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids.go
  pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids_test.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#608 Bug 2073945: Remove PSP gatherer
  docs/gathered-data.md
  docs/insights-archive-sample/config/psp_names.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/pod_security_policies.go
  pkg/gatherers/clusterconfig/pod_security_policies_test.go
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-medium

#605 [release-4.10] Bug 2072848: Gather namespace names with overlapping UIDs
  docs/gathered-data.md
  docs/insights-archive-sample/config/namespaces_with_overlapping_uids.json
  pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
  pkg/controller/periodic/periodic.go
  pkg/gather/gather.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/install_plans_test.go
  pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids.go
  pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids_test.go
  pkg/gatherers/conditional/validation.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed

#600 Create a new Prometheus metric providing Insights gathering time
  config/pod.yaml
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/insightsreport/types.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#606 Minor gatherer documentation update
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/image.go
  pkg/gatherers/clusterconfig/kube_controller_manager_logs.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#611 [release-4.9] Bug 2076903: Gather namespace names with overlapping UI…
  docs/gathered-data.md
  docs/insights-archive-sample/config/namespaces_with_overlapping_uids.json
  pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
  pkg/gather/gather.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/install_plans_test.go
  pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids.go
  pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids_test.go
  pkg/gatherers/conditional/validation.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed

#613 Bug 2077851: Fix vendoring of the build-machinery-go
  pkg/dependencymagnet/docs.go
  vendor/github.com/openshift/build-machinery-go/Makefile
  vendor/github.com/openshift/build-machinery-go/OWNERS
  vendor/github.com/openshift/build-machinery-go/README.md
  vendor/github.com/openshift/build-machinery-go/doc.go
  vendor/github.com/openshift/build-machinery-go/go.mod
  vendor/modules.txt
Labels: approved, bugzilla/valid-bug, lgtm, bugzilla/severity-low

#612 [release-4.8] Bug 2077765: Gather namespace names with overlapping UI…
  docs/gathered-data.md
  docs/insights-archive-sample/config/namespaces_with_overlapping_uids.json
  pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
  pkg/gather/gather.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/install_plans_test.go
  pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids.go
  pkg/gatherers/clusterconfig/namespaces_with_overlapping_uids_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, bugzilla/severity-medium, backport-risk-assessed
