Repository openshift/insights-operator, pull requests merged in 2022-10, with the labels that each got.

#680 read DataPolicy attribute from the config API
  cmd/obfuscate-archive/main.go
  manifests/03-insightsdatagather-config-crd.yaml
  manifests/04-insightsdatagather-config-cr.yaml
  manifests/10-prometheus_rule.yaml
  manifests/11-servicemonitor.yaml
  pkg/anonymization/anonymizer.go
  pkg/anonymization/anonymizer_test.go
  pkg/config/configobserver/apiconfigobserver.go
  pkg/config/configobserver/secretconfigobserver_test.go
  pkg/config/mock_configurator.go
  pkg/controller/gather_job.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic_test.go
  pkg/gather/gather.go
  pkg/gather/gather_test.go
  pkg/recorder/recorder.go
  pkg/recorder/recorder_test.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#681 OCPBUGS-1949: limit the size of logs loaded into memory
  pkg/gatherers/clusterconfig/kube_controller_manager_logs.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/severity-moderate

#685 OCPBUGS-2346: refactor(dvo_metrics): remove name and namespace from dvo metrics
  pkg/gatherers/clusterconfig/dvo_metrics.go
  pkg/utils/read_lines_with_prefix.go
  pkg/utils/read_lines_with_prefix_test.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/severity-moderate

#688 Update owners list
  OWNERS
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#690 Improve GatherNodeLogs docs
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/node_logs.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#689 [release-4.11] OCPBUGS-2320: refactor(dvo_metrics): remove name and namespace from dvo metrics
  pkg/gatherers/clusterconfig/dvo_metrics.go
  pkg/utils/read_lines_with_prefix.go
  pkg/utils/read_lines_with_prefix_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#687 OCPBUGS-2249: fix the schema checking conditional gathering rules
  pkg/gatherers/conditional/gathering_rule.schema.json
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug

#650 refactor(workloads_info): reduce cognitive complexity
  pkg/gatherers/workloads/workloads_info.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#683 OCPBUGS-2915: Updated info link in insights recommendations
  pkg/insights/insightsclient/insightsclient.go
  pkg/insights/insightsclient/requests.go
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/insightsreport/insightsreport_test.go
  pkg/insights/metrics.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/severity-moderate
