Repository openshift/insights-operator, pull requests merged in 2023-12, with the labels that each got.

#876 Fix typo in link to gathers.json
  docs/arch.md
Labels: approved, lgtm

#857 CCXDEV-11946: finalize the config update to the new config map
  pkg/authorizer/clusterauthorizer/clusterauthorizer.go
  pkg/authorizer/clusterauthorizer/clusterauthorizer_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/configobserver/config_aggregator.go
  pkg/config/configobserver/config_aggregator_test.go
  pkg/config/configobserver/configmapobserver.go
  pkg/config/configobserver/secretconfigobserver.go
  pkg/config/legacy_config.go
  pkg/config/legacy_config_test.go
  pkg/config/types.go
  pkg/controller/gather_commands.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/controller/status/controller.go
  pkg/controller/status/controller_test.go
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/insightsreport/insightsreport_test.go
  pkg/insights/prometheus_rules.go
  pkg/insights/prometheus_rules_test.go
  pkg/ocm/clustertransfer/cluster_transfer.go
  pkg/ocm/clustertransfer/cluster_transfer_test.go
  pkg/ocm/sca/sca.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#872 NO-JIRA: update nodeSelector key in the deployment manifests
  manifests/06-deployment-ibm-cloud-managed.yaml
  manifests/06-deployment.yaml
  profile-patches/ibm-cloud-managed/06-deployment.yaml-patch
Labels: approved, lgtm, qe-approved, jira/valid-reference

#873 NO-JIRA: increase number of query attempts to the processing status endpoint i…
  pkg/controller/gather_commands.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#863 CCXDEV-11387: feat(gather): gathering kubelet journal logs
  docs/gathered-data.md
  docs/insights-archive-sample/config/node/logs/ip-10-0-135-228.us-east-2.compute.internal.log
  pkg/gatherers/clusterconfig/gather_node_logs.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#854 CCXDEV-11652: update related objects in the DataGather CR in techpreview
  pkg/controller/periodic/periodic.go
  pkg/controller/periodic/periodic_test.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#870 [release-4.14] OCPBUGS-23445: DVO gatherer - add retry logic (#861)
  pkg/gatherers/clusterconfig/gather_dvo_metrics.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#875 [release-4.13] OCPBUGS-22997: adds gather storageclasses
  docs/gathered-data.md
  docs/insights-archive-sample/config/storage/storageclasses/standard-csi.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_storageclass.go
  pkg/gatherers/clusterconfig/gather_storageclass_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#878 NO-JIRA: gather new insights-config CM & add warning for deprecated support se…
  docs/gathered-data.md
  docs/insights-archive-sample/config/configmaps/openshift-insights/insights-config/config.json
  pkg/config/configobserver/secretconfigobserver.go
  pkg/controller/status/gatherer_status.go
  pkg/gatherers/clusterconfig/gather_config_maps.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#882 OCPBUGS-23616: changelog script - parse arguments as time
  cmd/changelog/main.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#866 NO-JIRA: fix errors handling + docs + lint
  pkg/controller/periodic/periodic.go
  pkg/controller/status/controller_test.go
  pkg/controller/status/datagather_status.go
  pkg/controller/status/gatherer_status.go
  pkg/gatherers/clusterconfig/gather_ceph_cluster.go
  pkg/gatherers/clusterconfig/gather_cluster_image.go
  pkg/gatherers/clusterconfig/gather_cluster_oauth.go
  pkg/gatherers/clusterconfig/gather_cluster_operator_pods_and_events.go
  pkg/gatherers/clusterconfig/gather_kube_controller_manager_logs.go
  pkg/gatherers/clusterconfig/gather_openshift_logging.go
  pkg/gatherers/clusterconfig/gather_storage_cluster.go
  pkg/gatherers/conditional/gather_image_stream_definitions_of_namespace.go
  pkg/gatherers/workloads/gather_workloads_info.go
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/insightsuploader/insightsuploader.go
  pkg/insights/prometheus_rules.go
  pkg/record/resource_marshaller.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#883 [release-4.13] OCPBUGS-24255: adds helm information gather
  docs/gathered-data.md
  docs/insights-archive-sample/config/helmchart_info.json
  pkg/gather/gather.go
  pkg/gatherers/workloads/gather_helm_info.go
  pkg/gatherers/workloads/gather_helm_info_test.go
  pkg/gatherers/workloads/types.go
  pkg/gatherers/workloads/types_test.go
  pkg/gatherers/workloads/workloads_gatherer.go
  pkg/gatherers/workloads/workloads_gatherer_test.go
  pkg/gatherers/workloads/workloads_info_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference
