Repository openshift/insights-operator, pull requests merged in 2023-02, with the labels that each got.

#698 [release-4.11] OCPBUGS-3380: fix storage/ceph path structure
  docs/gathered-data.md
  docs/insights-archive-sample/config/storage/openshift-storage/cephclusters/ocs-storagecluster-cephcluster.json
  docs/insights-archive-sample/config/storage/openshift-storage/ocs-storagecluster-cephcluster.json
  docs/insights-archive-sample/config/storage/openshift-storage/ocs-storagecluster.json
  docs/insights-archive-sample/config/storage/openshift-storage/storageclusters/ocs-storagecluster.json
  pkg/gatherers/clusterconfig/ceph_cluster.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/cost_management_metrics_configs.go
  pkg/gatherers/clusterconfig/machine_configs.go
  pkg/gatherers/clusterconfig/node_logs.go
  pkg/gatherers/clusterconfig/openshift_logging.go
  pkg/gatherers/clusterconfig/openshift_storage.go
  pkg/gatherers/clusterconfig/sap_datahubs.go
  pkg/gatherers/clusterconfig/storage_cluster.go
  pkg/gatherers/clusterconfig/storage_cluster_test.go
  pkg/gatherers/conditional/gather_api_request_count.go
  pkg/gatherers/conditional/gather_containers_logs.go
  pkg/gatherers/conditional/gather_pod_definition.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#725 OCPBUGS-6781: Create gatherer for gathering machines.
  docs/gathered-data.md
  docs/insights-archive-sample/config/machines/openshift-machine-api/dev-rhrmo-dev-26-01-2-tk6g8-master-0.json
  docs/insights-archive-sample/config/machines/openshift-machine-api/dev-rhrmo-dev-26-01-2-tk6g8-master-1.json
  docs/insights-archive-sample/config/machines/openshift-machine-api/dev-rhrmo-dev-26-01-2-tk6g8-master-2.json
  docs/insights-archive-sample/config/machines/openshift-machine-api/dev-rhrmo-dev-26-01-2-tk6g8-worker-us-east-2a-4g2rj.json
  docs/insights-archive-sample/config/machines/openshift-machine-api/dev-rhrmo-dev-26-01-2-tk6g8-worker-us-east-2b-kz6kb.json
  docs/insights-archive-sample/config/machines/openshift-machine-api/dev-rhrmo-dev-26-01-2-tk6g8-worker-us-east-2c-hg88m.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/machines.go
  pkg/gatherers/clusterconfig/machines_test.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference

#726 OCPBUGS-6832: feat(recent_metrics) adds openshift_apps_deploymentconfigs_strategy_total
  .gitignore
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/controller/status/controller.go
  pkg/gatherers/clusterconfig/recent_metrics.go
Labels: approved, bugzilla/valid-bug, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#723 OCPBUGS-6731: Anonymize env vars from containers: HTTP_PROXY, HTTPS_PROXY
  CHANGELOG.md
  pkg/gatherers/clusterconfig/container_images.go
  pkg/gatherers/clusterconfig/operators_pods_and_events.go
  pkg/gatherers/clusterconfig/version.go
  pkg/gatherers/conditional/gather_pod_definition.go
  pkg/utils/anonymize/envvars.go
  pkg/utils/anonymize/envvars_test.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference

#736 [release-4.12] OCPBUGS-6833: feat(recent_metrics) adds openshift_apps_deploymentconfigs_strategy_total
  .gitignore
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/controller/status/controller.go
  pkg/gatherers/clusterconfig/recent_metrics.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#733 Add unit tests to openshift sdn controller logs gatherer
  CHANGELOG.md
  pkg/gatherers/clusterconfig/gather_openshift_sdn_controller_logs.go
  pkg/gatherers/clusterconfig/gather_openshift_sdn_controller_logs_test.go
Labels: approved, lgtm, qe-approved

#735 gather logs - update "FilterLogFromScanner" function and add some tests
  pkg/gatherers/common/gather_logs.go
  pkg/gatherers/common/gather_logs_test.go
Labels: approved, lgtm, qe-approved

#739 [release-4.11] OCPBUGS-6834: feat(recent_metrics) adds openshift_apps_deploymentconfigs_strategy_total
  .gitignore
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/controller/status/controller.go
  pkg/gatherers/clusterconfig/recent_metrics.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#738 test(oauth): add unit test for oauth.go and rename it to gather_cluster_oauth.go
  pkg/gatherers/clusterconfig/gather_cluster_oauth.go
  pkg/gatherers/clusterconfig/gather_cluster_oauth_test.go
Labels: approved, lgtm, qe-approved
