Repository openshift/insights-operator, pull requests merged in 2023-03, with the labels that each got.

#729 test(clusterconfig): add unit test for ingresses.go and rename it to gather_cluster_ingress.go
  pkg/gatherers/clusterconfig/gather_cluster_ingress.go
  pkg/gatherers/clusterconfig/gather_cluster_ingress_test.go
Labels: approved, lgtm, qe-approved

#728 test(clusterconfig): add unit test for silenced_alerts.go and rename it to gather_silenced_alerts.go
  pkg/gatherers/clusterconfig/gather_silenced_alerts.go
  pkg/gatherers/clusterconfig/gather_silenced_alerts_test.go
Labels: approved, lgtm, qe-approved

#740 [release-4.10] OCPBUGS-6835: feat(recent_metrics) adds openshift_apps_deploymentconfigs_strategy_total
  .gitignore
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/controller/status/controller.go
  pkg/gatherers/clusterconfig/recent_metrics.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#741 OCPBUGS-7870: Collect info about monitoring pods pv
  CHANGELOG.md
  docs/gathered-data.md
  docs/insights-archive-sample/config/persistentvolumes/monitoring-persistent-volume.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_monitoring_pvs.go
  pkg/gatherers/clusterconfig/gather_monitoring_pvs_test.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/valid-reference

#745 update periodic_test.go & run unit tests with -race param
  Makefile
  pkg/controller/periodic/periodic_test.go
Labels: approved, lgtm, qe-approved

#743 Update docs & remove gathering of non-existing 'etcd_object_counts' m…
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/gatherers/clusterconfig/machines.go
  pkg/gatherers/clusterconfig/recent_metrics.go
Labels: approved, lgtm, qe-approved

#730 test(clusterconfig): add unit test for active_alerts.go and rename it to gather_active_alerts.go
  pkg/gatherers/clusterconfig/gather_active_alerts.go
  pkg/gatherers/clusterconfig/gather_active_alerts_test.go
Labels: approved, lgtm, qe-approved

#756 test(clusterconfig): add unit tests for cluster proxy gatherer
  CHANGELOG.md
  cmd/changelog/main.go
  cmd/gendoc/main.go
  pkg/config/configobserver/apiconfigobserver.go
  pkg/gather/tasks_processing_test.go
  pkg/gatherers/clusterconfig/gather_cluster_proxy.go
  pkg/gatherers/clusterconfig/gather_cluster_proxy_test.go
Labels: approved, lgtm, qe-approved

#731 test(clusterconfig): add unit test for nodes.go and rename it to gather_nodes.go
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/gather_nodes.go
  pkg/gatherers/clusterconfig/gather_nodes_test.go
Labels: approved, lgtm, qe-approved

#732 test(clusterconfig): add unit test for version.go and rename it to gather_cluster_version.go
  pkg/gatherers/clusterconfig/gather_cluster_version.go
  pkg/gatherers/clusterconfig/gather_cluster_version_test.go
Labels: approved, lgtm, qe-approved
