Repository openshift/insights-operator, pull requests merged in 2023-10, with the labels that each got.

#829 [release-4.11] OCPBUGS-19946: workload info gatherer, add external image repo
  docs/insights-archive-sample/config/workload_info.json
  pkg/gatherers/workloads/types.go
  pkg/gatherers/workloads/workloads_info.go
  pkg/gatherers/workloads/workloads_info_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#825 OCPBUGS-19695: gather APIServer.config.openshift.io resource
  docs/gathered-data.md
  docs/insights-archive-sample/config/apiserver.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_cluster_apiserver.go
  pkg/gatherers/clusterconfig/gather_cluster_apiserver_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#832 OCPBUGS-20034: improve on-demand data gathering timing issues
  pkg/controller/periodic/periodic.go
  pkg/controller/periodic/periodic_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#833 OCPBUGS-20320: fix error message when the data processing was not suc…
  pkg/controller/gather_commands.go
  pkg/controller/gather_commands_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#839 [release-4.14] OCPBUGS-20590: gather APIServer.config.openshift.io resource
  .openshiftci/install-golangci-lint.sh
  docs/gathered-data.md
  docs/insights-archive-sample/config/apiserver.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_cluster_apiserver.go
  pkg/gatherers/clusterconfig/gather_cluster_apiserver_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#827 First minimal PoC version for moving the configuration to configmap
  manifests/03-clusterrole.yaml
  pkg/config/configobserver/config_aggregator.go
  pkg/config/configobserver/config_aggregator_test.go
  pkg/config/configobserver/configmapobserver.go
  pkg/config/mock_configurator.go
  pkg/config/types.go
  pkg/controller/gather_commands.go
  pkg/controller/gather_commands_test.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/controller/periodic/periodic_test.go
  pkg/gather/gather.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_support_secret.go
  pkg/gatherers/clusterconfig/gather_support_secret_test.go
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/insights/insightsuploader/insightsuploader.go
Labels: approved, lgtm, qe-approved

#845 OCPBUGS-22173: Revert #827 "First minimal PoC version for moving the configuration to configmap"
  manifests/03-clusterrole.yaml
  pkg/config/configobserver/config_aggregator.go
  pkg/config/configobserver/config_aggregator_test.go
  pkg/config/configobserver/configmapobserver.go
  pkg/config/mock_configurator.go
  pkg/config/types.go
  pkg/controller/gather_commands.go
  pkg/controller/gather_commands_test.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/controller/periodic/periodic_test.go
  pkg/gather/gather.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_support_secret.go
  pkg/gatherers/clusterconfig/gather_support_secret_test.go
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/insights/insightsuploader/insightsuploader.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#846 fix the reverted configmap PR
  manifests/03-clusterrole.yaml
  pkg/config/configobserver/config_aggregator.go
  pkg/config/configobserver/config_aggregator_test.go
  pkg/config/configobserver/configmapobserver.go
  pkg/config/mock_configurator.go
  pkg/config/types.go
  pkg/controller/gather_commands.go
  pkg/controller/gather_commands_test.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/controller/periodic/periodic_test.go
  pkg/gather/gather.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_support_secret.go
  pkg/gatherers/clusterconfig/gather_support_secret_test.go
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/insights/insightsuploader/insightsuploader.go
Labels: approved, lgtm, qe-approved

#849 Revert #846 "fix the reverted configmap PR"
  manifests/03-clusterrole.yaml
  pkg/config/configobserver/config_aggregator.go
  pkg/config/configobserver/config_aggregator_test.go
  pkg/config/configobserver/configmapobserver.go
  pkg/config/mock_configurator.go
  pkg/config/types.go
  pkg/controller/gather_commands.go
  pkg/controller/gather_commands_test.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/controller/periodic/periodic_test.go
  pkg/gather/gather.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_support_secret.go
  pkg/gatherers/clusterconfig/gather_support_secret_test.go
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/insights/insightsuploader/insightsuploader.go
Labels: approved, lgtm, jira/valid-bug

#848 [release-4.13] OCPBUGS-22330: gather APIServer.config.openshift.io resource
  docs/gathered-data.md
  docs/insights-archive-sample/config/apiserver.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_cluster_apiserver.go
  pkg/gatherers/clusterconfig/gather_cluster_apiserver_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#847 add retry logic to the DVO metrics gatherer
  pkg/gatherers/clusterconfig/gather_dvo_metrics.go
Labels: approved, lgtm, qe-approved

#852 Fix lint, pin its version and other minor fixes
  .openshiftci/install-golangci-lint.sh
  cmd/gendoc/main.go
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/gather_cluster_infrastructure.go
  pkg/gatherers/clusterconfig/gather_install_plans.go
  pkg/gatherers/clusterconfig/gather_olm_operators.go
Labels: approved, lgtm, qe-approved

#851 Revert the previous revert and fix
  manifests/03-clusterrole.yaml
  pkg/config/configobserver/config_aggregator.go
  pkg/config/configobserver/config_aggregator_test.go
  pkg/config/configobserver/configmapobserver.go
  pkg/config/mock_configurator.go
  pkg/config/types.go
  pkg/controller/gather_commands.go
  pkg/controller/gather_commands_test.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/controller/periodic/periodic_test.go
  pkg/gather/gather.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_support_secret.go
  pkg/gatherers/clusterconfig/gather_support_secret_test.go
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/insights/insightsuploader/insightsuploader.go
Labels: approved, lgtm, qe-approved

#853 [release-4.12] OCPBUGS-22435: gather APIServer.config.openshift.io resource
  docs/gathered-data.md
  docs/insights-archive-sample/config/apiserver.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_cluster_apiserver.go
  pkg/gatherers/clusterconfig/gather_cluster_apiserver_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#844 extends obfuscation options in the configmap
  pkg/anonymization/anonymizer.go
  pkg/anonymization/anonymizer_test.go
  pkg/config/configobserver/config_aggregator.go
  pkg/config/configobserver/config_aggregator_test.go
  pkg/config/types.go
  pkg/controller/gather_commands.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic_test.go
  pkg/gather/gather_test.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_cluster_operator_pods_and_events.go
  pkg/gatherers/clusterconfig/gather_cluster_version.go
  pkg/gatherers/clusterconfig/gather_dvo_metrics.go
  pkg/gatherers/clusterconfig/gather_openshift_machine_api_events.go
  pkg/recorder/recorder_test.go
Labels: approved, lgtm, qe-approved
