Repository openshift/insights-operator, pull requests merged in 2023-06, with the labels that each got.

#777 update DVO metrics example in the sample archive
  docs/insights-archive-sample/config/dvo_metrics
Labels: approved, lgtm

#783 Update documentation
  CHANGELOG.md
  cmd/changelog/main.go
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/gather_monitoring_pvs.go
Labels: approved, lgtm

#792 OCPBUGS-14771: run an extra config informer in the tech preview
  pkg/anonymization/anonymizer.go
  pkg/config/configobserver/insighgtsdatagather_observer.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/controller/status/controller.go
  pkg/insights/insightsuploader/insightsuploader.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#794 OCPBUGS-14937: fix the config serialization & add test
  pkg/cmd/start/start.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#797 Revert "feat(clusterconfig): adds virtual machine instances gather"
  docs/gathered-data.md
  docs/insights-archive-sample/config/virtualmachineinstances/openshift-cnv/fedora-r2nf0eocvxbkmqjy.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/gather_virtual_machine_instances.go
  pkg/gatherers/clusterconfig/gather_virtual_machine_instances_test.go
Labels: approved, lgtm

#796 [release-4.13] OCPBUGS-15031: fix the config serialization & add test…
  pkg/cmd/start/start.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#791 [release-4.13] OCPBUGS-14773: extend configmap gatherer to get gatewa…
  docs/gathered-data.md
  docs/insights-archive-sample/config/configmaps/openshift-network-operator/gateway-mode-config/mode.json
  pkg/gatherers/clusterconfig/config_maps.go
  pkg/gatherers/clusterconfig/config_maps_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#778 chore: adds codecov
  .codecov.yml
  .editorconfig
  .openshiftci/check-coverage.sh
  .openshiftci/publish-codecov.sh
  Makefile
Labels: approved, lgtm

#801 [release-4.12] OCPBUGS-15414: extend configmap gatherer to get gatewa…
  docs/gathered-data.md
  docs/insights-archive-sample/config/configmaps/openshift-network-operator/gateway-mode-config/mode.json
  pkg/gatherers/clusterconfig/config_maps.go
  pkg/gatherers/clusterconfig/config_maps_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#804 [release-4.12] OCPBUGS-15459: gather PDBs only from openshift namespaces
  pkg/gatherers/clusterconfig/pod_disruption_budgets.go
  pkg/gatherers/clusterconfig/pod_disruption_budgets_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#802 [release-4.11] OCPBUGS-15446: extend configmap gatherer to get gatewa…
  docs/gathered-data.md
  docs/insights-archive-sample/config/configmaps/openshift-network-operator/gateway-mode-config/mode.json
  pkg/gatherers/clusterconfig/config_maps.go
  pkg/gatherers/clusterconfig/config_maps_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference
