Repository openshift/insights-operator, pull requests merged in 2023-01, with the labels that each got.

#703 chore(golanglint-ci) disabling some linters for *_test.go files
  .golangci.precommit.yml
  .golangci.yml
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#701 refactor(scheduler): move GatherSchedulerLogs to its own file
  pkg/gatherers/clusterconfig/scheduler.go
  pkg/gatherers/clusterconfig/scheduler_logs.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#702 refactor(webhookconfigurations): remove asset method and split tests
  pkg/gatherers/clusterconfig/mutatingwebhookconfigurations_test.go
  pkg/gatherers/clusterconfig/validatingwebhookconfigurations_test.go
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#706 OCPBUGS-5257: do not get disabled rules
  config/pod.yaml
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug, jira/severity-moderate

#697 [release-4.12] OCPBUGS-3379: fix storage/ceph path structure
  docs/gathered-data.md
  docs/insights-archive-sample/config/storage/openshift-storage/cephclusters/ocs-storagecluster-cephcluster.json
  docs/insights-archive-sample/config/storage/openshift-storage/ocs-storagecluster-cephcluster.json
  docs/insights-archive-sample/config/storage/openshift-storage/ocs-storagecluster.json
  docs/insights-archive-sample/config/storage/openshift-storage/storageclusters/ocs-storagecluster.json
  pkg/gatherers/clusterconfig/ceph_cluster.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/cost_management_metrics_configs.go
  pkg/gatherers/clusterconfig/machine_configs.go
  pkg/gatherers/clusterconfig/node_logs.go
  pkg/gatherers/clusterconfig/openshift_logging.go
  pkg/gatherers/clusterconfig/openshift_storage.go
  pkg/gatherers/clusterconfig/sap_datahubs.go
  pkg/gatherers/clusterconfig/storage_cluster.go
  pkg/gatherers/clusterconfig/storage_cluster_test.go
  pkg/gatherers/conditional/gather_api_request_count.go
  pkg/gatherers/conditional/gather_containers_logs.go
  pkg/gatherers/conditional/gather_pod_definition.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#712 Update operator name in the OWNERS file
  OWNERS
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#713 [release-4.12] Bug OCPBUGS-5463: do not get disabled rules
  config/pod.yaml
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate

#709 OCPBUGS-5347: do not periodically update Available clusteroperator co…
  pkg/controller/status/conditions.go
  pkg/controller/status/conditions_test.go
  pkg/controller/status/controller.go
  pkg/controller/status/controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug

#716 OCPBUGS-5347: additional fix
  pkg/controller/status/controller.go
  pkg/controller/status/controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug

#717 Revert "OCPBUGS-5347: additional fix"
  pkg/controller/status/controller.go
  pkg/controller/status/controller_test.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug

#714 OCPBUGS-5903: operators gatherer - handle ingresscontroller relatedObject & simplify
  docs/gathered-data.md
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/ingresscontroller/openshift-ingress-operator/default.json
  pkg/gatherers/clusterconfig/operators.go
  pkg/gatherers/clusterconfig/operators_test.go
Labels: approved, bugzilla/valid-bug, lgtm, jira/valid-bug

#710 [release-4.12] OCPBUGS-5348: do not periodically update Available clusteroperator co…
  pkg/controller/status/conditions.go
  pkg/controller/status/conditions_test.go
  pkg/controller/status/controller.go
  pkg/controller/status/controller_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#718 [release-4.11] OCPBUGS-5349: do not periodically update Available clusteroperator co…
  pkg/controller/status/conditions.go
  pkg/controller/status/conditions_test.go
  pkg/controller/status/controller.go
  pkg/controller/status/controller_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#719 [release-4.12] OCPBUGS-5976: operators gatherer - handle ingresscontroller relatedOb…
  docs/gathered-data.md
  docs/insights-archive-sample/config/clusteroperator/operator.openshift.io/ingresscontroller/openshift-ingress-operator/default.json
  pkg/gatherers/clusterconfig/operators.go
  pkg/gatherers/clusterconfig/operators_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#721 arch docs update - explain disabled=true status more
  docs/arch.md
Labels: approved, lgtm, px-approved, docs-approved, qe-approved

#720 [release-4.10] OCPBUGS-1987: do not periodically update Available clu…
  pkg/controller/status/conditions.go
  pkg/controller/status/conditions_test.go
  pkg/controller/status/controller.go
  pkg/controller/status/controller_test.go
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
