Repository openshift/insights-operator, pull requests merged in 2023-07, with the labels that each got.

#776 chore: general code cleanup
  .golangci.yml
  CONTRIBUTING.md
  STYLEGUIDE.md
  cmd/changelog/main.go
  cmd/gendoc/main.go
  docs/arch.md
  docs/conditional-gatherer/README.md
  pkg/anonymization/anonymizer.go
  pkg/cmd/start/start.go
  pkg/config/configobserver/secretconfigobserver_test.go
  pkg/config/mock_configurator.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic_test.go
  pkg/controller/status/conditions.go
  pkg/controller/status/controller.go
  pkg/gather/gather.go
  pkg/gatherers/clusterconfig/cluster_config_v1_config_map.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/gather_certificate_signing_requests.go
  pkg/gatherers/clusterconfig/gather_cluster_operators.go
  pkg/gatherers/clusterconfig/gather_cluster_operators_test.go
  pkg/gatherers/clusterconfig/gather_openshift_machine_api_events.go
  pkg/gatherers/interface.go
  pkg/insights/insightsclient/requests.go
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/insightsreport/insightsreport_test.go
  pkg/insights/metrics.go
  pkg/ocm/clustertransfer/cluster_transfer.go
  pkg/ocm/const.go
  pkg/ocm/sca/sca.go
  pkg/recorder/diskrecorder/diskrecorder.go
  pkg/utils/dns.go
Labels: approved, lgtm, qe-approved

#808 update registration of the metrics to work in techpreview too
  pkg/controller/gather_commands.go
  pkg/controller/operator.go
  pkg/controller/periodic/periodic.go
  pkg/insights/insightsclient/insightsclient.go
  pkg/insights/insightsclient/requests.go
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/insightsreport/insightsreport_test.go
  pkg/insights/insightsuploader/insightsuploader.go
  pkg/insights/metrics.go
Labels: approved, lgtm, qe-approved

#809 OCPBUGS-16017: update DataGather CR status in case of job failure
  pkg/controller/gather_commands.go
  pkg/controller/periodic/periodic.go
  pkg/controller/status/datagather_conditions.go
  pkg/controller/status/datagather_status.go
  pkg/controller/status/datagather_status_test.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference

#806 [release-4.11] OCPBUGS-15506: gather PDBs only from openshift namespaces
  pkg/gatherers/clusterconfig/pod_disruption_budgets.go
  pkg/gatherers/clusterconfig/pod_disruption_budgets_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference
