Repository openshift/insights-operator, pull requests merged in 2023-09, with the labels that each got.

#819 update changelog
  CHANGELOG.md
Labels: approved, lgtm, qe-approved

#820 Minor fixes for the techpreview
  pkg/controller/gather_commands.go
  pkg/controller/periodic/periodic.go
  pkg/ocm/sca/sca.go
Labels: approved, lgtm, qe-approved

#823 [release-4.12] OCPBUGS-19405: workload info gatherer, add external image repo
  docs/insights-archive-sample/config/workload_info.json
  pkg/config/config_test.go
  pkg/gatherers/workloads/types.go
  pkg/gatherers/workloads/workloads_info.go
  pkg/gatherers/workloads/workloads_info_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#824 OCPBUGS-19476: update Insights report config logging
  pkg/insights/insightsreport/insightsreport.go
Labels: approved, lgtm, qe-approved, jira/severity-important, jira/valid-bug, jira/valid-reference
