Repository openshift/insights-operator, pull requests merged in 2023-11, with the labels that each got.

#855 [release-4.11] OCPBUGS-22763: gather APIServer.config.openshift.io resource
  docs/gathered-data.md
  docs/insights-archive-sample/config/apiserver.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_cluster_apiserver.go
  pkg/gatherers/clusterconfig/gather_cluster_apiserver_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#858 OCPBUGS-22958: adds cluster storageclasses gather
  docs/gathered-data.md
  docs/insights-archive-sample/config/storage/storageclasses/standard-csi.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_storageclass.go
  pkg/gatherers/clusterconfig/gather_storageclass_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#834 CCXDEV-11152: docs(openshift_apiserver_operator_logs): explicit namespace at archiv…
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/gather_openshift_apiserver_operator_logs.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#861 OCPBUGS-23097: DVO gatherer - do the retry request as HEAD and not stream
  pkg/gatherers/clusterconfig/gather_dvo_metrics.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#865 [release-4.14] OCPBUGS-22996: adds cluster storageclasses gather (#858)
  docs/gathered-data.md
  docs/insights-archive-sample/config/storage/storageclasses/standard-csi.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_storageclass.go
  pkg/gatherers/clusterconfig/gather_storageclass_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#864 CCXDEV-12194: read configmap during configmap observer init
  pkg/config/configobserver/configmapobserver.go
  pkg/controller/operator.go
Labels: approved, lgtm, qe-approved, jira/valid-reference
