Repository openshift/insights-operator, pull requests merged in 2024-08, with the labels that each got.

#985 NO-JIRA: add definition of done
  DoD.md
Labels: approved, lgtm, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#975 NO-JIRA: Update docs for GatherAggregatedMonitoringCRNames with backport versions
  CHANGELOG.md
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/gather_aggregated_instances.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#984 [release-4.14] OCPBUGS-37673: Missing cluster role
  manifests/03-clusterrole.yaml
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference
