Repository openshift/insights-operator, pull requests merged in 2024-02, with the labels that each got.

#899 OCPBUGS-26937: Add extra check in ids to bypass validations
  .snyk
  cmd/changelog/main.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#907 NO-JIRA: add permission for prometheus to be able to read metrics
  manifests/03-clusterrole.yaml
Labels: approved, lgtm, qe-approved, jira/valid-reference

#898 NO-JIRA: adjust log level of some rather important messages
  pkg/cmd/start/start.go
  pkg/config/configobserver/secretconfigobserver.go
  pkg/controller/gather_commands.go
  pkg/controller/periodic/periodic.go
  pkg/controller/status/controller.go
  pkg/gather/tasks_processing.go
  pkg/gatherers/workloads/gather_workloads_info.go
  pkg/insights/insightsclient/requests.go
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/insightsuploader/insightsuploader.go
  pkg/recorder/diskrecorder/diskrecorder.go
  pkg/recorder/recorder.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#895 NO-JIRA: manifests: bump loglevel of operator to normal
  manifests/06-deployment-ibm-cloud-managed.yaml
  manifests/06-deployment.yaml
Labels: approved, ok-to-test, lgtm, qe-approved, jira/valid-reference

#904 [release-4.14] OCPBUGS-24698: Add extra check in ids to bypass validations
  .snyk
  cmd/changelog/main.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#909 [release-4.13] OCPBUGS-29597: gather etcd_server_slow metrics (#902)
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/gatherers/clusterconfig/recent_metrics.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#905 [release-4.13] OCPBUGS-28157: Add extra check in ids to bypass validations
  .snyk
  cmd/changelog/main.go
  pkg/gatherers/clusterconfig/operators_pods_and_events_test.go
  pkg/gatherers/workloads/gather_helm_info.go
  pkg/gatherers/workloads/types_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#911 NO-JIRA: adjust loglevel for some further messages
  pkg/config/configobserver/secretconfigobserver.go
  pkg/config/legacy_config.go
  pkg/controller/status/controller.go
  pkg/controllerstatus/controllerstatus.go
  pkg/insights/insightsclient/requests.go
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/insightsuploader/insightsuploader.go
  pkg/recorder/diskrecorder/diskrecorder.go
  pkg/recorder/recorder.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#913 NO-JIRA: update the gathered CPU usage metric
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/gatherers/clusterconfig/gather_most_recent_metrics.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#906 [release-4.12] OCPBUGS-28519: Add extra check in ids to bypass validations
  .snyk
  cmd/changelog/main.go
  pkg/gatherers/clusterconfig/operators_pods_and_events_test.go
  pkg/gatherers/workloads/gather_helm_info_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference
