Repository openshift/insights-operator, pull requests merged in 2024-10, with the labels that each got.

#1005 [release-4.17] OCPBUGS-39563: Not able to enable repositories during entitled build in OCP Cluster on IBM-Z
  pkg/ocm/sca/sca.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1006 OCPBUGS-42675: do not propagate the remote configuration status as an
  pkg/controller/gather_commands.go
  pkg/controller/gather_commands_test.go
  pkg/controller/periodic/periodic.go
  pkg/controller/periodic/periodic_test.go
  pkg/controller/status/controller.go
  pkg/controller/status/datagather_status.go
  pkg/controllerstatus/controllerstatus.go
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/gatherers/conditional/types.go
  pkg/gatherers/conditional/validation.go
  pkg/gatherers/interface.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1012 NO-JIRA: container log JSON schema - minor description update
  pkg/gatherers/conditional/container_log.schema.json
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1013 [release-4.16] OCPBUGS-39564: Not able to enable repositories during entitled build in OCP Cluster on IBM-Z
  pkg/controller/operator.go
  pkg/insights/insightsclient/insightsclient.go
  pkg/insights/insightsclient/requests.go
  pkg/ocm/sca/sca.go
  pkg/ocm/sca/sca_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1010 NO-JIRA: Updating build options in order to ensure FIPS compliant build
  Dockerfile
  Makefile
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1015 [release-4.15] OCPBUGS-39565: Not able to enable repositories during entitled build in OCP Cluster on IBM-Z
  pkg/controller/operator.go
  pkg/insights/insightsclient/insightsclient.go
  pkg/insights/insightsclient/requests.go
  pkg/ocm/sca/sca.go
  pkg/ocm/sca/sca_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1007 CCXDEV-14462: [IO Enhancement] collect how many unused MachineConfigs in the cluster
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/gather_machine_configs.go
  pkg/gatherers/clusterconfig/gather_machine_configs_test.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1009 OCPBUGS-42961: update the filtering of the container logs
  pkg/gatherers/conditional/filter_and_gather_container_logs.go
  pkg/gatherers/conditional/filter_and_gather_container_logs_test.go
  pkg/gatherers/conditional/types.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#1018 NO-JIRA: Add gather server error known codes to the checks
  pkg/gatherers/conditional/conditional_gatherer_test.go
Labels: approved, ok-to-test, lgtm, qe-approved, jira/valid-reference

#1016 OCPBUGS-43651: gather selected clusterroles
  docs/gathered-data.md
  docs/insights-archive-sample/cluster-scoped-resources/rbac.authorization.k8s.io/clusterroles/admin.json
  docs/insights-archive-sample/cluster-scoped-resources/rbac.authorization.k8s.io/clusterroles/edit.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_cluster_roles.go
  pkg/gatherers/clusterconfig/gather_cluster_roles_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1017 NO-JIRA: add/update some missing sample data
  docs/gathered-data.md
  docs/insights-archive-sample/config/certificatesigningrequests/csr-test.json
  docs/insights-archive-sample/config/pod/di-288312/auditlog-retention-28566720-t22qj.json
  docs/insights-archive-sample/config/pod/di-288312/data-hub-flow-agent-1a3a7e88888b7fe0630189-qcwhm-547b57cc5fvmg8.json
  docs/insights-archive-sample/config/pod/di-288312/default-2k58azz-backup-deletion-5rdw4.json
  docs/insights-archive-sample/config/pod/di-288312/vsystem-867f4b77cc-pqcns.json
  pkg/gatherers/clusterconfig/gather_certificate_signing_requests.go
  pkg/gatherers/clusterconfig/gather_cluster_operator_pods_and_events.go
  pkg/gatherers/clusterconfig/gather_machine_configs.go
  pkg/gatherers/clusterconfig/gather_sap_pods.go
Labels: approved, lgtm, qe-approved, jira/valid-reference
