Repository openshift/insights-operator, pull requests merged in 2024-12, with the labels that each got.

#1033 AUTH-482: set required-scc for dataGahtering jobs & pods
  pkg/controller/periodic/job.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1039 CCXDEV-14573: sort the JSON schema validation errors
  pkg/gatherers/conditional/validation.go
  pkg/gatherers/conditional/validation_test.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1043 OCPBUGS-45047: Avoid to send the same error repeated N times
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/gather_lokistack.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1045 NO-JIRA: golanci-lint version update & corresponding fixes
  .golangci.yml
  .openshiftci/install-golangci-lint.sh
  cmd/changelog/main.go
  cmd/gendoc/main.go
  cmd/insights-operator/main.go
  pkg/anonymization/anonymizer.go
  pkg/cmd/start/receiver.go
  pkg/cmd/start/start.go
  pkg/config/configobserver/secretconfigobserver_test.go
  pkg/controller/periodic/job.go
  pkg/controller/periodic/periodic.go
  pkg/controller/status/controller_test.go
  pkg/gather/gather.go
  pkg/gather/gather_test.go
  pkg/gather/tasks_processing_test.go
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_certificate_signing_requests_test.go
  pkg/gatherers/clusterconfig/gather_cluster_image_registries_test.go
  pkg/gatherers/clusterconfig/gather_cluster_operator_pods_and_events_test.go
  pkg/gatherers/clusterconfig/gather_cluster_operators_test.go
  pkg/gatherers/clusterconfig/gather_config_maps_test.go
  pkg/gatherers/clusterconfig/gather_dvo_metrics.go
  pkg/gatherers/clusterconfig/gather_image_pruners_test.go
  pkg/gatherers/clusterconfig/gather_install_plans_test.go
  pkg/gatherers/clusterconfig/gather_machines_test.go
  pkg/gatherers/clusterconfig/gather_most_recent_metrics_test.go
  pkg/gatherers/clusterconfig/gather_node_logs_test.go
  pkg/gatherers/clusterconfig/gather_olm_operators_test.go
  pkg/gatherers/clusterconfig/gather_openshift_logging_test.go
  pkg/gatherers/clusterconfig/gather_openstack_controlplanes_test.go
  pkg/gatherers/clusterconfig/gather_openstack_dataplane_deployments_test.go
  pkg/gatherers/clusterconfig/gather_openstack_dataplane_node_sets_test.go
  pkg/gatherers/clusterconfig/gather_openstackversions_test.go
  pkg/gatherers/clusterconfig/gather_pod_disruption_budgets_test.go
  pkg/gatherers/clusterconfig/gather_prometheus_tsdb_status_test.go
  pkg/gatherers/clusterconfig/gather_service_accounts_test.go
  pkg/gatherers/clusterconfig/gather_silenced_alerts_test.go
  pkg/gatherers/clusterconfig/gather_storage_cluster_test.go
  pkg/gatherers/common/gather_logs.go
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/gatherers/conditional/filter_and_gather_container_logs.go
  pkg/gatherers/conditional/gather_pod_definition_test.go
  pkg/gatherers/workloads/gather_workloads_runtime_infos_test.go
  pkg/insights/metrics.go
  pkg/insights/types/types.go
  pkg/ocm/clustertransfer/cluster_transfer.go
  pkg/ocm/clustertransfer/cluster_transfer_test.go
  pkg/ocm/sca/sca.go
  pkg/utils/strings_test.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1046 OCPBUGS-45479: avoid possible Go panic when searching existing conditions
  pkg/controller/status/datagather_status.go
  pkg/controller/status/datagather_status_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1047 [release-4.18] OCPBUGS-45201: LokiStack gatherer
  docs/gathered-data.md
  docs/insights-archive-sample/namespaces/openshift-logging/lokistack-sample.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/gather_lokistack.go
  pkg/gatherers/clusterconfig/gather_lokistacks_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1052 NO-JIRA: minor test update
  pkg/gatherers/conditional/filter_and_gather_container_logs_test.go
Labels: approved, lgtm, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#1050 OCPBUGS-45926: use joinHostPort to fix IPv6
  pkg/gatherers/workloads/gather_workloads_runtime_infos.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1048 [release-4.17] OCPBUGS-45202: LokiStack gatherer
  docs/gathered-data.md
  docs/insights-archive-sample/namespaces/openshift-logging/lokistack-sample.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/gather_lokistack.go
  pkg/gatherers/clusterconfig/gather_lokistacks_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1055 OCPBUGS-44211: Ignore previous status when disabling alerts
  pkg/insights/prometheus_rules.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1051 [release-4.16] OCPBUGS-45203: LokiStack gatherer
  docs/gathered-data.md
  docs/insights-archive-sample/namespaces/openshift-logging/lokistack-sample.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/gather_lokistack.go
  pkg/gatherers/clusterconfig/gather_lokistacks_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference
