Repository openshift/insights-operator, pull requests merged in 2024-09, with the labels that each got.

#986 OCPBUGS-39111: collect some nmstate customresources
  docs/gathered-data.md
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkconfigurationpolicies/policy-name.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-21-41.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-24-83.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-42-30.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-61-249.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-78-199.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-85-177.us-east-2.compute.internal.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy.go
  pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy_test.go
  pkg/gatherers/clusterconfig/gather_nmstate_nodenetworkstate.go
  pkg/gatherers/clusterconfig/gather_nmstate_nodenetworkstate_test.go
  pkg/gatherers/clusterconfig/testdata/node_network_configuration_policy.yaml
  pkg/gatherers/clusterconfig/testdata/node_network_state_no_interfaces.yaml
  pkg/gatherers/clusterconfig/testdata/node_network_state_with_interfaces.yaml
  pkg/gatherers/clusterconfig/testdata/node_network_state_with_interfaces_and_mac_addresses.yaml
  pkg/gatherers/conditional/filter_and_gather_container_logs.go
  pkg/gatherers/conditional/gather_containers_logs.go
  pkg/gatherers/conditional/gathering_functions.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#974 [release-4.16] OCPBUGS-38021: Integration of the OpenStack CRs into the insights-operator
  docs/anonymized-data.md
  docs/gathered-data.md
  docs/insights-archive-sample/insights-operator/gathers.json
  docs/insights-archive-sample/namespaces/openstack/core.openstack.org/openstackcontrolplanes/openstack-galera-network-isolation.json
  docs/insights-archive-sample/namespaces/openstack/core.openstack.org/openstackversions/openstack-galera-network-isolation.json
  docs/insights-archive-sample/namespaces/openstack/dataplane.openstack.org/openstackdataplanedeployments/edpm-deployment.json
  docs/insights-archive-sample/namespaces/openstack/dataplane.openstack.org/openstackdataplanenodesets/openstack-edpm-ipam.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/gather_openstack_controlplanes.go
  pkg/gatherers/clusterconfig/gather_openstack_controlplanes_test.go
  pkg/gatherers/clusterconfig/gather_openstack_dataplane_deployments.go
  pkg/gatherers/clusterconfig/gather_openstack_dataplane_deployments_test.go
  pkg/gatherers/clusterconfig/gather_openstack_dataplane_node_sets.go
  pkg/gatherers/clusterconfig/gather_openstack_dataplane_node_sets_test.go
  pkg/gatherers/clusterconfig/gather_openstack_helpers.go
  pkg/gatherers/clusterconfig/gather_openstackversions.go
  pkg/gatherers/clusterconfig/gather_openstackversions_test.go
  pkg/gatherers/clusterconfig/gather_sap_datahubs.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#988 OCPBUGS-32233: Not able to enable repositories during entitled build in OCP Cluster on IBM-Z
  pkg/controller/operator.go
  pkg/insights/insightsclient/insightsclient.go
  pkg/insights/insightsclient/requests.go
  pkg/ocm/sca/sca.go
  pkg/ocm/sca/sca_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#982 NO-JIRA: minor update of cluster transfer code & increase the code co…
  pkg/controller/operator.go
  pkg/insights/insightsclient/insightsclient.go
  pkg/ocm/clustertransfer/cluster_transfer.go
  pkg/ocm/clustertransfer/cluster_transfer_test.go
  pkg/ocm/clustertransfer/test-data/empty.json
  pkg/ocm/clustertransfer/test-data/no-secret-data-cluster-transfer.json
  pkg/ocm/clustertransfer/test-data/not-json.json
Labels: approved, lgtm, qe-approved, jira/valid-reference

#993 OCPBUGS-39111: add missing permission to get nmstate CRs
  manifests/03-clusterrole.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#989 [release-4.17] OCPBUGS-39393: collect some nmstate customresources (#…
  docs/gathered-data.md
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkconfigurationpolicies/policy-name.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-21-41.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-24-83.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-42-30.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-61-249.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-78-199.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-85-177.us-east-2.compute.internal.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy.go
  pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy_test.go
  pkg/gatherers/clusterconfig/gather_nmstate_nodenetworkstate.go
  pkg/gatherers/clusterconfig/gather_nmstate_nodenetworkstate_test.go
  pkg/gatherers/clusterconfig/testdata/node_network_configuration_policy.yaml
  pkg/gatherers/clusterconfig/testdata/node_network_state_no_interfaces.yaml
  pkg/gatherers/clusterconfig/testdata/node_network_state_with_interfaces.yaml
  pkg/gatherers/clusterconfig/testdata/node_network_state_with_interfaces_and_mac_addresses.yaml
  pkg/gatherers/conditional/filter_and_gather_container_logs.go
  pkg/gatherers/conditional/gather_containers_logs.go
  pkg/gatherers/conditional/gathering_functions.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#996 NO-JIRA: update docs/arch.md to mention the Rapid Recommendations
  docs/arch.md
Labels: approved, lgtm, qe-approved, jira/valid-reference

#995 [release-4.16] OCPBUGS-39394: collect some nmstate customresources
  docs/gathered-data.md
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkconfigurationpolicies/policy-name.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-21-41.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-24-83.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-42-30.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-61-249.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-78-199.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-85-177.us-east-2.compute.internal.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy.go
  pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy_test.go
  pkg/gatherers/clusterconfig/gather_nmstate_nodenetworkstate.go
  pkg/gatherers/clusterconfig/gather_nmstate_nodenetworkstate_test.go
  pkg/gatherers/clusterconfig/testdata/node_network_configuration_policy.yaml
  pkg/gatherers/clusterconfig/testdata/node_network_state_no_interfaces.yaml
  pkg/gatherers/clusterconfig/testdata/node_network_state_with_interfaces.yaml
  pkg/gatherers/clusterconfig/testdata/node_network_state_with_interfaces_and_mac_addresses.yaml
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1000 OCPBUGS-41932: set the RemoteConfigurationAvailable and RemoteConfigu…
  pkg/controller/periodic/periodic.go
  pkg/controller/periodic/periodic_test.go
  pkg/controller/status/controller.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1002 [release-4.15] OCPBUGS-39395: collect some nmstate customresources
  docs/gathered-data.md
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkconfigurationpolicies/policy-name.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-21-41.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-24-83.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-42-30.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-61-249.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-78-199.us-east-2.compute.internal.json
  docs/insights-archive-sample/cluster-scoped-resources/nmstate.io/nodenetworkstates/ip-10-0-85-177.us-east-2.compute.internal.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy.go
  pkg/gatherers/clusterconfig/gather_nmstate_node_network_configuration_policy_test.go
  pkg/gatherers/clusterconfig/gather_nmstate_nodenetworkstate.go
  pkg/gatherers/clusterconfig/gather_nmstate_nodenetworkstate_test.go
  pkg/gatherers/clusterconfig/testdata/node_network_configuration_policy.yaml
  pkg/gatherers/clusterconfig/testdata/node_network_state_no_interfaces.yaml
  pkg/gatherers/clusterconfig/testdata/node_network_state_with_interfaces.yaml
  pkg/gatherers/clusterconfig/testdata/node_network_state_with_interfaces_and_mac_addresses.yaml
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1004 NO-JIRA: changelog update
  CHANGELOG.md
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1003 OCPBUGS-32233: Not able to enable repositories during entitled build in OCP Cluster on IBM-Z
  pkg/ocm/sca/sca.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference
