Repository openshift/insights-operator, pull requests merged in 2024-01, with the labels that each got.

#890 [release-4.12] OCPBUGS-24256: adds helm information gather
  docs/gathered-data.md
  docs/insights-archive-sample/config/helmchart_info.json
  pkg/gather/gather.go
  pkg/gatherers/workloads/gather_helm_info.go
  pkg/gatherers/workloads/gather_helm_info_test.go
  pkg/gatherers/workloads/types.go
  pkg/gatherers/workloads/types_test.go
  pkg/gatherers/workloads/workloads_gatherer.go
  pkg/gatherers/workloads/workloads_gatherer_test.go
  pkg/gatherers/workloads/workloads_info_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#891 [release-4.11] OCPBUGS-25711: adds helm information gather
  docs/gathered-data.md
  docs/insights-archive-sample/config/helmchart_info.json
  pkg/gather/gather.go
  pkg/gatherers/workloads/gather_helm_info.go
  pkg/gatherers/workloads/gather_helm_info_test.go
  pkg/gatherers/workloads/types.go
  pkg/gatherers/workloads/types_test.go
  pkg/gatherers/workloads/workloads_gatherer.go
  pkg/gatherers/workloads/workloads_gatherer_test.go
  pkg/gatherers/workloads/workloads_info_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#893 OCPBUGS-26188: another attempt to fix security warning for changelog script
  cmd/changelog/main.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#897 OCPBUGS-28616: gather etcd_server_slow metrics
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/gatherers/clusterconfig/gather_most_recent_metrics.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference
