Repository openshift/insights-operator, pull requests merged in 2024-07, with the labels that each got.

#953 NO-JIRA: introduce JSON schema & validation for rapid container logs
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/gatherers/conditional/container_log.schema.json
  pkg/gatherers/conditional/container_logs.schema.json
  pkg/gatherers/conditional/parsing.go
  pkg/gatherers/conditional/validation.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#959 NO-JIRA: always store remote configuration and metrics in the archive
  pkg/controller/gather_commands.go
  pkg/controller/periodic/periodic.go
  pkg/gather/gather.go
  pkg/gatherers/clusterconfig/gather_most_recent_metrics.go
  pkg/gatherers/clusterconfig/gather_most_recent_metrics_test.go
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/gatherers/conditional/default_remote_configuration.json
  pkg/gatherers/conditional/types.go
  pkg/record/record.go
  pkg/recorder/recorder.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#962 [release-4.14] OCPBUGS-36475: properly encode the URL for the advisor links
  cmd/gendoc/main.go
  pkg/controller/periodic/periodic.go
  pkg/controller/periodic/periodic_test.go
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/metrics.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#963 OCPBUGS-36687: Start collecting haproxy_exporter_server_threshold metric
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/gatherers/clusterconfig/gather_most_recent_metrics.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#967 [release-4.15] OCPBUGS-36805: Set required-scc for openshift workloads
  manifests/06-deployment-ibm-cloud-managed.yaml
  manifests/06-deployment.yaml
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#965 [release-4.13] OCPBUGS-36745: properly encode the URL for the advisor links (#962)
  cmd/gendoc/main.go
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/metrics.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#968 OCPBUGS-37100: fix the configmapobserver notifications
  pkg/config/configobserver/configmapobserver.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#954 NO-JIRA: remove firing alerts from the config/metrics file
  docs/gathered-data.md
  docs/insights-archive-sample/config/metrics
  pkg/gatherers/clusterconfig/gather_most_recent_metrics.go
  pkg/gatherers/clusterconfig/gather_most_recent_metrics_test.go
Labels: approved, lgtm, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#964 NO-JIRA: limit the time for the new rapid container logs & update the endpoint
  config/pod.yaml
  pkg/gatherers/conditional/filter_and_gather_container_logs.go
Labels: approved, lgtm, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#951 OSPRH-5904: Integration of the OpenStack CRs into the insights-operator
  docs/anonymized-data.md
  docs/gathered-data.md
  docs/insights-archive-sample/insights-operator/gathers.json
  docs/insights-archive-sample/namespaces/openstack/core.openstack.org/openstackcontrolplanes/openstack-galera-network-isolation.json
  docs/insights-archive-sample/namespaces/openstack/core.openstack.org/openstackversions/openstack-galera-network-isolation.json
  docs/insights-archive-sample/namespaces/openstack/dataplane.openstack.org/openstackdataplanedeployments/edpm-deployment.json
  docs/insights-archive-sample/namespaces/openstack/dataplane.openstack.org/openstackdataplanenodesets/openstack-edpm-ipam.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/gather_openstack_controlplanes.go
  pkg/gatherers/clusterconfig/gather_openstack_controlplanes_test.go
  pkg/gatherers/clusterconfig/gather_openstack_dataplane_deployments.go
  pkg/gatherers/clusterconfig/gather_openstack_dataplane_deployments_test.go
  pkg/gatherers/clusterconfig/gather_openstack_dataplane_node_sets.go
  pkg/gatherers/clusterconfig/gather_openstack_dataplane_node_sets_test.go
  pkg/gatherers/clusterconfig/gather_openstack_helpers.go
  pkg/gatherers/clusterconfig/gather_openstackversions.go
  pkg/gatherers/clusterconfig/gather_openstackversions_test.go
  pkg/gatherers/clusterconfig/gather_sap_datahubs.go
Labels: approved, lgtm, qe-approved, jira/valid-reference
