Repository openshift/insights-operator, pull requests merged in 2024-06, with the labels that each got.

#941 OCPBUGS-34784: Collect aggregated Prometheus Alertmanager instances
  docs/gathered-data.md
  docs/insights-archive-sample/aggregated/custom_prometheuses_alertmanagers.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/gather_aggregated_instances.go
  pkg/gatherers/clusterconfig/gather_aggregated_instances_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#943 NO-JIRA: update OWNERS list
  OWNERS
Labels: approved, lgtm, qe-approved, jira/valid-reference

#942 OCPBUGS-34788: gather aggregated numbers of Pods and Netnamespaces with SDN annotations
  docs/gathered-data.md
  docs/insights-archive-sample/aggregated/pods_and_netnamespaces_with_sdn_annotations.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_pod_and_netnamespaces_with_sdn_annotation.go
  pkg/gatherers/clusterconfig/gather_pod_and_netnamespaces_with_sdn_annotation_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#947 OCPBUGS-33082: Add new use cases for networking obfuscation
  pkg/anonymization/anonymizer.go
  pkg/anonymization/anonymizer_test.go
  pkg/utils/apiserver.go
  pkg/utils/apiserver_test.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-low, jira/valid-reference

#945 OCPBUGS-35727: Ingress controller related certificates' validate dates gathering
  docs/gathered-data.md
  docs/insights-archive-sample/aggregated/ingress_controllers_certs.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_cluster_ingress_certificates.go
  pkg/gatherers/clusterconfig/gather_cluster_ingress_certificates_test.go
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#944 CCXDEV-12582: rapid recommendations with new status condition
  pkg/controller/gather_commands.go
  pkg/controller/gather_commands_test.go
  pkg/controller/operator.go
  pkg/controller/periodic/job.go
  pkg/controller/periodic/periodic.go
  pkg/controller/periodic/periodic_test.go
  pkg/controller/status/conditions.go
  pkg/controller/status/conditions_test.go
  pkg/controller/status/controller.go
  pkg/controller/status/controller_test.go
  pkg/controller/status/datagather_status.go
  pkg/controller/status/status.go
  pkg/controller/status/status_test.go
  pkg/controllerstatus/controllerstatus.go
  pkg/gather/gather.go
  pkg/gatherers/conditional/conditional_gatherer.go
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/gatherers/conditional/default_remote_configuration.json
  pkg/gatherers/conditional/filter_and_gather_container_logs.go
  pkg/gatherers/conditional/filter_and_gather_container_logs_test.go
  pkg/gatherers/conditional/parsing.go
  pkg/gatherers/conditional/parsing_test.go
  pkg/gatherers/conditional/types.go
  pkg/insights/insightsclient/requests.go
  pkg/insights/insightsclient/requests_test.go
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/insightsreport/insightsreport_test.go
  pkg/utils/errors.go
  pkg/utils/errors_test.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#952 OCPBUGS-35882: properly encode the URL for the advisor links
  pkg/controller/periodic/periodic.go
  pkg/controller/periodic/periodic_test.go
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/metrics.go
Labels: approved, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#957 [release-4.16] OCPBUGS-36149: properly encode the URL for the advisor links
  pkg/controller/periodic/periodic.go
  pkg/controller/periodic/periodic_test.go
  pkg/insights/insightsreport/insightsreport.go
  pkg/insights/metrics.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
