Repository openshift/insights-operator, pull requests merged in 2024-11, with the labels that each got.

#1025 CCXDEV-10979: Remove hardcoded log gatherers
  CHANGELOG.md
  docs/gathered-data.md
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/gather_kube_controller_manager_logs.go
  pkg/gatherers/clusterconfig/gather_kube_controller_manager_logs_test.go
  pkg/gatherers/clusterconfig/gather_openshift_apiserver_operator_logs.go
  pkg/gatherers/clusterconfig/gather_openshift_apiserver_operator_logs_test.go
  pkg/gatherers/clusterconfig/gather_openshift_authentication_logs.go
  pkg/gatherers/clusterconfig/gather_openshift_authentication_logs_test.go
  pkg/gatherers/clusterconfig/gather_sap_vsystem_iptables_logs.go
  pkg/gatherers/clusterconfig/gather_sap_vsystem_iptables_logs_test.go
  pkg/gatherers/clusterconfig/gather_scheduler_logs.go
  pkg/gatherers/clusterconfig/gather_scheduler_logs_test.go
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1028 NO-JIRA: Fix links to the OpenStack related CRs in the gathered-data doc
  docs/gathered-data.md
Labels: approved, lgtm, qe-approved, jira/valid-reference

#1020 NO-JIRA: Add conditional gatherer validation test cases
  pkg/gatherers/conditional/conditional_gatherer_test.go
  pkg/gatherers/conditional/validation_test.go
Labels: approved, ok-to-test, lgtm, qe-approved, jira/valid-reference

#1032 OCPBUGS-45044: insightsoperator.operator.openshift.io resource is cre…
  manifests/04-operator-cr.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#1022 OCPBUGS-45047: LokiStack gatherer
  docs/gathered-data.md
  docs/insights-archive-sample/namespaces/openshift-logging/lokistack-sample.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/gather_lokistack.go
  pkg/gatherers/clusterconfig/gather_lokistacks_test.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference
