Repository openshift/insights-operator, pull requests merged in 2025-01, with the labels that each got.

#1057 [release-4.15] OCPBUGS-45204: LokiStack gatherer
  docs/gathered-data.md
  docs/insights-archive-sample/namespaces/openshift-logging/lokistack-sample.json
  manifests/03-clusterrole.yaml
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/const.go
  pkg/gatherers/clusterconfig/gather_lokistack.go
  pkg/gatherers/clusterconfig/gather_lokistacks_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#1065 NO-JIRA: Add Ondrej user to OWNERS file
  OWNERS
Labels: approved, lgtm, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#1067 OCPBUGS-48154: Add a liveness probe to the extractor container
  manifests/10-insights-runtime-extractor.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only
