Repository openshift/insights-operator, pull requests merged in 2025-02, with the labels that each got.

#1071 CCXDEV-14824: Upgrade Golang to 1.23
  go.mod
Labels: approved, lgtm, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#1066 CCXDEV-12875: Enable Insight Operator entitlements for multi arch clusters
  config/pod.yaml
  manifests/03-clusterrole.yaml
  pkg/insights/insightsclient/insightsclient.go
  pkg/insights/insightsclient/requests.go
  pkg/insights/insightsclient/requests_test.go
  pkg/ocm/sca/architectures_gather.go
  pkg/ocm/sca/architectures_gather_test.go
  pkg/ocm/sca/sca.go
  pkg/ocm/sca/sca_test.go
Labels: approved, lgtm, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only

#1073 OCPBUGS-51109: Fix bad IPv6 address
  manifests/10-insights-runtime-extractor.yaml
  pkg/gatherers/workloads/gather_workloads_runtime_infos.go
Labels: approved, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#1068 [release-4.18] OCPBUGS-48790: Add a liveness probe to the extractor container
  manifests/10-insights-runtime-extractor.yaml
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference
