Repository openshift/insights-operator, pull requests merged in 2025-09, with the labels that each got.

#1122 OCPBUGS-61073: Rerun missed `make update` after read-only filesystem security context added
  manifests/06-deployment-ibm-cloud-managed.yaml
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference, acknowledge-critical-fixes-only

#1127 NO-JIRA: remove me from the OWNERS list
  OWNERS
Labels: approved, lgtm, qe-approved, jira/valid-reference, acknowledge-critical-fixes-only, verified

#1134 OCPBUGS-52838: Update error message for missing SCA certificates
  pkg/ocm/sca/sca.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference, verified, verified-later

#1138 [release-4.17] OCPBUGS-61775: virt launcher logs gatherer
  docs/gathered-data.md
  docs/insights-archive-sample/namespaces/default/pods/virt-launcher-example/virt-launcher.json
  pkg/gatherers/clusterconfig/clusterconfig_gatherer.go
  pkg/gatherers/clusterconfig/gather_cluster_ingress_certificates.go
  pkg/gatherers/clusterconfig/gather_qemu_kubevirt_launcher_logs.go
  pkg/gatherers/clusterconfig/gather_qemu_kubevirt_launcher_logs_test.go
  pkg/gatherers/common/gather_logs.go
Labels: approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified, verified-later

#1140 OCPBUGS-61798: Run missing make update
  manifests/06-deployment-ibm-cloud-managed.yaml
  profile-patches/ibm-cloud-managed/06-deployment.yaml-patch
Labels: approved, tide/merge-method-squash, lgtm, qe-approved, jira/valid-bug, jira/valid-reference, verified

#1142 [release-4.16] OCPBUGS-61108: avoid possible Go panic when searching existing conditions
  pkg/controller/status/datagather_status.go
  pkg/controller/status/datagather_status_test.go
Labels: approved, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#1131 OCPBUGS-60931: update DataGather condition when gathering job fails
  pkg/controller/gather_commands.go
  pkg/controller/periodic/job.go
  pkg/controller/periodic/periodic.go
  pkg/controller/status/datagather_status.go
Labels: approved, lgtm, qe-approved, jira/valid-bug, jira/valid-reference, verified
